### ISSUE TITLE
Different default hyperparameters in sklearn API

### ISSUE THREAD

**Issue by julioasotodv** [Microsoft/LightGBM#1014]
According to the hyperparameter docs (https://lightgbm.readthedocs.io/en/latest/Parameters.html):

`min_data_in_leaf, default=20, type=int, alias=min_data_per_leaf , min_data`

Whereas in the scikit-learn API (https://lightgbm.readthedocs.io/en/latest/Python-API.html#lightgbm.LGBMClassifier):

`min_child_samples (int, optional (default=10)) – Minimum number of data need in a child(leaf).`

As you can see, the default value for the hyperparameter changes.

The same happens in `min_sum_hessian_in_leaf`: in the booster API the default is `1e-3`, but in scikit-learn's API it is `5` for `min_child_weight`

Is there any reason for this change in the default value for those hyperparameters?

**Comment by guolinke** [comment]
@wxchan @StrikerRUS 
should we make them consistent ?

**Comment by StrikerRUS** [comment]
@guolinke As for me, I don't see reasons to make them inconsistent. Also, since they are cpp-level aliases, I think we should add them to the docs (so users will be able to use the same name in both CLI version and sklearn wrapper).
https://github.com/Microsoft/LightGBM/blob/1ef3d43ecd2068811273eb9226572aec694ee000/include/LightGBM/config.h#L389
https://github.com/Microsoft/LightGBM/blob/1ef3d43ecd2068811273eb9226572aec694ee000/include/LightGBM/config.h#L393

I can create a PR if you and @wxchan do not mind.

**Comment by julioasotodv** [comment]
Indeed @StrikerRUS, some hyperparameter names are different in the sklearn API compared to the ones in https://lightgbm.readthedocs.io/en/latest/Parameters.html, but I believe that all of them work when defined as in the sklearn API, so indeed it is a matter to add them to the docs as additional aliases.

**Comment by guolinke** [comment]
I remember why they are different now. I once changed the default parameters in cpp side, but forgot to change them in python package. 
so I think we should change to default parameter in python package. 
@StrikerRUS I think you can create a PR
