### ISSUE TITLE
[R package] why not set 'methods' and 'Matrix' as depended packages when building packages? 

### ISSUE THREAD

**Issue by chenwq** [Microsoft/LightGBM#1030]
Without pre-library these two packages, predict method will crash.

**Comment by Laurae2** [comment]
@chenwq They are not essential for the main functionalities of the package, they are still recommended to be installed by the user if they want to experience to full functionalities of the package (but this is not enforced, like for `data.table`, `magittr`, etc.).

In addition, those packages are not fully loaded on LightGBM package load. They are loaded and will be attached if they are installed only when required. => Imports

This does not apply to `R6`, which is the main driver of the package: without it, the core functionalities of the package would not work at all. They are loaded and attached when LightGBM loads for obvious reasons => Depends

It is a recommended practice to use Imports and not Depends unless the linked packages are essential for the core functionalities, in order to avoid plaguing the global environment with unexpected additional functions (no one wants a package loading 20 other packages on startup for instance).
