### ISSUE TITLE
fit(data_generator) possible?

### ISSUE THREAD

**Issue by mingwugmail** [Microsoft/LightGBM#1138]
Hi,

I know there is a 'two_round' option to handle large data, (BTW, I think this option 'two_round' needs some explanation, or a better name to the library user, e.g. why it's not called 'three_round'?), but I just wonder if is fit(data_generator) possible?  and suppose the user also gives the total_data_count in advance.

I found a similar question asked for sklearn:

https://stackoverflow.com/questions/20952418/using-python-generators-in-scikit-learn

I wonder if LightGBM can do better in this?

Thanks.

**Comment by mingwugmail** [comment]
I noticed cv() folds can take a generator or iterator:

https://github.com/Microsoft/LightGBM/blob/301e0a7c23ae8ef1c855c259034f44bf820bb67a/python-package/lightgbm/engine.py#L329

**Comment by guolinke** [comment]
@mingwugmail 
The `two_round` is really two rounds. 
The first round is to sample part of data, and use the sampling data to construct `bin_mapper` (map float feature values to binned feature values). 
The second round will read the data one by one and map them to binned values at the same time. 

Such a solution can reduce memory usage, since it doesn't need to all float feature values in memory. 

LightGBM is a in-memory algorithm, and it needs many preprocess based on full data.
So the data_generator is not possible.

**Comment by mingwugmail** [comment]
1) Another question is: does this means for GPU training, the data-set size will be limited by the GPU memory (instead of main memory)?

2) if the total_data_count is given in advance, why can't we still do the two_round as you mentioned above? just call the iterator/generator multiple times for the multi preprocess steps?

3) even for possible infinite data, how about https://en.wikipedia.org/wiki/Reservoir_sampling
and set k as the max memory the machine can handle. Can this dynamic sampling (i.e. the 'full dataset' is continuously changing) work with the current LightGBM algorithm? or is it possible to make it work?

**Comment by guolinke** [comment]
1. Current GPU implementation will be limited by both GPU and CPU memory. 
2. I think your solution is the same to save all data from generator to a file, and use two-round to read the data from file. The core algorithm of LightGBM is written by cpp. It is not trivial to pass a generator from python to  cpp side. As a result, use a file as buffer is a solution. 
3. Current implementation cannot deal with infinite data or dynamic dataset. You can make it work, however, it will be very slow since you will need to re-binned and re-boosting everytime you change a sample.
