### ISSUE TITLE
how much memory do i need, when i use two_rounds?

### ISSUE THREAD

**Issue by TaiChiBagua** [Microsoft/LightGBM#1189]
i tested the two_rounds option, for i have 40G data, but only 30G ram.
but it took too long to start training, or it hanged? almost an hour Loading.

So, what caused this?  The two_rounds also needed much memory? or Just because it is very slow？

i saw one comment says 

> there
https://github.com/Microsoft/LightGBM/issues/1138#issuecomment-353857567
：
 
but i don’t understand how, could someone explain this more detailed to me?

thx

**Comment by guolinke** [comment]
The memory cost when using `two_round` is about `(num_data * num_feature) Bytes` for dense features. 

you can check the memory usage. It should use much fewer memory if you pass the parameter correctly. 

`two_round` will have a additional pass of data file. So the reason may is your Disk speed is very slow.

**Comment by TaiChiBagua** [comment]
By num_data * num_feature， 
num_data is the number of total training data or the data sampled?

**Comment by guolinke** [comment]
it is number of total training data.

**Comment by TaiChiBagua** [comment]
thanks

**Comment by yangtian62** [comment]
@guolinke Hi, I have a training set of 16,000,000 data with 34 features (7.4G in libsvm format), when I train lighgbm with `two_round = True`, the memory usage jumps to over 8G no matter train with GPU or CPU, which seems like it loads all data to the memory at the same time, instead of only using (num_data * num_feature) Bytes. 

I just set `two_round = True` in params, am I doing it wrong?

thx

**Comment by guolinke** [comment]
@yangtian62 which version did you use? The CLI version should be fine.
For python version, you should set two_round in the parameters of lgb.dataset.

**Comment by yangtian62** [comment]
@guolinke Thanks for your reply! It seems working with CLI now. Best.
