### ISSUE TITLE
Max depth of each tree is max_depth - 1

### ISSUE THREAD

**Issue by tks0123456789** [Microsoft/LightGBM#125]
The parameter max_depth does limit the max depth for tree model but the max is max_depth -1.  Is this expected behavior?

**Comment by guolinke** [comment]
@tks0123456789 
LightGBM grows tree leaf-wise. It use ```num_leaves``` to control the complexity of tree model. And leaf-wise will have better accuracy.
However, when #data is small, leaf-wise may cause over-fitting, due to it may grow deep tree.
So LightGBM provide an option ```max_depth``` to limit the max depth. Tree still grow by leaf-wise.
When ```max_depth < 0 ``` means not limit the depth.

**Comment by guolinke** [comment]
The depth in LightGBM start from ```1```.  see : https://github.com/Microsoft/LightGBM/blob/master/src/io/tree.cpp#L43

Is it better to start from ```0``` ?

**Comment by tks0123456789** [comment]
Yes.  The usual meaning of depth is the number of edges from the root.
And the LightGBM's doc says "The relation is num_leaves = 2^(max_depth)."
https://github.com/Microsoft/LightGBM/blob/master/docs/Parameters.md#tuning-parameters

**Comment by guolinke** [comment]
@tks0123456789 
Thanks, fixed!
