### ISSUE TITLE
R package not building because of DCF error (DESCRIPTION file not formatted properly?)

### ISSUE THREAD

**Issue by vinhdizzo** [Microsoft/LightGBM#1270]
Hi,

I just downloaded LightGBM this morning and tried to build the R package.  I am getting the following error.  Seems like the DESCRIPTION file is not formatted correctly.
![image](https://user-images.githubusercontent.com/114053/37527832-394d3a78-28f0-11e8-89b4-03029b76e863.png)

**Comment by vinhdizzo** [comment]
I was able to build the R package if I modified the "Description" section of  `DESCRIPTION` to be:
```
Description: Tree based algorithms can be improved by introducing boosting frameworks.
```

I think that line might've been too long originally.

**Comment by guolinke** [comment]
@jameslamb

**Comment by jameslamb** [comment]
Thanks for bringing this to my attention! Will submit a fix soon

**Comment by jameslamb** [comment]
@vinhdizzo I was able to reproduce this error on my machine today. 

The issue is not the that first line is too long...it's the empty line I added when I added additional information to the `DESCRIPTION` in #1260 . I think that R does not like any blank lines in the `DESCRIPTION` file. I will update shortly
