### ISSUE TITLE
Failed R installation.

### ISSUE THREAD

**Issue by quantitative-technologies** [Microsoft/LightGBM#1307]
## Environment info
Operating System: Ubuntu 17.10
CPU: 
C++/Python/R version: R version 3.4.2

## To reproduce:

> install_github("Microsoft/LightGBM", subdir = "R-package")
...
Warning messages:
1: GitHub repo contains submodules, may not function as expected! 
2: In get(Info[i, 1], envir = env) : internal error -3 in R_decompress1

> library(lightgbm)
Loading required package: R6
Error: package or namespace load failed for ‘lightgbm’ in get(Info[i, 1], envir = env):
 lazy-load database '/home/james/R/x86_64-pc-linux-gnu-library/3.4/data.table/R/data.table.rdb' is corrupt
In addition: Warning message:
In get(Info[i, 1], envir = env) : internal error -3 in R_decompress1

According to the `install_github` documentation, I tried to use `install_git`. However this gives the error:
`Installation failed: Error in 'git2r_clone': Unsupported URL protocol`

**Comment by Laurae2** [comment]
Your package seems corrupted, restart R and reinstall LightGBM. (It seems you installed packages over already started packages, this won't work)

**Comment by quantitative-technologies** [comment]
Yes, you were correct about installing over started packages. It works for me with `install.packages`, btw.
So everything seems OK now.

**Comment by Laurae2** [comment]
@quantitative-technologies It doesn't work for LightGBM because it requires a library which cannot be fully unloaded (like most libraries hooking onto R directly, C side). Therefore, if attempting to overwrite the package (by reinstalling the package live), it will overwrite nearly all files except the critical ones, and will error automatically at startup.
