### ISSUE TITLE
Issue with 'random_state' parameter in LightGBM 2.1.0

### ISSUE THREAD

**Issue by AlexandraBomane** [Microsoft/LightGBM#1331]
I am using lightgbm 2.1.0 for a binary classification problem.

Here, my model : 

from sklearn.feature_selection import SelectKBest
from sklearn.feature_selection import f_classif
from lightgbm.sklearn import LGBMClassifier
from sklearn.pipeline import Pipeline

clf = Pipeline([("selectfeat", SelectKBest(f_classif)), ("model", LGBMClassifier(n_estimators = 1000, subsample = 0.8, colsample_bytree = 0.8, n_jobs = 1, random_state = 1234))])

When I fit the model to my data, I got this error : " KeyError: 'random_state' "

Indeed, the error message also reports which part of the code of lightgbm triggers this error : 

/usr/local/lib/python2.7/dist-packages/lightgbm/sklearn.py
388         # sklearn interface has another naming convention
389         params.setdefault('seed', params.pop('random_state'))

Nothing in the documentation and in LGBMClassifier parameters indicates that 'random_state' cannot be used. And I think that it is strange to go back to previous naming convention so drastically in an upgraded version, whereas it was changed in previous versions (e.g. lightgbm 2.0.10) to respect Scikit-Learn conventions.

**Comment by mlisovyi** [comment]
Hi,

I'm also using lightgbm 2.1.0 (installed via conda) and for me the `random_state` arg of the sklearn API works (also in the fit). The differencesin what i have tried: _I do not use a pipeline._

The line that you pointed out prepares arguments for the native lightgbm.train() call. I'm a new user, so i do not know the history of past releases. But the code looks as if `random_state` was implemented in the sklearn API, but the native API kept the original arg names. This is not a problem (only a little confusion for users of different API's). The problem is that in your case the code thinks that there is no `random_state` attribute of the class as collected by get_params(), and thus `params.pop('random_state')` raises the `KeyError`. Why does it happen- i have no idea. More experienced people can comment. How to fix it/ improve on it- do `params.pop('random_state', None)` in that line (and the following one for `n_jobs` ).

**Comment by AlexandraBomane** [comment]
I have got the same issue with LightGBM 2.0.10 but with the parameter "n_jobs".

**Comment by mlisovyi** [comment]
@StrikerRUS could you please comment?

**Comment by StrikerRUS** [comment]
@AlexandraBomane Could you reproduce the error with latest version and random data? Please provide random data generator code.

**Comment by guolinke** [comment]
ping @AlexandraBomane

**Comment by StrikerRUS** [comment]
@AlexandraBomane On my compute the following code works fine. The only change of your code I've made was `k='all'`

```
from sklearn.feature_selection import SelectKBest
from sklearn.feature_selection import f_classif
from lightgbm.sklearn import LGBMClassifier
from sklearn.pipeline import Pipeline

clf = Pipeline([("selectfeat", SelectKBest(f_classif, k='all')),
                ("model",LGBMClassifier(n_estimators=1000,
                                        subsample=0.8,
                                        colsample_bytree=0.8,
                                        n_jobs=1,
                                        random_state=1234))])

from sklearn.datasets import load_iris

iris = load_iris()
clf.fit(iris.data, iris.target).predict(iris.data)
```

**Comment by StrikerRUS** [comment]
ping @AlexandraBomane 
Is this problem still presented in your environmental?

**Comment by AlexandraBomane** [comment]
I was running several models like that with the function Parallel().
When I set the argument "backend" as "multiprocessing", instead of "threading", I solved the problem.
