### ISSUE TITLE
Weighted node count from dump_model

### ISSUE THREAD

**Issue by aokeson** [Microsoft/LightGBM#1425]
In the tree structure obtained from the dump_model function, the tree nodes include a node count field (internal_count, leaf_count), but do not include a weighted count of samples that pass through each node. I am looking for something similar to sklearn's weighted_n_node_samples tree structure attribute ([source code here](https://github.com/scikit-learn/scikit-learn/blob/master/sklearn/tree/_tree.pyx)). Is it possible to get this weighted count information from the LightGBM tree structure obtained by dump_model?

**Comment by guolinke** [comment]
You can use `sum_hessian` . The output prediction value in leaf is calculated by sum_grad/sum_hess.

**Comment by aokeson** [comment]
It looks like sum_hessian is just in the source code. Is there any way to obtain it without modifying the C code in feature_histogram?

**Comment by guolinke** [comment]
oh, sorry, I forget that.

However, I think you can get sum_hessian via some calculation. 

According to `leaf_value = - sum_grad / sum_hess`, and `split_gain = left_sum_grad^2 / left_sum_hess + right_sum_grad^2 / right_sum_hess - (left_sum_grad + right_sum_grad)^2 / (left_sum_hess + right_sum_hess)` . 

For each leaf, you can get its father's split_gain and output_value ( `internal_value`), and its neighborhood's output_leaf. 
Since there are 4 equations and 4 variables, I think we can get sum_grad and sum_hess from that.

**Comment by guolinke** [comment]
close now. feel free to reopen if not resolved.
