### ISSUE TITLE
[Warning] No further splits displayed even with verbose=-1

### ISSUE THREAD

**Issue by goldentom42** [Microsoft/LightGBM#1486]
Hi there, I think this issue was tracked on #640 and closed as far as I'm aware.

## Environment info
Operating System: Linux and windows (can't test on Apple)
C++/Python/R version: latest version (I believe Kaggle uses the latest master branch), occurs also on 2.1.0

## Reproducible examples
https://www.kaggle.com/ogrellier/lighgbm-with-selected-features

The problem only occurs **with lgb.train** (LGBClassifier does not exhibit the same issue) and only if **eval_sets** argument is provided.

![image](https://user-images.githubusercontent.com/17214417/42148603-32237e1e-7dd3-11e8-984d-46f277542d6a.png)

Let me know if you need any further info.
Thanks, Olivier

**Comment by StrikerRUS** [comment]
@goldentom42 Thank you for your example. It's very helpful because we're working on this problem right now, but the discussion is taking place in a closed issue (#1157).

I think that I'd better close this issue and reopen that one. I'll be very glade if you copy your example there (and maybe add something).
