### ISSUE TITLE
[LightGBM] [Fatal] Data file doesn't exist

### ISSUE THREAD

**Issue by AbhishekY09** [Microsoft/LightGBM#1540]
## Environment info
R version: 3.5

## Error Message: [LightGBM] [Fatal] Data file doesn't exist

Getting this error on the following step:
my_preds <- predict(model, test[, 1:4])

**Comment by guolinke** [comment]
@Laurae2 
@AbhishekY09 It seems that is a R's problem. can you try to restart R session and rerun again ?

**Comment by Laurae2** [comment]
@AbhishekY09 can you provide a reproducible example?

**Comment by PankajPatil1** [comment]
Facing same problem

**Comment by PankajPatil1** [comment]
Faced same problem. For me it was because the matrix I was using had values as character rather than numeric

**Comment by MichaelLLi** [comment]
I have the same problem. I eventually figured the problem is twofold:

1. There is an error in the code lgb.Predictor.R. Line 100 reads:
` preds <- read.delim(tmp_filename, header = FALSE, seq = "\t")`
Pretty sure it should be sep, not seq.


2. If you have a character matrix as your predict data, **or you used as.matrix**, the checking condition for filename in the same file on line 83:
` if (is.character(data)) {`
would be true and the function would misinterpret your data as a filename, and tries to execute line 100, which gives you the warning from read.delim. 

Use predict(model, data.matrix(your_data_here)) to solve the problem.

**Comment by Laurae2** [comment]
ping @jameslamb

**Comment by jameslamb** [comment]
@MichaelLLi I would be happy to address this. Do you have a reproducible example you can share, so I'll know whether or not I've fixed it?

**Comment by jameslamb** [comment]
#1638 was definitely needed either way, since `seq` is not a valid arg to `read.delim()`. Ah, the joys of R's `...`

**Comment by MichaelLLi** [comment]
@jameslamb Currently afk but will upload a reproducible example tonight EST

**Comment by jameslamb** [comment]
ok no problem! in the interim I can still make a PR to add a better "is a file" check

**Comment by Laurae2** [comment]
I passed some changes in #1638, it should handle character matrix corner case and correct the sep/seq issue. Will push it when checks are done.
