### ISSUE TITLE
Support for .Net4.6 in LightGBM nuget.

### ISSUE THREAD

**Issue by codemzs** [Microsoft/LightGBM#1566]
Hi @guolinke,

We need a structure like below to also make .net 4.6 work. 

* lightgbm
  * 2.2.2.2
     * net46
       * runtimes
          * lib_lightgbm.dll
           * lightgbm.exe
     * netstandard2.0
        * runtimes
          * linux-x86
            * native
              * lib_lightgbm.so
             * osx-x64
                * native
                  * lib_lightgbm.dylib
             * win-x64
                * native
                  * lib_lightgbm.dll
                  * lightgbm.exe

Let me know once you have the nuget ready and I can verify it on ML.NET side before you push it. 
@https://github.com/dotnet/machinelearning/issues/494
CC: @eerhardt @shauheen @galoshri @tomfinley @sharpwood

**Comment by sharpwood** [comment]
How is progress, can this be released with the ML 0.4 release? @codemzs

**Comment by eerhardt** [comment]
For anyone looking for a work around until this issue gets fixed, see https://stackoverflow.com/a/51728825/3680432.

@guolinke - a possible fix for this issue is to follow the same pattern we use in the `Microsoft.ML` package, which is to add a `.props` file to the package that adds the native assembly when `packages.config` is being used.  (Note we also have a `.targets` file that checks the project is targeting `x64`.)

Feel free to copy this code into your NuGet package:

https://github.com/dotnet/machinelearning/blob/94a3d90cba7787973d1ee300e0a88a30653b2d9a/pkg/Microsoft.ML/build/netstandard2.0/Microsoft.ML.props
https://github.com/dotnet/machinelearning/blob/94a3d90cba7787973d1ee300e0a88a30653b2d9a/pkg/Microsoft.ML/build/netstandard2.0/Microsoft.ML.targets

Put those 2 files in a `build` folder in the nupkg and edit any references to Microsoft.ML -> LightGBM.  Note the name of the files need to match the name of your nuget package.

**Comment by codemzs** [comment]
@sharpwood Unfortunately this won't go in for 0.4 release.

**Comment by eerhardt** [comment]
@guolinke - MSBuild files go into the `build` folder.

Check out this document, which has a table showing what each folder in a NuGet package is used for:

https://docs.microsoft.com/en-us/nuget/create-packages/creating-a-package#from-a-convention-based-working-directory

For example, in our `Microsoft.ML` package, we have MSBuild files in the `build` folder, .NET assemblies in the `lib` folder, and native binaries in the `runtimes` folder:

![image](https://user-images.githubusercontent.com/8291187/43846349-bfac0d7c-9af3-11e8-81e9-457b0c89e707.png)

In `Microsoft.ML`, we only support `netstandard2.0`, so that's why we have the MSBuild files in `build\netstandard2.0` and our .NET assemblies in `lib\netstandard2.0`.

However, for `LightGBM`, since there are no .NET assemblies, you don't need to put anything in the `lib` folder.  And the MSBuild files can go directly in the `build` folder (not a subfolder).

**Comment by StrikerRUS** [comment]
Can this issue and original one be closed, since https://github.com/dotnet/machinelearning/pull/1234 has been merged?
@codemzs @eerhardt @guolinke
