### ISSUE TITLE
Image Not Found Error on importing lightgbm as lgb

### ISSUE THREAD

**Issue by OmkaarTheGreat** [Microsoft/LightGBM#1573]
Please search your question on previous issues, [stackoverflow](https://stackoverflow.com/questions/tagged/lightgbm) or other search engines before you open a new one.

For bugs and unexpected issues, please provide following information, so that we could reproduce on our system.

## Environment info
Operating System: Mac OSX High Sierra
CPU: 2.5Ghz Intel 15
C++/Python/R version: python 3.6

## Error Message:
OSError: dlopen(/Users/otg/anaconda3/lib/python3.6/site-packages/lightgbm/lib_lightgbm.so, 6): Library not loaded: /usr/local/opt/gcc/lib/gcc/8/libgomp.1.dylib
  Referenced from: /Users/otg/anaconda3/lib/python3.6/site-packages/lightgbm/lib_lightgbm.so
  Reason: image not found
## Steps to reproduce
1. type import lightgbm as lgb

Pretty Surprising as it doesnt happen on windows Jupyter, python 3.6. lightgbm is installed...

**Comment by StrikerRUS** [comment]
What versions of gcc and LightGBM are you using?

**Comment by StrikerRUS** [comment]
@OmkaarTheGreat I suppose that your issue is practically the same as #1369. The only difference is that you are trying to run rather old LightGBM with the newest gcc. So, you can either downgrade your gcc version, or install the latest LightGBM (this way is recommended).

Feel free to reopen this issue with new details, if you are still cannot make LightGBM work.
