### ISSUE TITLE
Treating missing values as zeros in sparse mode

### ISSUE THREAD

**Issue by captify-acherednychenko** [Microsoft/LightGBM#162]
Hey there, thanks for the great product.

Would be great to have ability to mark missing features as ones, having zeros. My case - I am training on large sparse file, with numbers of features > 1M. I hacked a code slightly to automatically put trivial features as categorical, but that has no effect.

Please assist, some instructions on what to change in the code would be acceptable

Thanks,
Andrii

**Comment by guolinke** [comment]
@captify-acherednychenko 
you want let missing values to be treated as ```1```?

**Comment by captify-acherednychenko** [comment]
@guolinke 
thanks for an immediate reply. no, basically, I want trivial (having only one value) features to be included in training. I am adding only 1 into the file, otherwise it will blow-up.

so, I changed code slightly, to treat them as categorical, but that has no effect, as I don't have 0 values in the file (I assume)

would be great to have a quick code change advice

thanks

**Comment by guolinke** [comment]
@captify-acherednychenko 
If these ignored features actually is not trivial, you can change ``bin_construct_sample_cnt`` to a bigger value (default is 50000). 

If they are really trivial, it will have not effect on training even you add them force, due to data cannot split according to these features.

**Comment by captify-acherednychenko** [comment]
ok, let's imagine case - I want to describe if user have seen some document on the web. If user did - I put 1 for that feature. For sure, I don't put 0 in case user haven't seen a doc, otherwise file will blow up.

As a result, for that feature, I have only 1s in the file, and LightGBM is treating this feature as trivial, which I am sure is not the case?

Please assist.
Thanks

**Comment by guolinke** [comment]
@captify-acherednychenko I think LightGBM can handle this naturally. It will try missing value as zero.
And you are using Libsvm format, right? 
can you paste a sample of your data like?

**Comment by captify-acherednychenko** [comment]
yes, using Libsvm, for example here is part of file which contains only 4 occurrences of 49312 feature.  however, in log I see that this feature is ignored.

note that those are parts of files, as original ones are pretty big.

[guolinke.sample.libsvm.txt](https://github.com/Microsoft/LightGBM/files/684299/guolinke.sample.libsvm.txt)
[guolinke.log.txt](https://github.com/Microsoft/LightGBM/files/684298/guolinke.log.txt)

Thanks,
Andrii

**Comment by guolinke** [comment]
I see. Just of part of these features are ignored, not all of them, right? 
The reason is LightGBM sample part of data to construct bin mapper. When data is too sparse, the sampled data in some features may are all zeros, so these feature will be ignored.

If you really want to use all of them, you can set ```bin_construct_sample_cnt``` to your number of row of data.

And set feature to categorical feature doesn't help for this situation.

**Comment by captify-acherednychenko** [comment]
setting bin_construct_sample_cnt actually doesn't help. will continue investigation later, closing this issue so far
