### ISSUE TITLE
Plot functions for Python/R wrapper

### ISSUE THREAD

**Issue by guolinke** [Microsoft/LightGBM#171]
welcome to contribute for this feature.

**Comment by Laurae2** [comment]
@guolinke I think it is done in R package and Python package for now.

What else do you think users might need? (partial dependence plots?)

**Comment by HareenVenigalla** [comment]
@Laurae2  Hi, Is any one working on partial dependency plots ?

**Comment by Laurae2** [comment]
@HareenVenigalla not yet I think

**Comment by guolinke** [comment]
refer to a better visual analytics tool: https://github.com/thu-vis/BOOSTVis2

**Comment by ethen8181** [comment]
Hi team, checking to see if the partial dependency plot functionality is still on the to-be-included list. Thanks!

**Comment by xin-jin** [comment]
^Would really love to see Partial dependence plots, too.

**Comment by Laurae2** [comment]
@guolinke I might work on it in the next months to integrate tabplot for LightGBM R package: https://cran.r-project.org/web/packages/tabplot/vignettes/tabplot-vignette.html - it's (unconsciously) a generalization of partial dependency plots for large datasets, although it is not producing plots which are exactly 100% perfectly accurate (due to dealing with binning).
