### ISSUE TITLE
bdist_wheel doesn't allow any flags

### ISSUE THREAD

**Issue by KOLANICH** [microsoft/LightGBM#1863]
In fact some of these flags are unneeded, instead distutils prefs should be used. So maybe custom steps are unneeded too.

**Comment by StrikerRUS** [comment]
@KOLANICH Please elaborate.

Are you unable to install lightgbm from Python wheel? What error is raised?

**Comment by KOLANICH** [comment]
>Are you unable to install lightgbm from Python wheel?

I'm unable to build a wheel using the prebuilt library, since no custom command class is implemented for that command.

https://github.com/Microsoft/LightGBM/blob/d8d01e39843c4e93d6e9cb9d2c17bc6d138f4975/python-package/setup.py#L275L279

IMHO these "custom cmd classes" inherited from the original ones are too dirty hacky approaches, instead setuptools should be redesigned into a graph of stages with possibility to insert an own stage between any 2.

IMHO these

https://github.com/Microsoft/LightGBM/blob/d8d01e39843c4e93d6e9cb9d2c17bc6d138f4975/python-package/setup.py#L185L198

flags shouldn't be used, instead it should always use the lib prebuilt with CMake.

**Comment by StrikerRUS** [comment]
> I'm unable to build a wheel using the prebuilt library

Please share your use-case where you need this.

> instead it should always use the lib prebuilt with CMake.

How to build, say, MPI version with `pip` in this case?

**Comment by KOLANICH** [comment]
>Please share your use-case where you need this.

It is more convenient for me to use CMake for building. I don't use Visual Studio for building, instead I use MinGW-w64 and Ninja as a low level build tool, all the libraries are situated in unexpected folders.

>How to build, say, MPI version with pip in this case?

Just enable that option in CMakeCache.txt ?

**Comment by StrikerRUS** [comment]
> . I don't use Visual Studio for building, instead I use MinGW-w64 and Ninja as a low level build tool

Just use `--mingw` option with correctly configured PATH to build with MinGW.
But why you need wheel file for this?


> Just enable that option in CMakeCache.txt ?

Please elaborate. At present, I can just execute `pip install lightgbm --install-option=--mpi`. How to do it without those options?

**Comment by StrikerRUS** [comment]
Also, we already have the option to use **prebuilt library file**.
```
python setup.py install --precompile
```
 Have you seen it?

**Comment by KOLANICH** [comment]
>But why you need wheel file for this?

Because I prefer to store wheels of working versions of binary libraries as backups. So if something goes wrong, I just install the old wheel.

>How to do it without those options?

As usual when using CMake. Prebuild the library enabling `USE_MPI` and then install using the prebuilt library.

>Just use `--mingw` option

this option is unneeded and should be removed. The compiler to be used is configured in [distutils.cfg](https://docs.python.org/3/install/#location-and-names-of-config-files) and your stuff should not override it.

**Comment by StrikerRUS** [comment]
> Because I prefer to store wheels of working versions of binary libraries as backups

Ah, got it! However, this is very uncommon case because usually wheel distribution is made by developers, not users. However, if it's important for you, you can work with wheel file just like with ordinary archive: build library file and replace the default one in wheel.

> As usual when using CMake. Prebuild the library with CMake enabling USE_MPI and then b8ild and install the package using the prebuilt library.

Do you agree, that it's more inconvenient way, compared with one-line command?

> The compiler to be used is configured in distutils.cfg and your stuff should not override it.


This is legacy document.
### Installing Python Modules (Legacy version)

Also, nothing is overridden while LightGBM installation.

**Comment by StrikerRUS** [comment]
> This branch explicitly uses Visual Studio.

Uses, but not overrides.

LightGBM achieves it's best performance if compiled with VS, not MinGW. You can read more about it in [FAQ](https://lightgbm.readthedocs.io/en/latest/FAQ.html#lightgbm) Question 4 and 8. This is the reason why VS is used by default. But, as I've already said, you are able to build LightGBM with MinGW via one-line command.

> In order to make a wheel without rebuilding the lib we need to fix the scripts.

I don't think so. As I've said earlier, building special versions of wheels is very rare need for usual users and moreover can be achieved by some manual steps.
In general, the current implementation of the installation process is well-tested by the time, comfortable for ordinary users and works without any additional modifications of source files. I think that it doesn't worth to steal from users all present facilities available through options in order to implement unclaimed feature.

**Comment by StrikerRUS** [comment]
However, you are very welcome to contribute the changes which will allow preserve the current comfort for ordinary users and **enhance** the installation process with additional features.

**Comment by guolinke** [comment]
@StrikerRUS any updates for this issue? should it be in the feature request?

**Comment by StrikerRUS** [comment]
@guolinke According to the no references and comments for a quite long time, it seems that this feature is not demanded.

> In general, the current implementation of the installation process is well-tested through the time, comfortable for ordinary users and works without any additional modifications of source files. I think that it doesn't worth to steal from users all present facilities available through options in order to implement unclaimed feature.
