### ISSUE TITLE
No module named 'lightgbm'

### ISSUE THREAD

**Issue by ronzhou** [Microsoft/LightGBM#1963]
Operating System: win10

CPU/GPU model: gpu

C++/Python/R version: python

LightGBM version or commit hash: 2.2.3

## Error message

I was following the setup process of the gpu version of lightgbm on win10.  After the setup, I can run perfectly with the test case, But the problem is I cannot import lightgbm with anaconda spyder? "No module named 'lightgbm'", could you please help me figure it out?

Thanks!!

**Comment by StrikerRUS** [comment]
Hi @ronzhou !

Seems that you are launching Spyder from another conda environment.

**Comment by StrikerRUS** [comment]
This may help you to indicate key words to start googling your issue: https://stackoverflow.com/questions/46142967/how-to-ensure-that-spyder-runs-within-a-conda-environment

**Comment by ronzhou** [comment]
It only has one conda environment in my system. Maybe, the problem is that I uninstall anaconda by mistake before. I used lightgbm before with an old anaconda ( it was build at C:\\) . After the uninstall, I reinstall a new anaconda ( at D:\\), and a new lightgbm. After that, I cannot use it anymore. But the test case works fine. So the problem maybe that the lightgbm was not installed in a right conda environment.

Many Thanks!

**Comment by StrikerRUS** [comment]
Yeah, that's for sure that something is wrong with your environment!

Unfortunately, I'm not familiar with Spyder, but the first thing I saw when launched it was this setting:

![image](https://user-images.githubusercontent.com/25141164/51838057-4e372400-2316-11e9-9858-0155c01c7305.png)

I'm going to close this issue because it's unrelated to LightGBM. I suppose that stackoverflow is better place to ask your question. I'm sure that gurus there know what you should do install Spyder and LightGBM in the same environment.

Feel free to ask any further questions connected to LightGBM installation process.

**Comment by chjq201410695** [comment]
I counter same problem except I use jupyter lab. any update on this issue?
