### ISSUE TITLE
Python scikit-learn predict_proba returns probabilities > 1

### ISSUE THREAD

**Issue by ClimbsRocks** [Microsoft/LightGBM#198]
## Environment info
Operating System: Mac OSX Sierra
CPU: 2013 2 GHz Intel Core i7

## Error Message:
None in LightGBM

Sorry I can't provide a data example, but we're working with our company's non-public data. 

The issue is that predict_proba returned values > 1, which can obviously break some scoring functions, and does not make logical sense. 

That said, as the user, I personally would want to know when the model is so freaking confident about something that it's predicting > 100% chance. So really more of a design question for the team to decide on: does it make sense to be returning probabilities > 1?

**Comment by guolinke** [comment]
@ClimbsRocks Can you share for a example code?

**Comment by wxchan** [comment]
it happened with binary classification or multiclass?

**Comment by ClimbsRocks** [comment]
Ah, just realized the lower bound isn't bounded at 0 either. 

  File "/Users/preston/anaconda3/lib/python3.5/site-packages/sklearn/metrics/classification.py", line 1807, in _check_binary_probabilistic_predictions
    raise ValueError("y_prob contains values less than 0.")
ValueError: y_prob contains values less than 0.

This is all inside of [auto_ml](https://github.com/ClimbsRocks/auto_ml), a library I wrote that just takes in a dataset from the user, and trains a sklearn-based machine learning pipeline on the data. 

It perfectly illustrates the benefits of having such a consistent interface: with just a very few lines of code I was able to swap out XGBoost/GradientBoostingClassifier for LightGBM. But it also means that a code example is, well the whole library, and not particularly useful for filing issues :)

**Comment by ClimbsRocks** [comment]
@wxchan binary classification

**Comment by guolinke** [comment]
@ClimbsRocks can you provide more details ? e.g. the functions you called, the parameters ..

**Comment by wxchan** [comment]
seem xgboost has same issue: https://github.com/dmlc/xgboost/pull/1899

is there any constraint to ensure the output between 0 and 1?

**Comment by guolinke** [comment]
@wxchan really? I think the output after sigmoid should be in (0,1)

**Comment by wxchan** [comment]
what if sigmoid < 0?

**Comment by guolinke** [comment]
@wxchan  https://github.com/Microsoft/LightGBM/blob/master/src/boosting/gbdt.cpp#L658-L672

if sigmoid <= 0, it will not use the  sigmoid transform. 

https://github.com/Microsoft/LightGBM/blob/master/src/boosting/gbdt.cpp#L69-L74 

And sigmoid will only be set when using "binary" objective. 

So the only possible way is calling wrong objective function, e.g. regression, or use custom objective.

**Comment by ClimbsRocks** [comment]
@guolinke : that's exactly it! I was just copy/pasting the example code to see how quickly i could get this up and running for a quick MVP before bed, and left `objective='regression'` in there for the classifier. at some point i'll try to submit a PR for either user input validation, or an example update.

**Comment by wxchan** [comment]
@guolinke we can remove `objective` from init and infer it from which subclass they use.

**Comment by guolinke** [comment]
@wxchan OK, 
So the only way to use the custom objective function is using LGBMModelBase. 
And we should give some information that the prediction of LGBMModelBase is the raw scores.

**Comment by wxchan** [comment]
@guolinke I forgot `objective` is also for custom objective. Then we should leave it, perhaps add a warning if user sets up `wrong` objective string.

**Comment by mirekphd** [comment]
Perhaps `predict_proba()` should error when invoked for a model with a regression `objective`? Currently this function returns only incorrect predictions in such situation and these that can only be identified as such if some of them happen to fall outside of the [0, 1] range. 

This problem is not at all easy to spot on someone else's model exposed to you e.g. through an API, unless your test cases contain extreme target values and the model was good enough to convert them into equally extreme probability predictions.

**Comment by guolinke** [comment]
@StrikerRUS 
can you follow @mirekphd 's suggestion?

**Comment by StrikerRUS** [comment]
@guolinke Sorry, but I'm confused a little bit. `predict_proba` is presented only in `LGBClassifier` class and we are checking objective for correctness during `fit` stage:
https://github.com/Microsoft/LightGBM/blob/93a899ac7c80b7e71ea2ccc31b4f15ba3fabb7dd/python-package/lightgbm/sklearn.py#L717-L721
https://github.com/Microsoft/LightGBM/blob/93a899ac7c80b7e71ea2ccc31b4f15ba3fabb7dd/python-package/lightgbm/sklearn.py#L434-L438


`LGBMModel` class is supposed to be used with any objective, because this is general class...

This issue is very old and many changes in codebase were done. What is the actual problem here at the current moment?

**Comment by mirekphd** [comment]
I managed to  invoke `predict_proba()` in my online scoring API on an intended classification model that was trained without setting `objective` to "binary", i.e. on a regressor. The model we loaded from a pickle must have had unset `objective` parameter. I've just checked that the `_objective` property check you quoted from already existed in sklearn.py in the older LightGBM version 2.2.2 where the bug was caught. I will try to make it into a fully reproducible bug report if time permits.

**Comment by mirekphd** [comment]
You were right @StrikerRUS, it was `predict` that generated negative predictions (from a regressor), not `predict_proba`. Trying to use `predict_proba` on a regressor would have raised `AttributeError`. So would in fact on a classifier...  (on a Booster object created by `import lightgbm as lgbm` and trained with 'binary' objective). In a nutshell, `predict_proba` is missing from a Booster object.

Setting `objective` to "binary" eliminates negative and above-unity predictions returned by `predict`, turning them into probabilities, which is fine. But even in such situations where probabilities are returned, the only function we can use is called `predict`, and the expected function named `predict_proba` is not available.

I attach a reproducible example illustrating my points:
- incorrect (out-of-probability-range) predictions returned by `predict`(the only function available for a Booster) when `objective` is left at its default, rather than being set to 'binary' (which is a user error),
- missing `predict_proba` on a Booster even with 'binary' objective, where instead `predict` can be made to return probas - given correct objective (and lack of `predict_proba` for a classifier is arguably a bug).


```
# from lightgbm import LGBMClassifier as lgbm_clf

import lightgbm as lgbm
# !pip freeze | grep lightgbm
# lightgbm==2.2.2

from sklearn.datasets import make_classification
# !pip freeze | grep scikit-learn
# scikit-learn==0.20.3

import numpy
# !pip freeze | grep numpy
# numpy==1.15.4

X_fake, y_fake = make_classification(n_samples=100, n_features=10, n_classes=2, random_state=123)

optimal_params = {'learning_rate': 0.1, 'num_boost_round': 100, 'max_depth': 5, 'random_state': 123}

dtrain = lgbm.Dataset(X_fake, label=y_fake)

# note: boosting rounds cannot be supplied via params
num_boost_round=optimal_params["num_boost_round"]
del optimal_params["num_boost_round"]

# objective='binary'
# optimal_params["objective"] = objective

clf = lgbm.train(params=optimal_params, 
                 train_set=dtrain, 
                 num_boost_round=num_boost_round,
                 verbose_eval=10)

print(clf.params)

clf_pred = clf.predict(X_fake)
print(np.min(clf_pred))
print(np.max(clf_pred))

clf_pred_proba = clf.predict_proba(X_fake)
```

Output:

```
{'learning_rate': 0.1, 'max_depth': 5, 'random_state': 123}
min prediction: -0.08134217799742426
max prediction: 1.1642666993419126
---------------------------------------------------------------------------
AttributeError                            Traceback (most recent call last)
<ipython-input-1369-dc4b661edf43> in <module>
     37 print(np.max(clf_pred))
     38 
---> 39 clf_pred_proba = clf.predict_proba(X_fake)
     40 

AttributeError: 'Booster' object has no attribute 'predict_proba'
```

If we set objective to "binary", `predict` would finally return probabilities, but `predict_proba` would still remain unavailable:

```
{'learning_rate': 0.1, 'max_depth': 5, 'random_state': 123, 'objective': 'binary'}
min prediction: 0.00013774165232793132
max prediction: 0.9996720571806066
---------------------------------------------------------------------------
AttributeError                            Traceback (most recent call last)
<ipython-input-1373-55466d0144c7> in <module>
     37 print("max prediction:", np.max(clf_pred))
     38 
---> 39 clf_pred_proba = clf.predict_proba(X_fake)
     40 

AttributeError: 'Booster' object has no attribute 'predict_proba'

```

**Comment by mirekphd** [comment]
As a side note: the use of `lightgbm.Booster` instead of `lightgbm.LGBMClassifier` should not be ruled out or discouraged. It earned for instance actual prize money for the runner up team during Porto Seguro Kaggle competition:
https://www.kaggle.com/xiaozhouwang/2nd-place-lightgbm-solution
https://github.com/xiaozhouwang/kaggle-porto-seguro/blob/master/code_for_exact_solution/lightgbm1.py

**Comment by StrikerRUS** [comment]
@mirekphd Thanks for reproducible example! Everything are getting more clear now.

Mixing sklearn wrapper with ordinary Python API is strongly discouraged, because it can lead to many issues.

Scikit-learn has very strict API requirements for estimators which are checked by their tests and LightGBM follows them.

Sklearn wrapper is supposed to be used by users who want simple in usage interface. If one want to mix up different APIs which have no guaranteed compatibility between each other, then they are quite expertized users and can deal with such problems (and not only them).

For ordinary Python API the default objective is `regression` and it is stated [here](https://lightgbm.readthedocs.io/en/latest/Parameters.html#objective). `Booster` hasn't `predict_proba` method because it's from "another world", and has nothing in common with scikit-learn one.

Linking https://github.com/Microsoft/LightGBM/issues/1942#issuecomment-453975607 here.

**Comment by StrikerRUS** [comment]
@mirekphd 
However, if you have any cool ideas for ordinary Python and sklearn APIs interaction enhancement, PR is very welcome!

**Comment by StrikerRUS** [comment]
One more addition.

> So would in fact trying to use it on a classifier... (on a Booster object created by import lightgbm as lgbm and trained with 'binary' objective).

By extending @mirekphd's example it can be shown that `booster` obtained from sklearn's `LGBMClassifier` with default objective (`None`) predicts probabilities.

```
…
sklearn_clf = lgbm.LGBMClassifier()
sklearn_clf.fit(X_fake, y_fake)

bst = sklearn_clf.booster_
bst_pred = bst.predict(X_fake)
print(np.min(bst_pred))
print(np.max(bst_pred))
print(bst.params)
```

```
0.00013774165232793132
0.9996720571806066
{'boosting_type': 'gbdt', 'colsample_bytree': 1.0, 'learning_rate': 0.1, 'max_depth': -1, 'min_child_samples': 20, 'min_child_weight': 0.001, 'min_split_gain': 0.0, 'n_jobs': -1, 'num_leaves': 31, 'objective': 'binary', 'random_state': None, 'reg_alpha': 0.0, 'reg_lambda': 0.0, 'subsample': 1.0, 'subsample_for_bin': 200000, 'subsample_freq': 0, 'verbose': -1, 'metric': {'binary', None}}
```
So, `'objective': 'binary'` is propagated to ordinary Python API correctly.
