### ISSUE TITLE
[OOM] How to use Big data on distributed clusters?

### ISSUE THREAD

**Issue by sosofun** [microsoft/LightGBM#2077]
## Environment info

Operating System: ubuntu 16.04

CPU/GPU model: lightGBM-GPU

C++/Python/R version: 

LightGBM version or commit hash: lightgbm 2.2.4

## Error message
/usr/local/src/lightgbm/LightGBM/lightgbm config=train.conf
[LightGBM] [Info] Finished loading parameters
[LightGBM] [Warning] Set TCP_NODELAY failed
[LightGBM] [Info] Trying to bind port 55000...
[LightGBM] [Info] Binding port 55000 succeeded
[LightGBM] [Info] Listening...
[LightGBM] [Warning] Set TCP_NODELAY failed
[LightGBM] [Warning] Set TCP_NODELAY failed
[LightGBM] [Info] Connected to rank 0
[LightGBM] [Info] Local rank: 1, total number of machines: 2
[LightGBM] [Info] Finished initializing network
[LightGBM] [Warning] There are no meaningful features, as all feature values are constant.
[LightGBM] [Info] Finished linking network in 0.039458 seconds
Met Exceptions:
std::bad_alloc

## Reproducible examples
train.conf
--------
task = train
boosting_type = gbdt
tree_learner = data

objective = multiclass

metric = multi_logloss,multi_error
num_class = 3
metric_freq = 1
is_training_metric = true
max_bin = 256

data = data.full.train
valid_data = data.full.predict

early_stopping = 10
num_trees = 10000
learning_rate = 0.05
num_leaves = 31
num_machines = 2
machine_list_file = mlist.txt
local_listen_port = 55000

## Steps to reproduce

1.  data.full.train  file size:143GB;  Mem:500GB
2. exec on mlist  : /usr/local/src/lightgbm/LightGBM/lightgbm config=train.conf

**Comment by guolinke** [comment]
1. try `two_round=true`.
2. you can pre-partition the training data randomly, and set `pre_partition=true`.

**Comment by sosofun** [comment]
> 1. try `two_round=true`.
> 2. you can pre-partition the training data randomly, and set `pre_partition=true`.

sorry , I've tried this set  `two_round=true`, It can't work properly；
and how to pre-partition the training data randomly?  and multi files list how to config the train.conf?

**Comment by guolinke** [comment]
```
[LightGBM] [Warning] There are no meaningful features, as all feature values are constant.
```
It seems this issue is not OOM. The `bad_alloc` may throw by allocation with zero length.

**Comment by MrTuesday1020** [comment]
Hi @guolinke and @sosofun  I have encountered the **std::bad_alloc** issue:

LightGBM version: latest version
Operating System: Centos7
OpenMPI version: 3.1.0

task = train
boosting_type = gbdt
objective = binary
metric = binary_logloss,auc
metric_freq = 1
is_training_metric = true 
max_bin = 255
data = /LightGBM/traindata
valid_data = /LightGBM/testdata
num_trees = 100
learning_rate = 0.05
num_leaves = 63
tree_learner = data
num_threads = 8
feature_fraction = 0.8
bagging_freq = 5
bagging_fraction = 0.8
min_data_in_leaf = 50
min_sum_hessian_in_leaf = 5.0
is_enable_sparse = true
is_save_binary_file = false
two_round=true (I have tried **true** and **false** both)

**traindata** is about **1TB** and it is pre-partitioned into **96** machines(so each machine has about 10GB data).
Each machine is allocated with a **64GB** memory.  

I also added some log into the source code by myself and it seems the problem comes from **FinBin()** function in **ConstructBinMappersFromTextData()**. Code before Sample text data always works fine.

I randomly picked up one record of data: 0 428:1.0 704:1.0 19276:1.0 82787:1.0 106353:1.0 112915:1.0 171617:1.0 227895:1.0 505199:1.0 518888:1.0 525710:1.0 577081:1.0 763152:1.0 777976:1.0 820292:1.0 861076:1.0 907526:1.0 1072966:1.0 1110977:1.0 1216110:1.0 1368875:1.0 1398260:1.0 1420681:1.0 1424443:1.0 1438837:1.0 1483208:1.0 1488299:1.0 1500267:1.0 1503768:1.0 1506918:1.0 1589200:1.0 1629034:1.0 1644303:1.0 1714990:1.0 1867464:1.0 1879084:1.0 1884482:1.0 2014938:1.0 2048395:1.0 2065817:1.0 2117294:1.0 2139124:1.0 2165819:1.0 2216195:1.0 2503433:1.0 2563454:1.0 2578627:1.0 2591111:1.0 2598311:1.0 2683530:1.0 2701472:1.0 2718053:1.0 2733392:1.0 2878968:1.0 2892757:1.0 2902307:1.0 2904794:1.0 2988016:1.0 3012273:1.0 3014834:1.0 3043851:1.0 3133724:1.0 3165156:1.0 3399929:1.0 3533454:1.0 3587752:1.0 3693881:1.0 3733998:1.0 3801436:1.0 3827877:1.0 3839530:1.0 3899001:1.0 4024956:1.0 4069879:1.0 4232301:1.0 4245332:1.0 4301082:1.0 4307840:1.0 4309349:1.0 4349240:1.0 4403299:1.0 4421106:1.0 4450561:1.0 4499222:1.0 4535027:1.0 4571320:1.0 4612339:1.0 4619757:1.0 4636903:1.0 4650983:1.0 4662850:1.0 4663207:1.0 4729755:1.0 4742960:1.0 4743428:1.0 4765131:1.0 4789308:1.0 4810325:1.0 4922915:1.0 4966529:1.0 5017410:1.0 5213599:1.0 5519204:1.0 5522937:1.0 5524018:1.0 5549049:1.0 5566985:1.0 5590818:1.0 5669088:1.0 5698389:1.0 5715012:1.0 5789414:1.0 5894284:1.0 5947841:1.0 6012478:1.0 6044747:1.0 6072826:1.0 6108886:1.0 6116776:1.0 6118263:1.0 6131018:1.0 6157647:1.0 6253061:1.0 6324936:1.0 6384764:1.0 6436926:1.0 6483685:1.0 6492601:1.0 6538571:1.0 6575884:1.0 6601245:1.0 6878223:1.0 6930173:1.0 6967800:1.0 6985314:1.0 7025926:1.0 7076362:1.0 7097476:1.0 7125669:1.0 7144583:1.0 7172989:1.0 7200286:1.0 7268971:1.0 

It seems it is because all the label value is 1.0(which means this feature has been used) that causes this issue when it tries to find bins. 
Any idea and suggestion? Thanks:)

**Comment by guolinke** [comment]
@MrTuesday1020 I guess the reason is the very large features.
From the log, it seems you use the one-hot coding for categorical features.
It will be much faster if you use categorical feature directly, refer to https://github.com/microsoft/LightGBM/blob/master/docs/Advanced-Topics.rst#categorical-feature-support

**Comment by MrTuesday1020** [comment]
@guolinke Thanks for your quick response and the problem has been solved. Here are two points I want to say:
1. As LightGBM assumes that all the features are numerical type and we need to specify which ones are categorical type by the parameter "**categorical_feature**". However in my case, it seems impossible to do so because all of them are categorical features and it is quite large set of features. So how about we add some parameters to declare all the feature type is categorical  and we could specify numeric ones by parameter, for example, "**numeric_feature**".
2. From line 919 to 921 in src/io/dataset_loader.cpp, that is where cause the **bad_alloc** issuse. When **num_total_features** is very large(in my case it is), **buffer_size** will be larger than the max value of **size32_t** and becomes a negative number(**integer overflow**). I think this is a bug need to be fixed, maybe **comm_size_t**  should be set as **size64_t**.
```
    comm_size_t buffer_size = type_size * num_total_features;
    auto input_buffer = std::vector<char>(buffer_size);
    auto output_buffer = std::vector<char>(buffer_size);
```

**Comment by guolinke** [comment]
Thanks @matsuken92 for valuable feedbacks.

Indeed, the format of `categorical_feature` needs to be refined.

For the comm_size_t, using 64bit size for communication seems impractical. 
Therefore, I would like to add some Asserts here, throw the exception when it overflows.

**Comment by guolinke** [comment]
@sosofun could you provide which line causes the bad_alloc ? Thanks very much.

**Comment by MrTuesday1020** [comment]
@guolinke how about using **usize32_t** for **comm_size_t**?

**Comment by guolinke** [comment]
@MrTuesday1020 
All size types in LightGBM are signed types, for its better compatibility. 
BTW, I check the code, changing comm_size_t to int64_t can work.

**Comment by yingc123** [comment]
@guolinke 
lightgbm.basic.LightGBMError: vector::reserve     
happens when I try to save binary of the file.
The file is about 1TB with  2658851949  lines with 95 features.
Is it too large for once all put into lightGBM?

**Comment by guolinke** [comment]
I think 2,658,851,949 is larger than int32_max(2,147,483,647).
You can try to set data_size_t to int64_t : https://github.com/microsoft/LightGBM/blob/7189743d224a405bb48050834460d107fb7c1c0b/include/LightGBM/meta.h#L18

**Comment by PhilipMay** [comment]
Hi,
has this been fixed on code level? I wonder that this issue got just closed without further comments.
Thanks
Philip

**Comment by guolinke** [comment]
I think this is fixed in recent codes
