### ISSUE TITLE
[SOLVED] Building from source with JAVAWrapper on Ubuntu 16.04

### ISSUE THREAD

**Issue by Paperone80** [Microsoft/LightGBM#2148]
## Environment info

Operating System: Ubuntu 16.04 LTS

CPU/GPU model: 2xIntel 4110/NVIDIA RTX 2080 Ti

C++/Python/R version: GCC: 5.4.0 Python:3.5

LightGBM version or commit hash: 2.2.4

## Error message

When building with -DUSE_SWIG=ON, I got the following error messages: 

> ../build/java/lightgbmlibJAVA_wrap.cxx:176:17: fatal error: jni.h: No such file or directory
> compilation terminated.

> In file included from ../build/java/lightgbmlibJAVA_wrap.cxx:176:0:
> /usr/lib/jvm/java-8-openjdk-amd64/include/jni.h:45:20: fatal error: jni_md.h: No such file or directory
> compilation terminated.

## Reproducible examples

My cmake line is: 
```
sudo cmake .. \
-DUSE_GPU=1 \
-DOpenCL_LIBRARY=/usr/local/cuda/lib64/libOpenCL.so \
-DOpenCL_INCLUDE_DIR=/usr/local/cuda/include \
-DUSE_MPI=ON \
-DUSE_SWIG=ON \
-DJAVA_INCLUDE_PATH=/usr/lib/jvm/java-8-openjdk-amd64/include \
-DJAVA_AWT_LIBRARY=/usr/lib/jvm/java-8-openjdk-amd64/jre/lib/amd64/libjawt.so \
-DJAVA_AWT_INCLUDE_PATH=/usr/lib/jvm/java-8-openjdk-amd64/include
```
and 
`sudo make -j32`

## Resolution 
For successfully build I had to add: 
`sudo apt-get install swig openjdk-8-jdk-headless openjdk-8-jdk`
and 
`-DCMAKE_CXX_FLAGS="-I/usr/lib/jvm/java-8-openjdk-amd64/include -I/usr/lib/jvm/java-8-openjdk-amd64/include/linux`

You can find your location of jni.h and jni_md.h via 
```
sudo find /usr/lib/jvm/ | grep jni.h
/usr/lib/jvm/java-8-openjdk-amd64/include/jni.h
sudo find /usr/lib/jvm/ | grep jni_md.h
/usr/lib/jvm/java-8-openjdk-amd64/include/linux/jni_md.h
```
Add the directory of the respective file, not the path to the file itself. 

Hope that saves some time!

**Comment by StrikerRUS** [comment]
Hi @Paperone80 !

Thanks a lot for sharing your experience!

I assume that your `cmake` command is too complicated and can be simplified a lot. We are building SWIG wrapper at our CI service with OpenJDK too, and it's enough just to set `JAVA_HOME` environmental variable. I suppose it will allow to omit all `-DJAVA_...` flags in the command. Ping @imatiach-msft for the confirmation.

https://github.com/Microsoft/LightGBM/blob/804c5cdfa7c187f3197d4fa69452bf4ad48ca060/.ci/dockers/ubuntu-14.04/Dockerfile#L43-L50

https://github.com/Microsoft/LightGBM/blob/804c5cdfa7c187f3197d4fa69452bf4ad48ca060/.ci/test.sh#L22-L24

You can ignore `CMAKE_OPTS` variable, because it's used only for discovering OpenMP libraries on macOS Mojave. In all other cases it's just empty.


https://github.com/Microsoft/LightGBM/blob/804c5cdfa7c187f3197d4fa69452bf4ad48ca060/.ci/test.sh#L11-L19

**Comment by Paperone80** [comment]
Hi @imatiach-msft @StrikerRUS 

Thanks for the quick reply. I tried your suggestion and this worked for me: 
```
$ export JAVA_HOME=/usr/lib/jvm/java-8-openjdk-amd64/
$ sudo -E cmake .. \
-DUSE_GPU=1 \
-DOpenCL_LIBRARY=/usr/local/cuda/lib64/libOpenCL.so \
-DOpenCL_INCLUDE_DIR=/usr/local/cuda/include \
-DUSE_MPI=ON -DUSE_SWIG=ON
$ sudo make
```
Important part was 'sudo -E' to pass the environment variables down when sudo. Without '-E' I got the same error again.
