### ISSUE TITLE
Monotonic constraints not working with multiple features in dataset

### ISSUE THREAD

**Issue by timocb** [microsoft/LightGBM#2309]
I'm experiencing an issue where, when using multiple input features, the relationship between a single feature and the prediction is not monotonic, while I am applying `monotone_constraints` on this particular feature. `monotone_constraints` works correctly when training and predicting on a single feature. When using multiple features and applying the constraint on only 1 of 2 features, it does not work as expected.

## Environment info
Operating System:
macOS Mojave 10.14.6

CPU/GPU model:
Intel Core i7 / Intel Iris Graphics 6100 1536 MB

C++/Python/R version:
Python 3.6.8

LightGBM version or commit hash:
2.2.3

## Reproducible examples

Simple example:
```
import numpy as np
import pandas as pd
import lightgbm as lgb

size = 100
df = pd.DataFrame(
    {
        "x": np.linspace(0, 10, size),
        "x2": np.random.random(size),
        "y": np.linspace(0, 10, size)**2 + 10 - (20 * np.random.random(size))
    }
)

# Apply a monotonic constraint on "x", none on "x2"
monotone_model = lgb.LGBMRegressor(min_child_samples=5, monotone_constraints="1,0")
monotone_model.fit(df.drop('y', axis=1), df['y'])
 
monotone_output = pd.DataFrame(
    {
        "x": df["x"],
        "x2": df["x2"],
        "y": df["y"],
        "y_pred": monotone_model.predict(df.drop('y', axis=1))
    }
)
```
This provides the following output (created with altair):
![output](https://user-images.githubusercontent.com/42134934/62457846-e9083380-b77b-11e9-8431-ecc9f4f8988b.png)

This output is not monotonic.

Here is a notebook exploring the issue:
https://gist.github.com/timocb/7e6a0fbb8713fbaf05cfd5e4fb8a0d1a

Using:
numpy: 1.17.0
pandas 0.24.2
altair: 3.1.0
lightgbm: 2.2.3

## Steps to reproduce
1. Train LightGBM on multiple features, applying monotonic constraints on a single features.
2. Visualize relationship between this feature and the prediction.
3. Result: Relation is not monotonic.

**Comment by CharlesAuguste** [comment]
I think that the issue is related to the definition of monotonicity. The usual definition of monotonicity for multivariate functions, which is used by LightGBM, it that when you move only a single variable, then the function is monotone with respect of this variable (whatever the value of the rest of the variables). For example, a function real f of 2 real variables is increasing with respect to the first variable if 
![image](https://user-images.githubusercontent.com/17216645/62537990-a3b23780-b849-11e9-995f-5ad40e8fe165.png)

In your graph, you plotted y_pred with respect to x. But each prediction is related to a different x2. So the previous definition does no apply, because you should have the same x2 for every prediction for the plot to appear monotone.

**Comment by timocb** [comment]
@CharlesAuguste 

Thanks for the explanation, I believe you are correct. Given the same `x2`, `x` should be monotonic. But that obviously does not appear in the plot when `x2` also changes.

Issue can be closed.
