### ISSUE TITLE
Categorical feature: does LightGBM deal with non-int data types?

### ISSUE THREAD

**Issue by jsh9** [microsoft/LightGBM#2362]
In the documentation here (https://lightgbm.readthedocs.io/en/latest/Parameters.html#categorical_feature), it is stated that categorical feature values must be integers.

However, in another documentation (https://lightgbm.readthedocs.io/en/latest/pythonapi/lightgbm.train.html#lightgbm.train), the categorical features values only need to be lower than int32 max value.

I tried to specify a float column as categorical feature, and the training works. The script is as follows:

```python
import pandas as pd
import lightgbm as lgb
from sklearn import datasets

X_, y = datasets.load_wine(return_X_y=True)
X = pd.DataFrame(X_, columns=['col_%d' % _ for _ in range(X_.shape[1])])
d_train = lgb.Dataset(X, y)

param = dict(max_depth=5)
model = lgb.train(param, d_train, num_boost_round=20, 
                  categorical_feature=['col_0'])   # col_0's data type is float

x = X.iloc[4, :]
y_pred = model.predict(x)
```

Can I get some clarification here?  Thanks!

**Comment by StrikerRUS** [comment]
@jsh9 You described the expected behavior. The first link is for LightGBM CLI version, and the second one is for Python-package. So, in CLI version it's possible to use only ints, and for Python-package you can use some other data types. 
https://github.com/microsoft/LightGBM/blob/4fc0416fabee5ba8f062f6d7dd966e1b207b7f4f/tests/python_package_test/test_engine.py#L639-L644

If you are interested, here is the comment, which elaborates why I wrote "some other data types": https://github.com/microsoft/LightGBM/issues/2134#issuecomment-520261059.

**Comment by StrikerRUS** [comment]
@jsh9

Sure, here are answers for your question: https://github.com/microsoft/LightGBM/issues/804#issuecomment-507169407, https://github.com/microsoft/LightGBM/issues/1936#issuecomment-463958324.
