### ISSUE TITLE
how lgb.Dataset reference work and how data value affect bin construction

### ISSUE THREAD

**Issue by aprilffff** [microsoft/LightGBM#2553]
>First Question
when I contruct a valid set binary file, It's clear that I should set reference as a contructed-train-binary-file. But I'm wondering how "reference" work here. 
1. whether use same num of bin count?
2. same bin cut thresholds for every feature in validset construnction? 

>Second Question
After bins constructed, raw values of features are replaced by the index of bins. But during the calculation of leafouts or infogain, it only uses  the bin indices or uses something like mean-rawvalue-withinbin? I mean if I have two trainsets, and the order of data is the same, but the  value is not same,  I still could get same constructed binary dataset and same boosting results(keep every train param the same)?

**Comment by guolinke** [comment]
there is a "bin mapper", which stores how to map the continues floating values to discrete bins, in the dataset. Set reference will use the reference's (usually trainset) bin mapper to construct the valid set.

For the information gain, only the order of feature matters, since the features values only decide the cut point,  and don't be taken account into information gain calculation.
