### ISSUE TITLE
Installation of Python lib on Alpine Linux

### ISSUE THREAD

**Issue by lmdehaas** [microsoft/LightGBM#2614]
Not sure if this is the place to mention this, but installation on Alpine (the `python:3.7.3-alpine3.9` Docker image to be precise) required the following commands (assuming that the build and installation of the right numpy/scipy/sklearn libraries is done separately):

```
apk add gcc g++ make cmake
export CXX=g++ CC=gcc
pip install wheel
pip install lightgbm
```

The requirement of make and cmake and the cmake environment variable config would be useful additions to the Python installation guide.

**Comment by StrikerRUS** [comment]
Indeed, when you build from sources, CMake is required. Refer to https://github.com/microsoft/LightGBM/tree/master/python-package#build-from-sources
> For Linux and macOS users, installation from sources requires installed CMake.


However, when you install **regular** version from PyPI for `x86_64` architecture, CMake is not required, because wheel file already contains compiled library file. Refer to
https://pypi.org/project/lightgbm/#files
