### ISSUE TITLE
Documentation Request: More information on finding the optimal ranges for parameter tuning?

### ISSUE THREAD

**Issue by duckladydinh** [microsoft/LightGBM#2617]
Hi,

I start to play with LightGBM and want to optimize its parameters according to the tuning documentation. I would like to ask if there is a way to determine a good range for each parameter? Like bagging fraction for example? The range [0, 1] is understandable but is there a way to limit it? Like [0.8, 0.9] or something like that?

And also, I wonder why there are only a few (around a dozen or so) parameters mentioned in the tuning section? What about the rest? There are a lot of others in the parameters section, aren't they?

Thank you very much! I hope someone can share your experience!

Happy Coding!
Thuan

**Comment by StrikerRUS** [comment]
@duckladydinh Hi!
It is very task- and dataset-dependent. There is no silver bullet.
For example, you can read this comment for unbalanced datasets: https://github.com/microsoft/LightGBM/issues/695#issuecomment-315591634.
In addition, you may want to get familiar with this awesome site: https://sites.google.com/view/lauraepp/parameters.
Also, XGBoost recently had a suggestion to revisit their default param values: https://github.com/dmlc/xgboost/issues/4986

I remember we had an internal conversation about the need to change default params in order to respect small datasets. At least, we might enhance the current guide with suggested ranges for different types of datasets.

**Comment by StrikerRUS** [comment]
Closed in favor of being in #2302. We decided to keep all feature requests in one place.

Welcome to contribute this feature! Please re-open this issue (or post a comment if you are not a topic starter) if you are actively working on implementing this feature.
