### ISSUE TITLE
LightGBM error when running on Mac with mmlspark 0.18.1

### ISSUE THREAD

**Issue by JoanFM** [microsoft/LightGBM#2632]
When trying to use RankLib through mmlspark we observe following behaviour in Mac

[LightGBM] [Warning] Connecting to rank 1 failed, waiting for 10000 milliseconds
[LightGBM] [Warning] Connecting to rank 1 failed, waiting for 10000 milliseconds
[LightGBM] [Fatal] Socket send error, code: 32
libc++abi.dylib: terminating

Issue related to https://github.com/Azure/mmlspark/issues/512. Same behaviour experienced.

To reproduce issue you can clone this repo: https://github.com/JoanFM/lightGBM-mac-error and run ./gradlew test to see the issue.

## Environment info

Operating System: MacOS

CPU/GPU model:

C++/Python/R version:C++ corresponding to mmlspark 0.18.1

LightGBM version or commit hash:

## Reproducible examples
[LightGBM] [Warning] Connecting to rank 1 failed, waiting for 10000 milliseconds
[LightGBM] [Warning] Connecting to rank 1 failed, waiting for 10000 milliseconds
[LightGBM] [Fatal] Socket send error, code: 32
libc++abi.dylib: terminating

## Steps to reproduce

1. git clone https://github.com/JoanFM/lightGBM-mac-error.git
2.cd lightGBM-mac-error.git
3../gradlew test

**Comment by StrikerRUS** [comment]
Sorry, but we do not maintain MMLSpark library here. According to the error log, it seems that the problem is in establishing connection, which MMLSpark-team may know how to fix.

Please report this problem there.

Feel free to reopen with additional details, if there is any underlying issue inside the LightGBM library itself.
