### ISSUE TITLE
Error: unknow submodel type

### ISSUE THREAD

**Issue by gugatr0n1c** [Microsoft/LightGBM#264]
After upgrade LightGBM to latest version and calling model built with some of previous version I get error below. After downgrade of lib it is working again.

## Environment info
Operating System: LinuxMint
C++/Python/R version: Python3.5

## Error Message:
Traceback (most recent call last):
  File "predict.py", line 22, in <module>
    model = lg.Booster(model_file = workingDir + '/modely/model.txt')
  File "/usr/local/lib/python3.5/dist-packages/lightgbm-0.1-py3.5.egg/lightgbm/basic.py", line 1213, in __init__
    ctypes.byref(self.handle)))
  File "/usr/local/lib/python3.5/dist-packages/lightgbm-0.1-py3.5.egg/lightgbm/basic.py", line 46, in _safe_call
    raise LightGBMError(_LIB.LGBM_GetLastError())
lightgbm.basic.LightGBMError: b'unknow submodel type in model file myPath/modely/model.txt'

**Comment by guolinke** [comment]
@gugatr0n1c you can manually change the first line of your model to "tree" to adapt the latest code.

**Comment by gugatr0n1c** [comment]
ok, thx

**Comment by gugatr0n1c** [comment]
[LightGBM] [Fatal] Model file doesn't contain feature infos
Traceback (most recent call last):
  File "predikuj.py", line 22, in <module>
    model = lg.Booster(model_file = workingDir + '/modely/model_0_' + str(cv) + '.txt')
  File "/usr/local/lib/python3.5/dist-packages/lightgbm-0.1-py3.5.egg/lightgbm/basic.py", line 1218, in __init__
    ctypes.byref(self.handle)))
  File "/usr/local/lib/python3.5/dist-packages/lightgbm-0.1-py3.5.egg/lightgbm/basic.py", line 47, in _safe_call
    raise LightGBMError(_LIB.LGBM_GetLastError())
lightgbm.basic.LightGBMError: b"Model file doesn't contain feature infos"

**Comment by gugatr0n1c** [comment]
I manually changed "gbtd" to "tree", but I got another error

**Comment by gugatr0n1c** [comment]
Can I handle this as well somehow? I have many model built. I cannot regenerate all models with new lib. Thx

**Comment by gugatr0n1c** [comment]
@guolinke thx for help

**Comment by guolinke** [comment]
you can just copy the "feature_names=....." and change its name to "feature_infos" .

**Comment by gugatr0n1c** [comment]
@guolinke there is another error below, I can share model file, not sure If I got it right (55M file)
https://dl.dropboxusercontent.com/u/36271853/model_0_0.txt

error:
[LightGBM] [Fatal] Tree model string format error
Traceback (most recent call last):
  File "predikuj.py", line 22, in <module>
    model = lg.Booster(model_file = workingDir + '/modely/model_0_' + str(cv) + '.txt')
  File "/usr/local/lib/python3.5/dist-packages/lightgbm-0.1-py3.5.egg/lightgbm/basic.py", line 1218, in __init__
    ctypes.byref(self.handle)))
  File "/usr/local/lib/python3.5/dist-packages/lightgbm-0.1-py3.5.egg/lightgbm/basic.py", line 47, in _safe_call
    raise LightGBMError(_LIB.LGBM_GetLastError())
lightgbm.basic.LightGBMError: b'Tree model string format error'

**Comment by guolinke** [comment]
@gugatr0n1c can you try the latest commit?

**Comment by gugatr0n1c** [comment]
@guolinke yep!, working now (still need to rename gbtd->tree and add f_infos, but that is OK), thx!

**Comment by econkc** [comment]
Hi,

I have exact same issue with Python 3.6 (although my model is saved in json). The name of the first line is already "tree" but "feature_names" is still "names" instead of "infos". Tried changed it to infos, also tried switching the name back to "gbdt" but doesn't work. Please help.

> 
LightGBMError                             Traceback (most recent call last)
<ipython-input-19-360d7251075e> in <module>()
      1 # Load saved model
      2 
----> 3 bst = lgb.Booster(model_file='clvpr1.txt')

~/anaconda3/lib/python3.6/site-packages/lightgbm/basic.py in __init__(self, params, train_set, model_file, silent)
   1296                 c_str(model_file),
   1297                 ctypes.byref(out_num_iterations),
-> 1298                 ctypes.byref(self.handle)))
   1299             out_num_class = ctypes.c_int(0)
   1300             _safe_call(_LIB.LGBM_BoosterGetNumClasses(

~/anaconda3/lib/python3.6/site-packages/lightgbm/basic.py in _safe_call(ret)
     46     """
     47     if ret != 0:
---> 48         raise LightGBMError(_LIB.LGBM_GetLastError())
     49 
     50 

LightGBMError: b'unknown submodel type in model file clvpr1.txt'
