### ISSUE TITLE
max_position ignored in ranking with "lambdarank"

### ISSUE THREAD

**Issue by mavillan** [microsoft/LightGBM#2746]
## Environment info

Operating System: OSX 10.15.2

CPU/GPU model: Intel(R) Core(TM) i5-5350U CPU @ 1.80GHz

C++/Python/R version: Clang 4.0.1 / Python 3.7.6

LightGBM version or commit hash: 2.3.1

## Error message

The parameter `max_position` which the docs says determines the position at which NDGC is optimized, seems to not take effect in the learning of the algorithm. 

## Reproducible examples

I noticed this problem working on a real ranking problem, but I provide a toy example to show you the problem:

```python
import numpy as np
import lightgbm as lgb
from sklearn.model_selection import train_test_split

np.random.seed(2)
X = np.random.random((1000,2))
y = np.random.randint(5, size=(1000,))

# all samples belong to one group
group_train = [X_train.shape[0]]
group_valid = [X_valid.shape[0]]
train_set = lgb.Dataset(data=X_train, label=y_train, group=group_train, free_raw_data=False)
valid_set = lgb.Dataset(data=X_valid, label=y_valid, group=group_valid, free_raw_data=False)

model_params = {"objetive":"lambdarank",
                "metric":"ndcg",
                "eval_at":[100],
                "learning_rate":0.1,
                "num_leaves":16,
                "max_position":500
                }
ranker = lgb.train(model_params,
                   train_set=train_set,
                   valid_sets=[valid_set],
                   num_boost_round=100,
                   early_stopping_rounds=20)
```

varying the value of `max_position` between `1` and `1000` does not produce any change in the early_stopping round nor in the valid_metric, which is always:

`
Early stopping, best iteration is:
[23]	valid_0's ndcg@5: 0.668392
`

When changing `max_position` I expect a change in the learning process and so a change in these two values.

**Comment by guolinke** [comment]
You can check the model file generated by the different `max_position`, I think they are different. 

I guess the reason is, 1) it is hard to learn from random data, and changing max_position only results in slight difference model 2) with the slight difference, the ranking score could be very close. 

The effect of `max_position` actually is very limited. currently, we just use it to truncate the max_ndcg. (refer to "truncation level" in the sec.3 in https://www.microsoft.com/en-us/research/wp-content/uploads/2016/02/MSR-TR-2010-82.pdf)
