### ISSUE TITLE
why we don't consider the max_position when we calculate the delta_pair_NDCG

### ISSUE THREAD

**Issue by shaoguang123** [microsoft/LightGBM#2792]
In the code file[https://github.com/microsoft/LightGBM/blob/master/src/objective/rank_objective.hpp](url), the max_psition only work when we calculate inverse_max_dcg.
why we don't consider the max_position when we calculate the delta_pair_NDCG

**Comment by guolinke** [comment]
refer to https://github.com/microsoft/LightGBM/issues/2746#issuecomment-583211348

We didn't use that since we follow the original paper.
You can try to set `low_discount` and `high_discount` with `std::max(DCGCalculator::GetDiscount(max_position), ...)` 
If this indeed can help the performance, the PR of this change is very welcome

**Comment by shaoguang123** [comment]
> refer to [#2746 (comment)](https://github.com/microsoft/LightGBM/issues/2746#issuecomment-583211348)
> 
> We didn't use that since we follow the original paper.
> You can try to set `low_discount` and `high_discount` with `DCGCalculator::GetDiscount(std::min(max_position, cur_pos))`.
> If this indeed can help the performance, the PR of this change is very welcome

Thank you for your answer which helps me a lot.
