### ISSUE TITLE
[ci] R linter is broken

### ISSUE THREAD

**Issue by StrikerRUS** [microsoft/LightGBM#2986]
We have the following error in `master`:
```
Linting R code
Error: 'absolute_path_linter' is not an exported object from 'namespace:lintr'
Execution halted
```

https://travis-ci.org/github/microsoft/LightGBM/jobs/672985225

**Comment by jameslamb** [comment]
I'm looking into this right now

**Comment by jameslamb** [comment]
This is so weird. I see the first  `conda install` reflected in the logs

![image](https://user-images.githubusercontent.com/7608904/78957019-b1d7e800-7aa9-11ea-921e-6df1c9eaf2b9.png)

but not the second one with `libxml2` and  `r-lintr`

I checked `conda-forge`...the last update to `r-lintr` in that channel was [almost 2 months ago](https://anaconda.org/conda-forge/r-lintr/files). That is v2.0.1.

v2.0.1 is also the latest on CRAN, from February ([link](https://cran.r-project.org/web/packages/lintr/index.html).

`absolute_path_linter()` even got a fix in that release, so it definitely is still in the project: https://github.com/jimhester/lintr/blob/d3c741d68c8c1fabf32e770871dd6f0c07ac53df/NEWS.md#lintr-201

This is extra confusing because the error we're getting means that `lintr` was installed, but just without `absolute_path_linter`. If you try to `::` import something from a package that isn't installed, you'll get a different error

```r
nonsense::ok
#  Error in loadNamespace(name) : there is no package called ‘nonsense’
```

**Comment by jameslamb** [comment]
This error isn't transient though. I see it on the PR I just opened a few moments ago (for a different issue)

https://travis-ci.org/github/microsoft/LightGBM/jobs/673261314

I'm going to open a PR and take the `--quiet` flags off the installs

**Comment by jameslamb** [comment]
deeeep in the extra-extra-verbose logs (`conda install -vvv`) I see this statement about cyclic dependencies in some R packages

![image](https://user-images.githubusercontent.com/7608904/78958664-6542db80-7aae-11ea-8de3-c2a2d6f09ff8.png)

I also noticed that every reference to `r-lintr`  in there that has a channel mentions the main linux channel, not `conda-forge`. So my theory is that `conda` is ignoring what I asked and instead of saying "I can't find a matching version on `conda-forge`" it's saying "the best I can do is this super old one from the main channels". I'll try some things.

**Comment by jameslamb** [comment]
I don't see  `r-lintr` 2.0.1 mentioned a single time in there 0_o

**Comment by jameslamb** [comment]
Wow these logs are NOT encouraging https://travis-ci.com/github/jameslamb/LightGBM/builds/159731103

I see a ton of conflicts. Going to try pegging to 2.0.0

**Comment by jameslamb** [comment]
Given that even 2.0.0 (the previous version) is not working, I think that some other package's recipe(s) are broken and I can't figure out from the logs which ones :/

**Comment by jameslamb** [comment]
ok @StrikerRUS I need to pick this back up tomorrow. Things I tried that did not work:

* `conda install`-ing `lintr==2.0.0` instead of the most recent version
* installing `lintr` from CRAN with `install.packages()` (using `Rscript`  from `conda`)
     - this failed because of other upstream things not available, e.g. `httr` R package is a dependency of `lintr`, it depends on R package `curl`, which depends on `libcurl`...I didn't want to patch all those things because that would be super brittle even if it worked
* forcing installation from `conda-forge` using `conda install --override-channels` and `conda install --strict-channel-priority`

You can see the history  of things I tried and their builds [on my fork](https://github.com/jameslamb/LightGBM/pull/16).

You can see in the logs that something somewhere in `conda-forge` land is broken and causing rippling inconsistencies. Either that or literally the `conda` installer itself is.

I don't even know where the root of the problem is so I can't open an issue somewhere.

I see two options:

1. Stop using R stuff with `conda`. This might mean pulling R environment setup out of 
 `test_r_package.sh` into like a `.ci/setup_r.sh`, then putting R linting in a TASK by itself called `r-lint` which re-uses that setup.
2. Just wait for the issue to resolve itself

If you have other ideas I'm open to them! It would take me maybe 20 minutes to do idea 1, but up to you if it's valuable to keep all linting as one task.

**Comment by StrikerRUS** [comment]
@jameslamb Haven't read all you reports yes, sorry. Will do it in a dew hours.
One question. Is it possible simply drop that linter for now?

**Comment by StrikerRUS** [comment]
@jameslamb You will laugh when see what was the root cause of this issue 😃 .

**Comment by jameslamb** [comment]
![image](https://user-images.githubusercontent.com/7608904/79002330-d8336d00-7b15-11ea-8332-063683f68eda.png)

haha WHAT

![](https://media.giphy.com/media/KymorXwDdmvw4/giphy.gif)
