### ISSUE TITLE
Quantiles Regression become much slower than sklearn .

### ISSUE THREAD

**Issue by eromoe** [microsoft/LightGBM#3034]
## Environment info

Operating System:   Ubuntu 18.04.2 LTS

CPU/GPU model:

> Architecture:        x86_64
> CPU op-mode(s):      32-bit, 64-bit
> Byte Order:          Little Endian
> CPU(s):              32
> On-line CPU(s) list: 0-31
> Thread(s) per core:  2
> Core(s) per socket:  16
> Socket(s):           1
> NUMA node(s):        1
> Vendor ID:           GenuineIntel
> CPU family:          6
> Model:               85
> Model name:          Intel(R) Xeon(R) Silver 4216 CPU @ 2.10GHz
> Stepping:            7
> CPU MHz:             2700.001
> BogoMIPS:            4200.00
> Virtualization:      VT-x
> L1d cache:           32K
> L1i cache:           32K
> L2 cache:            1024K
> L3 cache:            22528K
> NUMA node0 CPU(s):   0-31
> 

C++/Python/R version: python 3.7.6

LightGBM version or commit hash:   2.3.1

## Reproducible examples

There is an issue https://github.com/Microsoft/LightGBM/issues/1182 for quantile regression . At the end , auther said `20x speedup with similar performance over sklearn` . 

Here is a notebook replicated test code  https://github.com/ceshine/quantile-regression-tensorflow/blob/master/notebooks/02-sklearn-example-lightgbm.ipynb

I was using this notebook to do testing , but I found that Lgbm is much more slower than sklearn . 

Sklearn:
![image](https://user-images.githubusercontent.com/3938751/80578726-86f30b00-8a3b-11ea-8416-ea396235ff17.png)

Lgbm: 
![image](https://user-images.githubusercontent.com/3938751/80578758-92463680-8a3b-11ea-89b1-80dcde5f7910.png)

What happen ?

**Comment by Laurae2** [comment]
@eromoe The difference is likely because you are using 32 threads to train on a 100x1 dataset.

In the LightGBM version:

* (this should explain all the performance difference alone) Decrease significantly the number of threads: you are using 32 threads to train on a training set of 100 samples of 1 column, 1 thread is likely to be the fastest for such size
* or significantly increase dataset size (to something like 1 million samples instead of 100 samples)

If you increase the dataset size, then in the sklearn version:

* Remove all the validation data
* Increase maximum depth to match LightGBM

**Comment by eromoe** [comment]
You are right, thanks
