### ISSUE TITLE
num_leaves and max_leaves yields different results although states as aliases

### ISSUE THREAD

**Issue by heisenberg72** [microsoft/LightGBM#3115]
The results are different based on selection as you can see here with digits dataset.
I first noticed it with my large dataset, and tried to reproduce it on public available dataset.

![digits](https://user-images.githubusercontent.com/35179399/82766112-807a6800-9e1c-11ea-9ec7-046ad284a3e8.PNG)

**Comment by StrikerRUS** [comment]
In the second case `max_leaves` param is overwritten by `num_leaves` argument from classifier's constructor. You can see it in the logs:
```
[LightGBM] [Warning] num_leaves is set=31, max_leaves=255 will be ignored. Current value: num_leaves=31
```

Please use arguments from constructor if needed params are among them.

**Comment by heisenberg72** [comment]
@StrikerRUS I'm glad you cleared that out for me, but still, why official documentation states one can use both names for the same parameter?

> num_leaves 🔗︎, default = 31, type = int, aliases: num_leaf, max_leaves, max_leaf, constraints: 1 < num_leaves <= 131072

**Comment by StrikerRUS** [comment]
Because they are aliases of the same parameter and you can use **any** of them. But when you specify **multiple** aliases for the same parameter at the same time, only one is applied.

**Comment by heisenberg72** [comment]
@StrikerRUS Where did I specify multiple aliases for the same parameter at the same time?
These two runs are independent.

**Comment by jameslamb** [comment]
hey @heisenberg72 , sorry this might not be obvious.

The information about parameter "aliases" in the documentation is used LightGBM-wide, and doesn't just apply to the scikit-learn interface to the Python API for LightGBM.

The constructor for `LGBMClassifier` is inherited from `LGBMModel`, and that class's explicitly sets `num_leaves=31`: https://github.com/microsoft/LightGBM/blob/796ba8033266931814fe27cdf729fcf0d79fff5d/python-package/lightgbm/sklearn.py#L174

So when you call `LGBMClassifier(max_leaves=255)`, `max_leaves` was considered part of `**kwargs` because it didn't match any of the formal keyword arguments. The behavior for the estimators from LightGBM's scikit-learn API is that formal keyword arguments won't be overridden by passing the same parameter or an alias for it into `**kwargs`.

So that call saw:

* `num_leaves=31` (default in the constructor, which you didn't override)
* `max_leaves=255` (an alias for `num_leaves`)

That is why you got this warning (https://github.com/microsoft/LightGBM/issues/3115#issuecomment-633702690) and the behavior you observed.

You can see all of these formal keyword arguments and their defaults in https://lightgbm.readthedocs.io/en/latest/pythonapi/lightgbm.LGBMClassifier.html#lightgbm.LGBMClassifier, as well as this warning

![image](https://user-images.githubusercontent.com/7608904/82958475-11ffec00-9f7b-11ea-83be-49517cfb18e9.png)

Sorry for the confusion! This is a result of the fact that that `Parameters` section serves all interfaces to `LightGBM` (command-line, R, C++, Java, Python, Python sklearn-compliant, and more). Is there something we could have added to the documentation on https://lightgbm.readthedocs.io/en/latest/pythonapi/lightgbm.LGBMClassifier.html#lightgbm.LGBMClassifier that would have made this behavior clearer?

**Comment by heisenberg72** [comment]
@jameslamb 
Oh, I see now. Thank you very much for your clarification. I wasn't aware that LGBMClassifier works through scikit learn API. Documentation for LGBMClassifier (https://lightgbm.readthedocs.io/en/latest/pythonapi/lightgbm.LGBMClassifier.html) is very clear, although it wasn't clear for me from this page https://lightgbm.readthedocs.io/en/latest/Parameters.html that these parameters are not specific for scikit learn API.
