### ISSUE TITLE
Subsetting Dataset not equivalent to subsetting raw data then creating Dataset

### ISSUE THREAD

**Issue by nontrivial** [microsoft/LightGBM#3362]
Using Dataset.subset() to train on specific rows of your data is not equivalent to creating a new Dataset with only those specific rows (I've included an example below). 

I assume maybe this is the intended behavior? Is it because when you create the Dataset on data some global properties are computed like histogram bin widths and these are copied to the subset Dataset? If that's the case what is the use case for the subset function?

My intended use case is to train many models on different subsets of the data, in a way that data/information from outside of the subset doesn't leak into the subset. Is there a way to do that without creating a completely new Dataset for every subset?

Thanks in advance.

```
import pandas as pd
import numpy as np
import lightgbm as lgb

data = pd.DataFrame(np.random.rand(100, 10))
data.columns = [str(i) for i in range(len(data.columns))]

feature_columns = list(data.columns)[2:]
label = '1'
# Masking specific rows
index = data['0'] < 0.2

# Creating the datasets using the same rows, first by masking the data then with subset()
ld1 = lgb.Dataset(data[index][feature_columns], data[index][label], free_raw_data=False).construct()
ld2 = lgb.Dataset(data[feature_columns], data[label], free_raw_data=False).subset(np.flatnonzero(index)).construct()

# Check that the underlying data is the same
assert not np.any(ld1.get_data() != ld2.get_data())

reg1 = lgb.train({}, ld1)
reg2 = lgb.train({}, ld2)

# Get predictions
data['reg1'] = reg1.predict(data[feature_columns])
data['reg2'] = reg2.predict(data[feature_columns])

# Returns true because of different predictions
np.any(data['reg1'] != data['reg2'])
```

**Comment by btrotta** [comment]
This is the intended behavior. When creating the subset LightGBM uses the same bin thresholds as the original dataset instead of calculating them from scratch. However the histogram (i.e. the number of data points in each bin) is recalculated for the subset.

This functionality is used for cross-validation in `CVBooster` (https://lightgbm.readthedocs.io/en/latest/pythonapi/lightgbm.CVBooster.html)

I think `subset` is suitable for your use case; the only information leakage will be that the bin thresholds are calculated using the full dataset. If you want to avoid even this, you could manually specify the binning thresholds, see https://github.com/microsoft/LightGBM/blob/master/examples/regression/forced_bins.json
