### ISSUE TITLE
In skewed data's cross validation case where y_train has only 1 class, predict_proba returns probabilities for 2 classes

### ISSUE THREAD

**Issue by skasturi** [microsoft/LightGBM#3562]
In highly skewed datasets and CV, there is a possibility for the train split to contain a single class. When this happens, LightGBM is returning 2 probabilities when calling `predict_proba`.

I understand that this is uncommon and the model really isn't learning anything and uninformative; but this seems to break the interface of `predict_proba` to return an array of shape `(n_samples, n_classes)`.

## How you are using LightGBM?

python package
LightGBM component: LGBMClassifier

## Environment info

lightgbm==2.3.0

Operating System: Windows 10

CPU/GPU model:

Python version: Python 3.6.10

## Reproducible example(s)

![image](https://user-images.githubusercontent.com/482709/99128509-d6f08400-25bf-11eb-89dd-c40cd3df710a.png)

## Steps to reproduce

```python
import numpy as np
import lightgbm as lgb
model = lgb.LGBMClassifier()
X = np.random.rand(100, 200)
y = np.array([1] * 100)
model.fit(X, y)
assert model.predict_proba(X).shape == (100, 1)
```

**Comment by jameslamb** [comment]
Hi @skasturi . Thanks for using `LightGBM`, and for taking the time to write up this reproducible example!

This is intentional behavior. `LightGBMClassifier` assumes binary classification if you do not pass an objective (https://github.com/microsoft/LightGBM/blob/c20cce0474ceba0a3239e09782f50aed1050bc38/python-package/lightgbm/sklearn.py#L478-L479). Like you mentioned, training a model on a target that is all the same value shouldn't be expected to produce anything useful.

So while you might think of training on this `y` as training a "one-class" model, it's more accurate to say you've trained a binary classification (2 classes) on a dataset that only has samples from one class.

I'm going to close this, but please do let me know if I've misunderstood or you feel strongly that something about LightGBM's behavior should change here.
