### ISSUE TITLE
Confusion: What is the exact meaning of "lightgbm" in "parallel learning" example? 

### ISSUE THREAD

**Issue by Dinxin** [microsoft/LightGBM#3599]
The folder did not contain the file named "lightgbm". I would like to run the code in python.

**Comment by guolinke** [comment]
did you mean `./lightgbm`? it is the execute file in Linux. 
The example for CLI version. For python with parallel learning, you can refer to dask-lightgbm.

**Comment by jameslamb** [comment]
Hi @Dinxin 

`lightgbm` in the examples in https://lightgbm.readthedocs.io/en/latest/Parallel-Learning-Guide.html refers to the LightGBM CLI.

Are you looking at that guide because you need to do distributed (multi-machine) training? If you want to do multi-machine LightGBM training, you can try [`dask-lightgbm`](https://github.com/dask/dask-lightgbm).

Also keep an eye on #3515 and https://github.com/dask/community/issues/104. We'll have better support and documentation for LightGBM + Dask in the near future.
