### ISSUE TITLE
Wrong shape of predictions

### ISSUE THREAD

**Issue by pseudotensor** [microsoft/LightGBM#3636]
Lightgbm 2.2.3 -> 3.1.1

Long term bug.

```
import lightgbm as lgb
import pickle
model, Xslice, kwargs_predict = pickle.load(open("tmp/h2oai/newlgbm.pkl", "rb"))
preds = model.predict_proba(Xslice, **kwargs_predict)
print("version: %s" % lgb.__version__)
assert preds.shape[0] == Xslice.shape[0], "%s %s" % (preds.shape[0], Xslice.shape[0])
```

[newlgbm.pkl.zip](https://github.com/microsoft/LightGBM/files/5664010/newlgbm.pkl.zip)

gives

```
version: 3.1.1
Traceback (most recent call last):
  File "lgbm_shapeissue.py", line 7, in <module>
    assert preds.shape[0] == Xslice.shape[0], "%s %s" % (preds.shape[0], Xslice.shape[0])
AssertionError: 4 163
```

Basically, if one has objective multiclass but have only 2 label types, then lgbm messes up and gives totally wrong results (wrong shape and preds nan).  Here preds.shape[1] is 326, which is wild, just normal predictions not pred_contribs etc.

**Comment by guolinke** [comment]
@pseudotensor can this be reproduced from scratch, without pickle?

**Comment by pseudotensor** [comment]
The pickle is pretty trivial file of model and data.  I'm sure it can be reproduced from scratch, but is it not enough?

**Comment by guolinke** [comment]
@pseudotensor I think the training (how to get the model) is the root cause for this issue, not in the prediction stage. 
So it would be better to have an end-to-end example.

**Comment by pseudotensor** [comment]
I don't have easy way to get full training case.  But as I mentioned, the model was set to multiclass objective but training data target only had 2 label types.

**Comment by guolinke** [comment]
As you use `predict_proba`, which is from sklearn interface, not LightGBM native python interface. So I assume you use the `LGBMClassifier` to perform training.
however, In `LGBMClassifier`, we will first check the label, if it only has 2 label types, it will use binary loss. 

https://github.com/microsoft/LightGBM/blob/44a6fb7ffa646b469fc10475b3526c61239682ac/python-package/lightgbm/sklearn.py#L808-L812

So I am not sure how you perform the multi-class training, with the 2 label types. If you use the native LightGBM interface, you cannot use `predict_proba`.

**Comment by rabyj** [comment]
This is still a problem in `v3.3.2` when using the sklearn interface, in my case it was caused by giving parameters that existed in the native interface but not the sklearn one, so I fell into the following ['documented'](https://lightgbm.readthedocs.io/en/latest/pythonapi/lightgbm.LGBMClassifier.html#lightgbm.LGBMClassifier) case: ****kwargs is not supported in sklearn, it may cause unexpected issues.**

I had saved all parameters automatically to a json when tuning with [Optuna](https://github.com/optuna/optuna), that's how I ended up with incompatible parameters.

I filtered my parameters using the allowed input params, and then the problem went away :)
```python
from inspect import signature
lgbm_allowed_params = set(signature(LGBMClassifier.__init__).parameters.keys())
```

**Comment by rabyj** [comment]
@jameslamb 

I really think it's linked! If one has objective multiclass but have only 2 label types, it's still possible to perform multi-class training using an `LGBMClassifier`, contrary to what @guolinke said. One only has to specify multiclass metrics with a `metric` parameter. Maybe it's what happened with the OP. The thing is, the init of `LGBMClassifier` has no `metric` parameter, so it's an unsupported case. (`**kwargs is not supported in sklearn, it may cause unexpected issues.`). 

In my case, I used a `metric` parameter because it is supported by the Optuna integration `optuna.integration.lightgbm.LightGBMTuner`. I directly saved the best params from that tuner, so when I reloaded them for a new training, the parameter was still there and caused problem. My filtering mentionned above removed it, and the correct default metric was then used.

Here is the minimal code example. I use the IRIS dataset and remove the last class to create my own 2-class dataset. The output shape with the multiclass metrics is wrong, but otherwise it works fine.

```python
import numpy as np
from lightgbm import LGBMClassifier
from sklearn.datasets import load_iris
from sklearn.model_selection import StratifiedKFold

params = {
    "objective": "multiclass",
    "num_class": 2,
    "metric": ["multi_logloss", "multi_error"],
    "n_estimators": 1,
    "verbose": 0,
}

X, y = load_iris(return_X_y=True)
X, y = zip(
    *[[feat, targ] for feat, targ in zip(X, y) if targ != 2]
)  # remove third class
X = np.array(X)
y = np.array(y)

skf = StratifiedKFold(n_splits=3, shuffle=False)
splits = skf.split(np.zeros(X.shape), y)
train_idx_1, valid_idx_1 = next(splits)

X_train = X[train_idx_1]
y_train = y[train_idx_1]

X_valid = X[valid_idx_1]
y_valid = y[valid_idx_1]

print(X_train.shape, y_train.shape, X_valid.shape, y_valid.shape)

estimator = LGBMClassifier()
estimator.set_params(**params)
estimator.fit(X_train, y_train)
preds = estimator.predict_proba(X_valid)
print(preds.shape)

new_estimator = LGBMClassifier()
new_estimator.set_params(**{})
new_estimator.fit(X_train, y_train)
preds = new_estimator.predict_proba(X_valid)
print(preds.shape)
```

I didn't work out the exact math, but in the wrong case, the classifier seems to reshape X_valid in such a way that 
`Product of input shape (n samples * m features) = Product of output shape (n' * m')`.  So there's a link somewhere there. Perhaps.

Output is clarified here
```text
X_train.shape, y_train.shape
(66, 4) (66,) 

X_valid.shape, y_valid.shape
(34, 4) (34,)

predict_proba outputs (on validation set)
Shape 1 (multiclass metrics)
(2, 68)

Shape 2 (default metric)
(34, 2)
````

**Comment by jameslamb** [comment]
@jmoralez whenever you have time, could you look into the example @rabyj provided and offer an opinion here?

**Comment by jmoralez** [comment]
Indeed it doesn't work as expected when `objective='multiclass'` and `num_classes=2` because here: https://github.com/microsoft/LightGBM/blob/61e464bc02bd325672ce71daabfa57d569cf02bc/python-package/lightgbm/sklearn.py#L1148-L1151 it's assumed that `self._n_classes==2` is equal to having a binary objective i.e. something that returns only the predictions for the positive class, which isn't true in this case.

We could fix that by having a more reliable way to check the case where the booster returns only the positive class probabilities, maybe something like this:
```python
if result.ndim == 1 and not (raw_score or pred_leaf or pred_contrib):
    return np.vstack((1. - result, result)).transpose()
else:
    return result
```
