### ISSUE TITLE
Can't suppress "UserWarning: Found `num_iterations` in params. Will use it instead of argument"

### ISSUE THREAD

**Issue by sergeyf** [microsoft/LightGBM#3676]
I'm getting that error quite a bit, and doing the standard 

```
import warnings

warnings.filterwarnings("ignore")
```

I'm using the Python sklearn api and verbose is set to -1. 

Any ideas?

PS, thanks for this majestic package. I use it all the time and it works extremely well. The Semantic Scholar search engine now has a LightGBM reranker.

**Comment by StrikerRUS** [comment]
Hello @sergeyf !
Thanks a lot for the kind words!

Unfortunately, I can't reproduce the warnings with `3.1.1` version.
Could you please share a larger piece of related code?

```
import lightgbm as lgb
from sklearn.datasets import load_boston

X, y = load_boston(return_X_y=True)

est = lgb.LGBMRegressor(verbose=-1, num_rounds=4).fit(X, y)
est.get_params()
```
![image](https://user-images.githubusercontent.com/25141164/103142612-ef9f9e00-4716-11eb-8070-ac653098a49b.png)


Adding `warnings.filterwarnings("ignore")` helps to suppress ```UserWarning: Found `num_iterations` in params. Will use it instead of argument```.

![image](https://user-images.githubusercontent.com/25141164/103142623-152ca780-4717-11eb-9e5f-1ef5d0340a15.png)


BTW, do you have a possibility to fix the **cause** of the warning instead of suppressing it? In case you use sklearn wrapper, this should be easy by simply changing a current alias of boosting trees number to `n_estimators`.

**Comment by sergeyf** [comment]
Thanks @StrikerRUS! Changing it to `n_estimators` helped. It would be helpful to have that contained in the error message.

**Comment by StrikerRUS** [comment]
I'm afraid that it will be more confusing. The thing is that the same argument has different names in our standard API and in sklearn wrapper. And there is no way to know which one is used.
https://github.com/microsoft/LightGBM/blob/44a6fb7ffa646b469fc10475b3526c61239682ac/python-package/lightgbm/engine.py#L145-L148

https://github.com/microsoft/LightGBM/blob/44a6fb7ffa646b469fc10475b3526c61239682ac/python-package/lightgbm/engine.py#L30-L31

https://github.com/microsoft/LightGBM/blob/44a6fb7ffa646b469fc10475b3526c61239682ac/python-package/lightgbm/sklearn.py#L200-L201

**Comment by sergeyf** [comment]
Ah that makes sense.

**Comment by RodrigoAbrao** [comment]
Any update coming soon?

**Comment by StrikerRUS** [comment]
@RodrigoAbrao 

> Any update coming soon?

Update should be done on your side (in your code use argument of a function but not an alias of parameter in params/kwargs).

**Comment by mlindsk** [comment]
Well, I still recieve this warning though I'm not using an alias:

```
UserWarning: Found `num_iterations` in params. Will use it instead of argument
  _log_warning(f"Found `{alias}` in params. Will use it instead of argument")
```

Any suggestions here?

**Comment by StrikerRUS** [comment]
Hey @mlindsk !

> Any suggestions here?

Unfortunately, without a reproducible example we are not able to provide any suggestions.

**Comment by mlindsk** [comment]
I found a solution. If I remove the `num_iteration` from the parameter dict, and directly use `num_boost_round` in `lightgbm.train` it don't complain.
