### ISSUE TITLE
MAPE objective loss predictions having fixed ceiling?

### ISSUE THREAD

**Issue by ivangvi** [microsoft/LightGBM#3734]
LightGBM 3.0.0
Python 3.8.3

Hi! I'm working on a forecasting project with a highly skewed target, representing sales:

![newplot (7)](https://user-images.githubusercontent.com/30244899/103796421-ed4a1780-5025-11eb-9344-183878e1d66b.png)

Since business side is interested in MAPE, I'm setting that as stop **metric** for training validation. Trying several **objectives**, I wasn't surprised when MAPE came out as the top performer. MAPE loss yielded around 0.6 MAPE, while Tweedie loss was at 0.8 MAPE. Nevertheless, when taking a closer look at the predictions, MAPE completely ignores any high value targets, assigning them all around a fixed ceiling:

<img width="610" alt="Untitled" src="https://user-images.githubusercontent.com/30244899/103806371-acf19600-5033-11eb-91f4-54e992a77d90.png">

It appears like MAPE loss is working relatively much better for the bulk low value targets than Tweedie loss, because it can afford the luxury of completely ignoring high value targets and getting better MAPE anyway. I believe I have read somewhere this a problem that can arise with MAPE loss and skewed target distributions. Actually, I encountered the exact same issue some months ago while trying MAPE loss for another sales forecasting project, but since the performance metric wasn't MAPE I didn't look into it.

Is this expected, unchangeable behavior? 
If it is, do you have any suggestions to improve my results?

Thanks a lot.

PS. feel free to comment on using another metric instead of MAPE, I'm working with business side on that as well.

**Comment by guolinke** [comment]
I think it is expected. 
For mape objective, there is a "post-fix" for the output values, to avoid being skewing by too large (or too small) prediction values.
refer to code:
https://github.com/microsoft/LightGBM/blob/31bc196aba4841efbeaccae72bcbae997e7228de/src/objective/regression_objective.hpp#L640-L658

As you can see in the above code, when using mape objective, the prediction value will be the median of label values (rather than the mean values used in l2 objective).  
Similar trick is used in L1 and quantile objective loss.
