### ISSUE TITLE
Release v3.1.1 for java

### ISSUE THREAD

**Issue by zhumengzhu** [microsoft/LightGBM#3791]
## Summary
Generate SWIG Java wrappers for the latest version 3.1.1 and deploy the jar file into the maven central.

## Motivation
The LightGBM has already support Java via swig, but the latest java release is still 2.3.180:
https://repo.maven.apache.org/maven2/com/microsoft/ml/lightgbm/lightgbmlib/

Sine the 2.3.1 version was first released on Nov 28, 2019, there are a lot updates includes many performance improvement. 

Although I can build it for myself base on this [comment](https://github.com/microsoft/LightGBM/issues/909#issuecomment-364453517), it will be very nice if there is an official release because all java developers will benefit from it.

## References
https://github.com/microsoft/LightGBM/releases
https://github.com/microsoft/LightGBM/issues/909
https://github.com/microsoft/LightGBM/pull/3727
https://repo.maven.apache.org/maven2/com/microsoft/ml/lightgbm/lightgbmlib/

**Comment by StrikerRUS** [comment]
@zhumengzhu Hi! Thanks for pointing to this issue.

For the first part of the issue, namely 
> Generate SWIG Java wrappers for the latest version 3.1.1

we already have SWIG JAVA wrappers uploaded to LightGBM Release page at GitHub. You can find them [here](https://github.com/microsoft/LightGBM/releases/tag/v3.1.1) (`lightgbmlib_linux.jar`, `lightgbmlib_macos.jar`, `lightgbmlib_win.jar`).

For the second part
> and deploy the jar file into the maven central.

I'd like to ask you to post this issue in the [`mmlspark` GitHub repository](https://github.com/Azure/mmlspark) because they own that Maven central. Unfortunately, we cannot help with this.

cc @imatiach-msft
