### ISSUE TITLE
[dask] support init_score

### ISSUE THREAD

**Issue by jameslamb** [microsoft/LightGBM#3807]
## Summary

LightGBM allows you to provide initial scores to boost from (https://lightgbm.readthedocs.io/en/latest/pythonapi/lightgbm.Dataset.html?highlight=init_score#lightgbm.Dataset.set_init_score).

This option should be supported in the Dask interface. Dask model classes should accept a dask array, dask dataframe, or Dask dataframe series as input for `init_score`.

## Motivation

This change would bring the Dask interface closer to full feature parity with the non-Dask interface, so that users who'd otherwise like to use Dask don't have to avoid it because `init_score` is missing.

## References

Created from this conversation: https://github.com/microsoft/LightGBM/pull/3708#discussion_r562024425

**Comment by jameslamb** [comment]
Closing this in favor of being in #2302 with other feature requests. Anyone is welcome to contribute this feature. Leave a comment below and it can be re-opened.

**Comment by jmoralez** [comment]
I see this is a method of `lgb.Dataset`, should I attempt to make a Dask equivalent? I guess this will have to be done eventually to avoid having lots of parts all over the place.

**Comment by jameslamb** [comment]
Since you're working on this, I'll open the issue back up. Thanks for looking into it!

> I see this is a method of lgb.Dataset, should I attempt to make a Dask equivalent

I'm not sure what you mean by "method of Dataset", sorry. For a training dataset of shape `[n, k]`, `init_score` is an array of shape `[n]` with initial scores for each sample.

https://github.com/microsoft/LightGBM/blob/84c4b7504a49eed63fa819a92db7d0b18292f3f4/python-package/lightgbm/sklearn.py#L194

Since the Dask interface only supports LightGBM's scikit-learn interface today, you don't need to do anything with the `Dataset` object to add this feature. I think it'll work to handle `init_score` exactly the way we handle `sample_weight`: https://github.com/microsoft/LightGBM/blob/84c4b7504a49eed63fa819a92db7d0b18292f3f4/python-package/lightgbm/dask.py#L293-L296

* it should be passed to `.fit()` as a Dask Array, Dask DataFrame, or Dask series
* it should have the same partitioning as `X` and `y`
* pass it around in `parts` just like we currently do with `sample_weight`

**Comment by jmoralez** [comment]
Oh I meant the link in the summary points to `lgb.Dataset.set_init_score`. Ok, will try your proposed approach.

**Comment by jmoralez** [comment]
I believe `init_score` is deprecated in the scikit-learn interface. I'm getting
```
/home/josemz/programs/anaconda3/envs/lightgbm/lib/python3.7/site-packages/lightgbm/basic.py:1224: UserWarning: init_score keyword has been found in `params` and will be ignored.
Please use init_score argument of the Dataset constructor to pass this parameter.
```

**Comment by jameslamb** [comment]
It is not deprecated. `init_score` should be passed to `fit()`, not the estimator's constructor: https://github.com/microsoft/LightGBM/blob/master/python-package/lightgbm/sklearn.py#L543

If you get that same warning even when doing that, please ignore it.

**Comment by jameslamb** [comment]
fixed by #3950

**Comment by jmoralez** [comment]
Hi @jameslamb. I'm including the multiclass-classification task and the test for init_score fails because you have to specify an init_score for each class. However, you can't send an `(n_samples, n_classes)` array like it is suggested [here](https://github.com/microsoft/LightGBM/issues/2595#issuecomment-558561739) because the init_score is expected to be a 1d collection, so you have to reshape that to an `(n_samples * n_classes, )` collection, which for the dask case will be hard because of the partitioning. 

So I see two ways of fixing this:
1. Handling this reshaping inside the [_train_part](https://github.com/microsoft/LightGBM/blob/37e987828d3141aded1a6e356fdcc7954a6f2f5c/python-package/lightgbm/dask.py#L108) function and sending an `(n_samples, n_classes)` collection as `init_score` to the fit method of the dask models (which creates an inconsistency between the interfaces).
2. Allow for `init_score` to be of shape `(n_samples, n_classes)` everywhere in LightGBM, which currently fails [here](https://github.com/microsoft/LightGBM/blob/37e987828d3141aded1a6e356fdcc7954a6f2f5c/python-package/lightgbm/basic.py#L1843). This seems to be more intuitive but is also very invasive since it involves modifying the `basic` module.

What do you think?

**Comment by jameslamb** [comment]
> Hi @jameslamb. I'm including the multiclass-classification task and the test for init_score fails because you have to specify an init_score for each class. However, you can't send an `(n_samples, n_classes)` array like it is suggested [here](https://github.com/microsoft/LightGBM/issues/2595#issuecomment-558561739) because the init_score is expected to be a 1d collection, so you have to reshape that to an `(n_samples * n_classes, )` collection, which for the dask case will be hard because of the partitioning.
> 
> So I see two ways of fixing this:
> 
> 1. Handling this reshaping inside the [_train_part](https://github.com/microsoft/LightGBM/blob/37e987828d3141aded1a6e356fdcc7954a6f2f5c/python-package/lightgbm/dask.py#L108) function and sending an `(n_samples, n_classes)` collection as `init_score` to the fit method of the dask models (which creates an inconsistency between the interfaces).
> 2. Allow for `init_score` to be of shape `(n_samples, n_classes)` everywhere in LightGBM, which currently fails [here](https://github.com/microsoft/LightGBM/blob/37e987828d3141aded1a6e356fdcc7954a6f2f5c/python-package/lightgbm/basic.py#L1843). This seems to be more intuitive but is also very invasive since it involves modifying the `basic` module.
> 
> What do you think?

Please open a new issue describing the problem, with a reproducible example of what happens when you pass an `init_score` of shape `(n_samples, n_classes)`, including the specific error message.
