### ISSUE TITLE
Make some functions from Dask module class methods

### ISSUE THREAD

**Issue by StrikerRUS** [microsoft/LightGBM#3832]
It will be good to have `_train()` and `_predict()` functions (at least them, very possibly some other functions can be made methods) in a form of `_LGBMModel`'s methods. It will improve encapsulation in Dask module.

https://github.com/microsoft/LightGBM/blob/ac706e10e461d1c5987a3975cc48aa82fde33566/python-package/lightgbm/dask.py#L179

https://github.com/microsoft/LightGBM/blob/ac706e10e461d1c5987a3975cc48aa82fde33566/python-package/lightgbm/dask.py#L337

https://github.com/microsoft/LightGBM/pull/3515#discussion_r541799922

**Comment by ShrillShrestha** [comment]
Hi @StrikerRUS, I am a beginner and learning to contribute in open source. I am not sure if I understand the whole issue, but it seems interesting. If you can guide me, I think I can resolve it.
 
Do I add them inside the _LGBMModel class and change https://github.com/microsoft/LightGBM/blob/b8fc476e9c3a358992c4d45b51522a1ac53ffc91/python-package/lightgbm/dask.py#L395 to `model = self._train(...)`
and return statements like https://github.com/microsoft/LightGBM/blob/b8fc476e9c3a358992c4d45b51522a1ac53ffc91/python-package/lightgbm/dask.py#L443 to `return super()._predict(...)`

**Comment by jameslamb** [comment]
Hi @ShrillShrestha , thanks for the offer!

But @StrikerRUS I disagree with the label "good first issue" on this one. This will involve some design discussions that I think should be done by maintainers. It's not as simple as just moving the code around, because the decision here might be based on a discussion (that we have not had yet) about whether the Dask module should support a non-scikit, functional API similar to https://github.com/microsoft/LightGBM/blob/ac706e10e461d1c5987a3975cc48aa82fde33566/python-package/lightgbm/engine.py#L15. Let's please not have that conversation here by the way.

@ShrillShrestha all that said...we would love you help on one other issues. Could you try https://github.com/microsoft/LightGBM/issues/3833?

**Comment by StrikerRUS** [comment]
@jameslamb 

> the decision here might be based on a discussion (that we have not had yet) about whether the Dask module should support a non-scikit, functional API similar to

Makes sense! I was not aware of plans to support functions from standard API `train` and `cv`.

Feel free to close this issue because I guess code refactoring indeed will be tightened to decisions we will make.

**Comment by jameslamb** [comment]
Thanks! Yes sorry, I have a lot of documentation to catch up on.

Added feature requests for `train()` (#3846) and `cv()` (#3847).

I'll close this issue, thanks.
