### ISSUE TITLE
How to tell if the GPU-version of lightgbm is installed

### ISSUE THREAD

**Issue by George3d6** [microsoft/LightGBM#3939]
Is there any way to tell from within python if lightgbm can use the GPU of the machine it's running on, or at least if the gpu-spport version has been installed by the user?

**Comment by George3d6** [comment]
My current method is:

```
import lightgbm
import numpy as np
def check_gpu_support():
    try:
        data = np.random.rand(50, 2)
        label = np.random.randint(2, size=50)
        train_data = lightgbm.Dataset(data, label=label)
        params = {'num_iterations': 1, 'device': 'gpu'}
        gbm = lightgbm.train(params, train_set=train_data)
        return True
    except Exception as e:
        return False
```

**Comment by George3d6** [comment]
+ using torch to check for cuda in order to save time.

**Comment by jameslamb** [comment]
Hi @George3d6 , good question! Thanks for using LightGBM.

I'm not aware of an "official" way to do this, but if there is one @StrikerRUS would know.

At a minimum, since you're just catching a general `Exception` I think you should at least move more of that code up out of the `try` block. An exception encountered when creating the dataset won't tell you whether or not a GPU-enable version has been built.

```python
import lightgbm
import numpy as np
def check_gpu_support():
    data = np.random.rand(50, 2)
    label = np.random.randint(2, size=50)
    train_data = lightgbm.Dataset(data, label=label)
    params = {'num_iterations': 1, 'device': 'gpu'}
    try:
        gbm = lightgbm.train(params, train_set=train_data)
        return True
    except Exception as e:
        return False
```

If @StrikerRUS confirms that we don't support this in the Python package today, I think it's a useful feature request. I understand why it would be relevant for people who are building other tools / frameworks on top of LightGBM.

Have you seen other libraries that do this well? If you could point us to examples of those interfaces, it would be helpful.

**Comment by StrikerRUS** [comment]
@George3d6 
> Is there any way to tell from within python if lightgbm can use the GPU of the machine it's running on, or at least if the gpu-spport version has been installed by the user?
> My current method is:

Your method is correct. But you can improve it by checking exact wording in error. With `'device': 'gpu'` param and LightGBM version compiled **without** GPU support you will get `LightGBMError`
https://github.com/microsoft/LightGBM/blob/84c4b7504a49eed63fa819a92db7d0b18292f3f4/python-package/lightgbm/basic.py#L245-L248
with the following message
https://github.com/microsoft/LightGBM/blob/84c4b7504a49eed63fa819a92db7d0b18292f3f4/src/treelearner/gpu_tree_learner.h#L278-L279
