### ISSUE TITLE
Correct grid search values for Hyper-parameter tuning [regression model ]

### ISSUE THREAD

**Issue by ninenerd** [microsoft/LightGBM#3953]
So i am using LightGBM for regression model. 
**500k records , after pre-processing it has 30 columns.** 
_Now for HPT i'm using below grid search params,_ 

```
lgbm_param_dict ={'n_estimators': sp_randint(50, 500),
    'num_leaves': sp_randint(6, 50), 
                  'max_depth': [x for x in range(15, 100)],
             'min_child_samples': sp_randint(100, 500), 
             'min_child_weight': [1e-5, 1e-3, 1e-2, 1e-1, 1, 1e1, 1e2, 1e3, 1e4],
             'subsample': sp_uniform(loc=0.2, scale=0.8), 
             'colsample_bytree': sp_uniform(loc=0.4, scale=0.6),
             'reg_alpha': [0, 1e-1, 1, 2, 5, 7, 10, 50, 100],
             'reg_lambda': [0, 1e-1, 1, 5, 10, 20, 50, 100]}
```

I want to make sure the parameter values are enough to make most of the grid search. 
_Is number of estimators enough, max depth ?_  
**Any suggestions or changes that you would recommend ?**

**Comment by jameslamb** [comment]
Thanks for using LightGBM!

Specifics will depend on your dataset and problem, but I can offer some general comments.

You can see https://lightgbm.readthedocs.io/en/latest/Parameters-Tuning.html for more tips on tuning parameters, and https://lightgbm.readthedocs.io/en/latest/Parameters.html for a full list of parameters.

I think some parts of your grid could be eliminated, because they're impossible. Setting `num_leaves = 6` and `max_depth = 15`, for example. LightGBM will always hit the `num_leaves` limit of 6  before getting close to a 15-split-deep tree. See https://lightgbm.readthedocs.io/en/latest/Parameters-Tuning.html#tune-parameters-for-the-leaf-wise-best-first-tree for some additional information on tuning those two parameters specifically.

I also recommend having 1.0 be the top of your `colsample_bytree` and `subsample` ranges. For the parts of the grid with a small `n_estimators`, you might get better performance by using all of the training data and features at each iteration.

**Comment by StrikerRUS** [comment]
We already have similar feature request for enhancing parameter tuning guide with useful examples for various use cases.
You can subscribe to it #2617 and follow further updates.
