### ISSUE TITLE
Question: How does LightGBM convert feature_fraction to an integer value?

### ISSUE THREAD

**Issue by Alireza-Amani** [microsoft/LightGBM#3991]
Does it use floor or ceiling function?

if I have three features, what does feature_fraction = 0.5 mean? Each decision tree uses how many features at each split? 1 or 2?

(Im using the Python API)

I could not find my answer by reading the documentation, and a skim through source codes. Of course, I may have missed it.

**Comment by jameslamb** [comment]
Thanks for using LightGBM!

For 3 features and `feature_fraction = 0.5`, I believe 2 features will be used.

You can follow the links below in order to see how this is done in LightGBM's source code. If you're interested about other details of column sampling, see https://github.com/microsoft/LightGBM/blob/master/src/treelearner/col_sampler.hpp.

https://github.com/microsoft/LightGBM/blob/d6ebd063fff7ff9ed557c3f2bcacc8f9456583e6/src/treelearner/col_sampler.hpp#L142-L143

https://github.com/microsoft/LightGBM/blob/d6ebd063fff7ff9ed557c3f2bcacc8f9456583e6/src/treelearner/col_sampler.hpp#L128

https://github.com/microsoft/LightGBM/blob/d6ebd063fff7ff9ed557c3f2bcacc8f9456583e6/src/treelearner/col_sampler.hpp#L33-L37

https://github.com/microsoft/LightGBM/blob/d6ebd063fff7ff9ed557c3f2bcacc8f9456583e6/include/LightGBM/utils/common.h#L862-L864

<hr>

Are you interested in submitting a pull request to add a note about that behavior in LightGBM's parameter documentation (https://lightgbm.readthedocs.io/en/latest/Parameters.html#feature_fraction)? 

The process would be updating https://github.com/microsoft/LightGBM/blob/d6ebd063fff7ff9ed557c3f2bcacc8f9456583e6/include/LightGBM/config.h#L329-L335, then running `python helpers/parameter_generator.py` from the root of the repo. You can see https://github.com/microsoft/LightGBM/blob/d6ebd063fff7ff9ed557c3f2bcacc8f9456583e6/include/LightGBM/config.h#L106 for the formatting we use for NOTE entries in the parameter documentation.

**Comment by Alireza-Amani** [comment]
Thank you for your help. 

So the `RoundInt` function that is defined here is another way of using `floor(feature_fraction + 0.5)`.  

(I would love to be useful and add a note but I have zero experience really, not confident) 

Thanks again for the prompt and detailed help and answer.

**Comment by jameslamb** [comment]
Yep that's correct! I encourage you to try the pull request if you're interested. We can answer your questions and help with the process.
