### ISSUE TITLE
Does monotone_constraints work when boosting_type = 'rf'?

### ISSUE THREAD

**Issue by flippercy** [microsoft/LightGBM#4003]
Does monotone_constraints work when boosting_type = 'rf'? 

Thank you.

**Comment by guolinke** [comment]
@CharlesAuguste , can you also help to answer this question?

**Comment by CharlesAuguste** [comment]
Hello @flippercy, as far as I understand, monotone constraints should work for random forests. Monotone constraints should be independent from the boosting type, because the constraints are enforced on the tree level, and when you sum positively weighted monotone trees, you end up end up with a monotone result. If you think you found a case where this is not working, please post an example that can be reproduced, or the set of parameters you are using for your training, so we can investigate. Thanks
