### ISSUE TITLE
[dask] Distributed training sometimes produces very high leaf values

### ISSUE THREAD

**Issue by jose-moralez** [microsoft/LightGBM#4026]
## Description

Hi. I'm trying to use LightGBM in time series forecasting and it works fine with local models. However, when using dask the predictions sometimes are huge (my time series are in the range [0, 160] and the predictions are 10^38). I've included a reproducible example (I'm sorry it's not that minimal but I couldn't reproduce it with some regular datasets). By running the example below sometimes the values are kind of big but other times they just really explode. With bigger datasets I've seen that the first tree is pretty much the same between local and dask but by the second tree the values in dask become increasingly large (so it may have something to do with the gradients). I haven't been able to track down the issue and was hoping someone could point me in the right direction.

## Reproducible example

```python
from itertools import chain
from math import ceil, log10

import dask.dataframe as dd
import lightgbm as lgb
import numpy as np
import pandas as pd
from dask.distributed import Client

def generate_daily_series(n_series: int, 
                          min_length: int = 50, 
                          max_length: int = 500):
    series_lengths = np.random.randint(min_length, max_length+1, n_series)
    total_length = series_lengths.sum()
    n_digits = ceil(log10(n_series))
    
    dates = pd.date_range('2000-01-01', periods=max_length, freq='D').values
    uids = [[f'id_{i:0{n_digits}}'] * serie_length for i, serie_length in enumerate(series_lengths)]
    ds = [dates[-serie_length:] for serie_length in series_lengths]
    y = np.arange(7)[np.arange(total_length) % 7] + np.random.rand(total_length) * 0.5
    series = pd.DataFrame({
        'unique_id': list(chain.from_iterable(uids)),
        'ds': list(chain.from_iterable(ds)),
        'y': y
    })
    series = series.set_index('unique_id')
    return series

def generate_features(df, lags, expanding, rolling,
                      ewm_alpha, date_features):
    df = df.copy()
    for lag in lags:
        df[f'lag_{lag}'] = df.y.shift(lag)
    grouped_lag1 = df.groupby('unique_id')['lag_1']
    for op in expanding:
        df[f'expanding_{op}'] = grouped_lag1.transform(
            lambda y: y.expanding().agg(op)
        )
    for op in rolling:
        df[f'rolling_{op}'] = grouped_lag1.transform(
            lambda y: y.rolling(7).agg(op)
        )
    dates = df.ds.dt
    for feature in date_features:
        df[feature] = getattr(dates, feature)
    df = df.dropna()
    return df

client = Client(n_workers=2, 
                threads_per_worker=2, 
                memory_limit='4 GiB')

# generate data
config = dict(
    lags=[1, 7],
    expanding=['min', 'max', 'mean'],
    rolling=['mean'],
    ewm_alpha=0.1,
    date_features=['dayofweek', 'month', 'year', 'day']  
)
data = generate_daily_series(20, min_length=300, max_length=700)
train = generate_features(data, **config)
X, y = train.drop(columns=['ds', 'y']), train.y

# local regressor
local_reg = lgb.LGBMRegressor().fit(X, y)
local_df = local_reg.booster_.trees_to_dataframe()

# dask regressor
dtrain = dd.from_pandas(train, npartitions=2)
dX, dy = dtrain.drop(columns=['ds', 'y']), dtrain.y
dask_reg = lgb.dask.DaskLGBMRegressor().fit(dX, dy)
dask_df = dask_reg.booster_.trees_to_dataframe()

# Generate plot
ax = dask_df.groupby('tree_index')['value'].mean().plot(label='dask')
local_df.groupby('tree_index')['value'].mean().plot(ax=ax, label='local')
ax.legend();
```

## Environment info

LightGBM version or commit hash: 6356e659af74909aa77eb87d54b79f0373772509

Command(s) you used to install LightGBM

```shell
git clone --recursive https://github.com/microsoft/LightGBM.git
cd LightGBM/python-package
python setup.py install
```

Here are some example plots.
Sometimes the values are just "kind of big".
![image](https://user-images.githubusercontent.com/61287624/109375505-ddf78580-7882-11eb-9f5c-bee9a24a0bab.png)

But other times they just really explode.
![image](https://user-images.githubusercontent.com/61287624/109375522-f9629080-7882-11eb-9893-4c7265de88be.png)

**Comment by jmoralez** [comment]
FWIW this doesn't happen with [dask-lightgbm](https://github.com/dask/dask-lightgbm). I'll try to find where the problem is.

**Comment by jmoralez** [comment]
This actually seems to be related to lightgbm itself. I just pasted the [original dask-lightbm code](https://github.com/dask/dask-lightgbm/blob/main/dask_lightgbm/core.py) in `python-package/lightgbm/dask.py` and found the same issue. The version of lightgbm that I have in my dask-lightgbm environment is `2.3.1`, were there any major changes with respect to distributed training after that? I only found #3110 in the relase notes but I just built from the previous commit before that merge and the issue is there.

**Comment by guolinke** [comment]
How much data (rows) you used? 
If the data is too small, using distributed learning will cause the poor performance, due to the feature bucketing is done by the local data only.

You can try to use construct a dataset on a single node first, via Dataset.construct(), then save it to binary format, Dataset.save_binary(). Then use the binary file for the distributed learning.

**Comment by jmoralez** [comment]
The example I posted generates 20 time series between 300 and 700 rows each, so on average they would be around 10,000 rows. However the issue persists when having more data, I just changed the 20 to 1,000 and trained on 500,000 rows and reproduced the issue. I'm using two machines, I also noticed that when adding more machines the values on the nodes go even higher (even with big datasets).

 I'm trying to track down exactly where this originated because building from 2.3.1 (8364fc3e9a2e3795786561efcedf56a15b028ab9) works fine, however with some of the later changes, (da91c6139c5ae934cb91a7eca6daada3b504d8f2, d0bec9e946de41a5cdfc57128fbd4f948cdea449) I get this error: `lightgbm.basic.LightGBMError: Check failed: best_split_info.left_count > 0` (in case that helps).

**Comment by guolinke** [comment]
@jmoralez I think it is better to fix (use the same) dataset first, constructing it by all rows. 
Then we know which part causes the problem.

**Comment by jmoralez** [comment]
Do you mean using the CLI?

**Comment by guolinke** [comment]
>You can try to construct a dataset on a single node first, via Dataset.construct(), then save it to binary format, Dataset.save_binary(). Then use the binary file for the distributed learning.

These are all python interfaces.

**Comment by jmoralez** [comment]
I've constructed the dataset and saved it to binary format. I'm just confused about 
> Then use the binary file for the distributed learning.

**Comment by guolinke** [comment]
After you save binary file, you can copy it to the nodes for distributed learning.
Then, you can use the binary file path, like use the normal csv file, to construct the dataset for distributed learning.

**Comment by jmoralez** [comment]
Thank you. I just trained using the CLI on my local machine with two "machines" using the binary file and then loaded the booster in python to see the leaf values and they seem normal. Do you have any suggestions for the dask case?

**Comment by guolinke** [comment]
okay, so the problem indeed happens in Dataset construct. 
I am not familiar with dask interface, but I think the python interface lgb.Dataset should support construct by binary file as well. 

To ultimately fix this problem, we should add an "accurate" mode, for feature bucketing. This will significantly slow-down the pre-processing stage before training, due to heavy communications. 

also cc @shiyu1994 to implement "accurate" mode

The algorithm of  "accurate" mode is like:
1. each node sample part of rows
2. use all-gather, to gather the sampled rows from all nodes.
3. each node find bin-mappers for its assigned features like currently do.

**Comment by jmoralez** [comment]
I should point out that this doesn't happen with all datasets, for example, using `sklearn.datasets.load_boston` which just has 500 rows performs well. I actually struggled to produce an example, I'm not sure what's particularly special about these kinds of datasets (time series) that impacts the dataset creation. Like I said it used to work in 2.3.1 but I'm not sure why the changes from then on would have a greater impact here.

**Comment by guolinke** [comment]
@jmoralez 
Can you also try `force_col_wise=true` with dask (without pre-constructed dataset), and see what happen?

**Comment by jmoralez** [comment]
I get high values as well

**Comment by jmoralez** [comment]
I think it has to do with low variance features. In this example I create for example `expanding_min` which has values like 0.1, 0.1, 0.1, 0.1, 0.2, ... so it doesn't vary very much and somehow it breaks the model. However, removing low variance features and training only on lags and rolling mean which have more variance provide good results.

**Comment by guolinke** [comment]
@jmoralez did you shuffle the data by rows?

**Comment by jmoralez** [comment]
I did try it but it doesn't help

**Comment by jose-moralez** [comment]
I extended the table above to include `split_feature` and `threshold` and I realized that in the second tree for the exact same split the distributed version sends 20 samples the wrong way (2331 vs 2351). 

![image](https://user-images.githubusercontent.com/61287624/110699631-aeb31380-81b4-11eb-8c62-de0c183069d8.png)

**Comment by jose-moralez** [comment]
I just realized that even though I shuffle `df`, since dask partitions on the index the data isn't actually shuffled in the dask dataframe (i.e. the first partition has ids 0-9 and the second one 10-19). We have to do `df = df.sample(frac=1).reset_index(drop=True)` and doing this removes the issue. However for my use case I split the data by `id` for preprocessing so shuffling the entire data would be very expensive and if you shuffle the data within each partition the problem persists.

I also found something new, I added the `weight` column and in the second tree they start to differ for the distributed case.
![image](https://user-images.githubusercontent.com/61287624/110875438-3e32f200-829b-11eb-8aa2-6a6847bda7b2.png)

**Comment by jmoralez** [comment]
I just tried using `tree_learner=voting_parallel` and get similar results. I think the problem is in the samples being sent the wrong way, which generates wrong node values and unreal gains. I've looked at the source code but I have no idea where the issue could be.

**Comment by guolinke** [comment]
cc @shiyu1994 for possible bugs.

**Comment by shiyu1994** [comment]
@jameslamb I'm debugging this. Could you tell me how to make dask regressor print the Warning messages from the C++ code? I seems that setting neither `silent=False` nor `verbose=2` works.

**Comment by jameslamb** [comment]
@shiyu1994 sure, I think I can help.

This answer uses a modified version of the code from https://github.com/microsoft/LightGBM/blob/master/examples/python-guide/dask/regression.py (just added `silent=False` and `verbose=2`).

1. start a Python REPL

```shell
python
```

2. Run the following in it

```python
import dask.array as da
from distributed import Client, LocalCluster
from sklearn.datasets import make_regression
import lightgbm as lgb

cluster = LocalCluster(n_workers=2)
client = Client(cluster)
X, y = make_regression(n_samples=1000, n_features=50)
dX = da.from_array(X, chunks=(100, 50))
dy = da.from_array(y, chunks=(100,))
dask_model = lgb.DaskLGBMRegressor(n_estimators=10, silent=False, verbose=2)
dask_model.fit(dX, dy)
```

When I did this, I saw the following printed in my Python console after calling `fit()`

```text
Finding random open ports for workers
[LightGBM] [Warning] num_threads is set=4, n_jobs=-1 will be ignored. Current value: num_threads=4
[LightGBM] [Warning] num_threads is set=4, n_jobs=-1 will be ignored. Current value: num_threads=4
[LightGBM] [Debug] Dataset::GetMultiBinFromAllFeatures: sparse rate 0.000000
[LightGBM] [Debug] init for col-wise cost 0.000004 seconds, init for row-wise cost 0.000503 seconds
[LightGBM] [Warning] Auto-choosing col-wise multi-threading, the overhead of testing was 0.001011 seconds.
You can set `force_col_wise=true` to remove the overhead.
[LightGBM] [Info] Total Bins 12750
[LightGBM] [Info] Number of data points in the train set: 1000, number of used features: 50
[LightGBM] [Info] Start training from score 6.255258
[LightGBM] [Debug] Trained a tree with leaves = 31 and max_depth = 6
[LightGBM] [Debug] Trained a tree with leaves = 31 and max_depth = 7
[LightGBM] [Debug] Trained a tree with leaves = 31 and max_depth = 8
[LightGBM] [Debug] Trained a tree with leaves = 31 and max_depth = 8
[LightGBM] [Debug] Trained a tree with leaves = 31 and max_depth = 7
[LightGBM] [Debug] Trained a tree with leaves = 31 and max_depth = 9
[LightGBM] [Debug] Trained a tree with leaves = 31 and max_depth = 8
[LightGBM] [Debug] Trained a tree with leaves = 31 and max_depth = 9
[LightGBM] [Debug] Trained a tree with leaves = 31 and max_depth = 7
[LightGBM] [Debug] Trained a tree with leaves = 31 and max_depth = 9
DaskLGBMRegressor(n_estimators=10, num_threads=4, silent=False, time_out=120,
                  tree_learner='data', verbose=2)
```

Are there other specific log messages that you think are missing?

## One other thing you can try

You might be able to find more diagnostic information on the Dask dashboard, especially in the "Info" tab that can take you to additional worker logs.

In that same Python REPL, you could get the address for the dashboard by running

```python
print(client.dashboard_link)
```

Paste that into a browser and you'll be able to see the Dask diagnostic dashboard.

![image](https://user-images.githubusercontent.com/7608904/112359121-f189e680-8c9e-11eb-9c4b-7ab6a777442f.png)

But when I did that, I only saw Dask logs and nothing else from LightGBM.

```text
distributed.worker - INFO - Start worker at: tcp://127.0.0.1:33003
distributed.worker - INFO - Listening to: tcp://127.0.0.1:33003
distributed.worker - INFO - dashboard at: 127.0.0.1:34517
distributed.worker - INFO - Waiting to connect to: tcp://127.0.0.1:45311
distributed.worker - INFO - -------------------------------------------------
distributed.worker - INFO - Threads: 4
distributed.worker - INFO - Memory: 16.77 GB
distributed.worker - INFO - Local Directory: /home/jlamb/repos/open-source/LightGBM/dask-worker-space/worker-vlbru721
distributed.worker - INFO - -------------------------------------------------
distributed.worker - INFO - Registered to: tcp://127.0.0.1:45311
distributed.worker - INFO - -------------------------------------------------
```

**Comment by jameslamb** [comment]
ok now I'm weirded out by the changing `max_depth`, looking at that more closely! That seems unexpected, right? I might open a separate issue about it later, don't want to distract too much from this discussion.

```text
[LightGBM] [Debug] Trained a tree with leaves = 31 and max_depth = 6
[LightGBM] [Debug] Trained a tree with leaves = 31 and max_depth = 7
[LightGBM] [Debug] Trained a tree with leaves = 31 and max_depth = 8
[LightGBM] [Debug] Trained a tree with leaves = 31 and max_depth = 8
[LightGBM] [Debug] Trained a tree with leaves = 31 and max_depth = 7
[LightGBM] [Debug] Trained a tree with leaves = 31 and max_depth = 9
[LightGBM] [Debug] Trained a tree with leaves = 31 and max_depth = 8
[LightGBM] [Debug] Trained a tree with leaves = 31 and max_depth = 9
[LightGBM] [Debug] Trained a tree with leaves = 31 and max_depth = 7
[LightGBM] [Debug] Trained a tree with leaves = 31 and max_depth = 9
```

**Comment by shiyu1994** [comment]
@jameslamb Thanks! 

I do find a bug in data parallel training.

When values of the same feature in different machines differ a lot, or even have no overlap, a global optimal split can result in leaves with `0` local data in each machine. For example, in the synthetic example by @jmoralez, the `id` in machine 0 are in `[0, 10]` while machine 1 has `[11, ...]`. Then a split with feature `id` always results in an empty leaf in one of the machine.

Even under such case, we are expected to provide a stable (perhaps not good enough) result. But the problem is, when a leaf has data count `0`, currently we directly skip the histogram construction process, as following.
https://github.com/microsoft/LightGBM/blob/6ad3e6e9e306d3657a0a3d0201862d1f471b2a5e/include/LightGBM/dataset.h#L470-L478
This will not cause any problem in a single machine scenario. However, with data distributed training, we need to send the content in histogram buffer to other machines. With `num_data <= 0`, we exit the `ConstructHistograms` method directly, without clearing the buffer.
https://github.com/microsoft/LightGBM/blob/6ad3e6e9e306d3657a0a3d0201862d1f471b2a5e/src/io/dataset.cpp#L1192-L1193

So, when training a second tree, the empty leaf (though the leaf is actually not empty, considering the global training data) in a local machine will send the histogram content from the first iteration to other machines, which results in an incorrect global histogram.

That's why the problem always occurs from a second iteration.

Let me open a PR to fix this.

**Comment by StrikerRUS** [comment]
@jameslamb 

> ok now I'm weirded out by the changing `max_depth`, looking at that more closely!

I believe this is just a logging bug (bad wording): 
https://github.com/microsoft/LightGBM/blob/fcfd4132e6d40a22d52023396329c41fd3de4a42/src/treelearner/serial_tree_learner.cpp#L207

**Comment by jameslamb** [comment]
oooo ok I'll submit a PR to fix that

**Comment by imatiach-msft** [comment]
@jmoralez are you seeing output like this from lightgbm:

[LightGBM] [Debug] Trained a tree with leaves = 31 and max_depth = 13
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Debug] Trained a tree with leaves = 1 and max_depth = 1
[LightGBM] [Warning] Stopped training because there are no more leaves that meet the split requirements
[LightGBM] [Info] Finished linking network in 11.926274 seconds

I'm seeing this for the regressor, where the last tree seems to output very high values

The image you had above where split gain is NaN seems to resonate with what I am seeing, but it seems unlike mmlspark code dask code continue to call update, it ignores the value it returns:

https://github.com/microsoft/LightGBM/blob/master/python-package/lightgbm/dask.py#L90

I created an issue here:
https://github.com/microsoft/LightGBM/issues/4178
to understand how to deal with this case, when LightGBM outputs "Stopped training because there are no more leaves that meet the split requirements"

**Comment by shiyu1994** [comment]
@imatiach-msft Not sure whether the two are related. Which distributed training strategy are you using?

**Comment by imatiach-msft** [comment]
@shiyu1994 it's using data_parallel training strategy

**Comment by jose-moralez** [comment]
Fixed by #4185

**Comment by jose-moralez** [comment]
Hi @shiyu1994. Is it possible that this could still be present when splitting categorical features? I think I'm experiencing the same issue when I use them.

**Comment by imatiach-msft** [comment]
@jose-moralez are you sure you are using the latest lightgbm on master?  This issue was only recently fixed.  If so, I would suggest creating a new issue.  A similar issue a customer had in mmlspark was resolved with the new change.

**Comment by jose-moralez** [comment]
You're right @imatiach-msft, I had installed from source and checked that the issue was solved but I recently rebuilt my env and installed `3.2.1` again. It was my bad, sorry.

**Comment by imatiach-msft** [comment]
@jose-moralez ah ok, great to hear it's resolved then - if you still see issues though I would either just reopen this one or create a new one, it's difficult to keep track of closed issues (at least for me when I work on other open source projects)
