### ISSUE TITLE
[Question] Using shared memory across boosters

### ISSUE THREAD

**Issue by memeplex** [microsoft/LightGBM#4110]
I need to do predictions from multiple processes (this is the architecture I've to deal with, not the one I designed) and I don't want to load the same boosters (there are hundreds of them) into the memory of each process. Now, one option is to create a prediction service but, if that's possible, I would prefer to share the memory used by the boosters to store tree ensembles, although not necessarily other structures that might not be accessible in a thread-safe manner. Are there any options to specify the memory pool where boosters are stored? Thanks!

**Comment by memeplex** [comment]
A clarification: this is only to do predictions, not training at all, just the model evaluation part.

**Comment by alexisdrakopoulos** [comment]
Along these lines I wanted to ask, but don't believe it constitutes its own ticket, can you share memory of a Dataset across different boosters who are trained with the same inputs but differing labels?

**Comment by shiyu1994** [comment]
@memeplex In C++ interface of LightGBM, we can convert LightGBM models into C++ code with `if-else` statements. After such converting, I think the size of the `if-else` code should be smaller than the original booster ensemble objects in memory. This may not fit your request that different processes share the memory to store the booster, since each process has to load the code independently. However, when your memory to store the boosters is limited, converting to C++ code may be a good solution for lower memory cost.
