### ISSUE TITLE
Exclusive Feature Bundle is for categorical data only?

### ISSUE THREAD

**Issue by aceson28** [microsoft/LightGBM#4114]
@guolinke 
Hi i have some following question for EFB
1. Is EFB only bundling 2 feature? Or it can be greater than that for 1 bundle
2. Is it only for categorical feature? Isn't what is data type if combine between 2 numerical feature or when combining numerical feature with categorical feature?
3.in journal, when we choose what feature to bundle that is a gamma who controlled (in explanation) but in algorithm there are K as max conflict is that same? And in python what his name?
4. In #3010 said the most value will be treated as zero, is there any encode or something? How is that encode work?

**Comment by shiyu1994** [comment]
@aceson28 Thanks for using LightGBM.
1. EFB can bundles multiple features into a single bundle.
2. No, it is for all kinds of features. Note that in LightGBM, numerical features will be discretized into integers (bin IDs of the feature histogram). After discretizing, the representation of numerical and categorical features will both be integers.
In the paper, $K$ is simply $\gamma \times n$. Currently we don't provide $K$ or $\gamma$ as a hyper-parameter. Instead, $K$ is hard-coded as `num_data / 10000` in the code.
https://github.com/microsoft/LightGBM/blob/d517ba12f2e7862ac533908304dddbd770655d2b/src/io/dataset.cpp#L108-L109
3. Strictly speaking, the most frequent value (actually, the most frequent bin value after discretization) is not treated as zero. But it is treated as missing value when constructing histograms (in other words, data with the most frequent bin value will be ignored when constructing histograms, and then recover later.) So that we can save the time for histogram construction, especially when most data has the most frequent bin value.

If you have any further questions, pleas feel free to post them here.

**Comment by skullknight15** [comment]
@shiyu1994 you're saying that features are first transformed into histograms then EFB is applied ? After binning the features usually in the range [0-255], how maximum conflict K is deduced since in the source it is defined as len(real data)/10000 ?

**Comment by jameslamb** [comment]
Reopening this discussion so this comment is more visible.

cc @shiyu1994 @tongwu-msft @hzy46

**Comment by shiyu1994** [comment]
Hi @skullknight15, the features are not transformed into `histograms`, they are transformed into bin numbers of the `histograms`. So I think it makes sense to set the maximum conflict K according to the size of training data.
Please feel free to post any further questions here.

**Comment by skullknight15** [comment]
Thank you @shiyu1994  for your response. It makes more sense to me now.
Is it possible to tell  me  the functions that do feature binning, conflict computation, and feature merging in the provided LightGBM source code.
Thank you in advance for your time

**Comment by shiyu1994** [comment]
Hi @skullknight15,
1. For feature binning, the bin boundaries are found here
https://github.com/microsoft/LightGBM/blob/da98f24711a2faab17f94e5b2a636e6609c93fa6/src/io/bin.cpp#L325-L328
and the discretization is done when a feature value is extracted from the original representation (file, numpy array, ...), into the LightGBM internal representation, see
https://github.com/microsoft/LightGBM/blob/da98f24711a2faab17f94e5b2a636e6609c93fa6/include/LightGBM/feature_group.h#L198-L199
Note that by the time `PushData` is called, we've already done with EFB. So you can see offsets of bin values due to EFB are added in `PushData`.
2. For conflict computation, or feature group finding in EFB, see https://github.com/microsoft/LightGBM/blob/da98f24711a2faab17f94e5b2a636e6609c93fa6/src/io/dataset.cpp#L100
3. For feature merging, it is a nature process after we have define the feature groups, and the merge will be done when 
aforementioned `PushData` method is called.

**Comment by skullknight15** [comment]
@shiyu1994 thank you for your quick response.
I will look at the code and get back to you if I have further questions.

**Comment by skullknight15** [comment]
@shiyu1994  I still have some questions regarding the implementation of merging features in _PushaData_ function.

1- In this function, _sub_feature_idx_ and _line_idx_ are the current feature and sample indexes. What about **value** ?
To which feature it is related? If we are trying to merge f1 and f2 for instance,  _value_ is  associated to f2 or f1?
2- **bin_mappers_** is kind of a multidimensional pointer that allows us to access the specific param related to  feature of index _sub_feature_idx_. Is it possible for you to provide more details about the code from line 201 to 211.
Is it possible for you also to provide more details about function _Push_? I see that there are bit shifts in lines 71,72, and 73 but can't figure out how indexes i1 and i2 are used for feature merging.

I’m sorry for asking so many questions but I am trying to understand and relate to the formalization proposed in the article and to this code snippet:

- feature_bundle12[i] = f2[i]+ max(f1) if F1[i]==most_freq_bin and F2[i] !=most_freq_bin
- feature_bundle12[i] = f1[i] if (F1[i]!=most_freq_bin and F2[i] !=most_freq_bin) or (F1[i]==most_freq_bin and F2[i] ==most_freq_bin) or (F1[i]!=most_freq_bin and F2[i] ==most_freq_bin)
where F1 and F2 are the binned versions of features f1 and f2

Thank you for your response.

**Comment by shiyu1994** [comment]
@skullknight15
1. _sub_feature_idx_ is the feature index WITHIN the group. And **value** is the original feature value. For example, _f1_ and _f2_ can be both in feature group 0, but _f1_ has _sub_feature_idx_ 0 and _f2_ has _sub_feature_idx_ 1. Feature group index and _sub_feature_idx_  together identifies exactly which feature **value** belongs to.
2. **bin_mappers_** stores a BinMapper for each feature in the feature group. A BinMapper of a feature maps the original feature value to its discretized bin value. So together with the explanation in 1, line 201 to 211 maps the original feature value to the discretized bin value. If the bin value is the most frequent bin of that feature, then it is ignore to exploit sparsity.

**Comment by skullknight15** [comment]
@shiyu1994  
So in _PushData_ we only map a feature value to a bin value and then store it in a new table using the function _Push_ . Where does the merging process occurs then? 
Is it possible for you to list the functions that will be called in order to merge the original values of f1 and f2 to form the the merged feature f1-2  and then the binned merged feature F1-2.

**Comment by shiyu1994** [comment]
Hi @skullknight15, sorry for the late response. To be clear, the merging process is decomposes into two stages:
1. Decide which features are to be merged, this can be find in 
https://github.com/microsoft/LightGBM/blob/da98f24711a2faab17f94e5b2a636e6609c93fa6/src/io/dataset.cpp#L100
which is called by https://github.com/microsoft/LightGBM/blob/99e0a4bd7b9e7c557e593ff9172799822abc4b7d/src/io/dataset.cpp#L239-L244
And after `FastFeatureBundling`, you will see `FeatureGroup` are created according to the groups found, https://github.com/microsoft/LightGBM/blob/99e0a4bd7b9e7c557e593ff9172799822abc4b7d/src/io/dataset.cpp#L396-L397
In this step, the `bin_offsets_` in the feature groups are created, which is used in the `PushData` method. You can think `bin_offsets_` acts as `max(f1)` in your previous comment https://github.com/microsoft/LightGBM/issues/4114#issuecomment-960926731. That's why I say the merging happens in `PushData`.
2. Read the raw data again and maps the raw data into binned data. Then call the `PushData`.
