### ISSUE TITLE
Algorithm (pseudo code) Explanation

### ISSUE THREAD

**Issue by aceson28** [microsoft/LightGBM#4138]
in LightGBM paper (https://papers.nips.cc/paper/2017/file/6449f44a102fde848669bdd9eb6b76fa-Paper.pdf.)
in algorithm 1 what mean of  I.f[k][j].bin ? i can't find where is f coming from
in algorithm  3 "bundles ← {}, bundlesConflict ← {}" is that means defining 2 blank object? if that true, where these are coming "for j = 1 to len(bundles) do" and bundlesConflict[i] ? if is it blank so what value of lenght of blank object?

**Comment by shiyu1994** [comment]
Hi @aceson28, in algorithm 1 `I.f[k][j].bin` means the bin value of feature `k` of data `j`.
In algorithm 3, `bundles` is the set to store all bundles. `bundlesConflict` store the number of conflicts in each bundle. Also, I believe that `bundlesConflict[i]` in the condition of the `if` statement should be `bundlesConflict[j]` (which is a typo).
Initially, both sets are empty, so in the first iteration of `i`, the second `for` loop won't be executed, so `needNew` will be `true`. And then a new bundle will be created to contain only the first feature, and added to `bundles`. In the same time, `bundlesConflict[0]` will also be updated to `0` (since there's only one feature, there won't be any conflict). The update of `bundlesConflict` is not explicitly written in the pseudo code.
