### ISSUE TITLE
Validation dataset creation via Sequence

### ISSUE THREAD

**Issue by Willian-Zhang** [microsoft/LightGBM#4184]
> This issue refers to an underdevelopment feature/PR: Sequence support for dataset

_Originally posted by @shiyu1994 in https://github.com/microsoft/LightGBM/pull/4089#discussion_r612925344_

This post is created for keeping track of and providing new LightGBM developer more insight on design of LightGBM data pipelines.

Please close this issue upon #4089 is merged.

**Comment by Willian-Zhang** [comment]
@shiyu1994 Would you mind explaining `CreateValid` from:
https://github.com/microsoft/LightGBM/blob/fba18e488ccd82b25c4e0788b2fec1f75bcde46a/src/io/dataset.cpp#L726-L770 

Specifically: Can it be used to create training dataset as well.

From my current understanding, it's creating a new dataset, regardless of training or validation, from a referenced dataset. To be specific, copying its BinMapper, resetting actually data and associated states to empty and nothing else.

However I'm not sure what these does:
https://github.com/microsoft/LightGBM/blob/fba18e488ccd82b25c4e0788b2fec1f75bcde46a/src/io/dataset.cpp#L750-L752
https://github.com/microsoft/LightGBM/blob/fba18e488ccd82b25c4e0788b2fec1f75bcde46a/src/io/dataset.cpp#L758-L760

Are they related to `Exclusive Feature Bundling` featured in the paper?

**Comment by shiyu1994** [comment]
In principal, we don't specify `reference` when creating training dataset. So `CreateValid` shouldn't be used for creating training dataset.
https://github.com/microsoft/LightGBM/blob/fba18e488ccd82b25c4e0788b2fec1f75bcde46a/src/io/dataset.cpp#L750-L752
Here the `feature_need_push_zeros_` are just copied from the referenced training data. And it makes no different if we write `feaure_need_push_zeros_ = dataset->feature_need_push_zeros_`.

https://github.com/microsoft/LightGBM/blob/fba18e488ccd82b25c4e0788b2fec1f75bcde46a/src/io/dataset.cpp#L758-L760
But these lines do indicate an important difference between training data and validation data. In LightGBM, features are bundled together according to their sparsity, to speedup training. See Exclusive Feature Bundling in the paper: https://papers.nips.cc/paper/2017/file/6449f44a102fde848669bdd9eb6b76fa-Paper.pdf
Since validation data is only used for inference, there's no need to group the features. So we set `group_feature_start_[i] = i` and `group_feature_cnt_[i] = 1` to make each single feature remains a group by itself.

**Comment by StrikerRUS** [comment]
Closed in favor of being in #2302. We decided to keep all feature requests in one place.

Welcome to contribute this feature! Please re-open this issue (or post a comment if you are not a topic starter) if you are actively working on implementing this feature.

**Comment by StrikerRUS** [comment]
Implemented in #4089.

https://github.com/microsoft/LightGBM/pull/4089#discussion_r659403739
