### ISSUE TITLE
Default arguments differ between interfaces

### ISSUE THREAD

**Issue by david-cortes** [microsoft/LightGBM#4196]
In the Python version of lightgbm, the default number of boosting rounds is 100 (which is reasonable), whereas in the R version the default is 10 (which is not reasonable).

Would be nice if both could have the same default arguments.

(I haven't checked the rest of the arguments so I don't know if there are more discrepancies)

**Comment by jameslamb** [comment]
Thank you for your interest in LightGBM! As you write comments in this project, please keep your tone and wordings respectful. For example, please avoid referring to characteristics of the code that you disagree with as "not reasonable".

I would support a pull request to change the default value for `nrounds` to 100 in the R package, since that is the default in LightGBM's core library: https://lightgbm.readthedocs.io/en/latest/Parameters.html#num_iterations. And we'd be grateful for pull requests making similar changes for any other places where you see that the R package's defaults differ from the LightGBM core library defaults documented at https://lightgbm.readthedocs.io/en/latest/Parameters.html.

Are you interested in making such contributions?

**Comment by david-cortes** [comment]
Created ar PR.
