### ISSUE TITLE
installing R package on macOS

### ISSUE THREAD

**Issue by topepo** [Microsoft/LightGBM#421]
I'm using macOS Sierra 10.12.4 and R version 3.3.3 (2017-03-06) with
```
$ /usr/local/Cellar/gcc/6.3.0_1/bin/gcc-6 --version
gcc-6 (Homebrew GCC 6.3.0_1 --without-multilib) 6.3.0
```
`~/.R/Makevars` is
```
CC=/usr/local/Cellar/gcc/6.3.0_1/bin/gcc-6 -fopenmp
CXX=/usr/local/Cellar/gcc/6.3.0_1/bin/g++-6 -fopenmp
CXX1X=/usr/local/Cellar/gcc/6.3.0_1/bin/g++-6 -fopenmp
SHLIB_CXXLD=/usr/local/Cellar/gcc/6.3.0_1/bin/g++-6 -fopenmp
FC=/usr/local/bin/gfortran-4.8
F77=/usr/local/bin/gfortran-4.8
MAKE=make -j 7

SHLIB_OPENMP_CFLAGS=-fopenmp
SHLIB_OPENMP_CXXFLAGS=-fopenmp
SHLIB_OPENMP_FCFLAGS=-fopenmp
SHLIB_OPENMP_FFLAGS=-fopenmp

LDFLAGS=-L/usr/local/opt/llvm/lib
CPPFLAGS=-I/usr/local/opt/llvm/include
```
Compilation worked with no messages using github version current to 2016-04-13 but:
```r
> library(lightgbm)
Loading required package: R6
> sessionInfo()
R version 3.3.3 (2017-03-06)
Platform: x86_64-apple-darwin13.4.0 (64-bit)
Running under: macOS Sierra 10.12.4

locale:
[1] en_US.UTF-8/en_US.UTF-8/en_US.UTF-8/C/en_US.UTF-8/en_US.UTF-8

attached base packages:
[1] stats     graphics  grDevices utils     datasets  methods   base     

other attached packages:
[1] lightgbm_0.1 R6_2.2.0    

loaded via a namespace (and not attached):
[1] magrittr_1.5      data.table_1.10.4
>      library(lightgbm)
>      data(agaricus.train, package = "lightgbm")
>      train <- agaricus.train
>      dtrain <- lgb.Dataset(train$data, label = train$label)
>      params <- list(objective = "regression", metric = "l2")
>      model <- lgb.cv(params,
+                      dtrain,
+                      10,
+                      nfold = 5,
+                      min_data = 1,
+                      learning_rate = 1,
+                      early_stopping_rounds = 10)
Loading required package: Matrix
R(70152,0x70000b4b9000) malloc: *** error for object 0x7fa5d0d30a40: pointer being freed was not allocated
*** set a breakpoint in malloc_error_break to debug
R(70152,0x7fffcf97e3c0) malloc: *** error for object 0x7fa5d3b00268: incorrect checksum for freed object - object was probably modified after being freed.
*** set a breakpoint in malloc_error_break to debug
R(70152,0x70000b5bf000) malloc: *** error for object 0x7fa5d0c52ce0: double free
*** set a breakpoint in malloc_error_break to debug
Abort trap: 6
```
More history on this is at topepo/caret#572

**Comment by Laurae2** [comment]
@topepo Do you know an online place where we can rent a Mac with different OSes (with GPU support) so we can try to make proper/reproducible working instructions for Mac to have:

* Support for multithreading
* Support for GPU

? ping also @tobigithub if you know anything so we can make the Mac installation setup step ahead, since Mac (macOS only specifically..?) seems to be an issue since the beginning (https://github.com/Microsoft/LightGBM/issues/89).

You can ping @huanzhang12 and myself if you have any tip to point us to the right direction, as only Macs are missing from our hands to do this.

**Comment by Laurae2** [comment]
@topepo Can you install and try first with gcc 5 and tell us if it works?

gcc 6 and macOS seems to be a known issue which is not limited to LightGBM but to many other libraries using OpenMP.

**Comment by topepo** [comment]
```
$ /usr/local/Cellar/gcc@5/5.4.0_1/bin/gcc-5 --version
gcc-5 (Homebrew GCC 5.4.0_1 --without-multilib) 5.4.0
```
That seems to have done it. I can execute the examples in the R package without any issues. 

Thanks!

**Comment by tobigithub** [comment]
Hi,
not affiliated, never tried: 

www.hostmyapple.com
https://xcloud.me
https://www.macstadium.com
www.macincloud.com

Although I feel  Timothy Donald "Tim" Cook  should give Bill Gates 
and Satya Nadella  a freed demo version of their latest hardware and
software for development purposes.  Because:
https://www.wired.com/2009/08/dayintech_0806/

probably cheapest native  version:
https://www.apple.com/mac-mini/macos/

**Comment by psdhillon** [comment]
how about gcc 7, is this problem still persist with gcc7 as i am unable to get over this problem. Please suggest
