### ISSUE TITLE
Saving Model to binary stream

### ISSUE THREAD

**Issue by bholekiran** [microsoft/LightGBM#4217]
Is the feature of saving the Model to binary stream or binary file supported now in lightGBM?

I could see below file in branch but not in main source code.
https://github.com/wxchan/LightGBM/blob/1e6091c01f75cbbc86b55b104ae3231d302a0a9f/src/proto/gbdt_model_proto.cpp

Also If I want to save the model in binary format then protobuf is the only option or any other ways as well?

Could somebody please answer and point me to any examples of doing it?

Thanks.

**Comment by StrikerRUS** [comment]
> I could see below file in branch but not in main source code.

protobuf support was merged into main source code one day: #908.
But then it was reverted #1002 and replaced with faster implementation of saving models into text format #1083.

**Comment by bholekiran** [comment]
@StrikerRUS Thank you so much for clarification.
Is there any plan to implement this new feature of saving model in binary format in near future?
Please comment.

Thanks,
Kiran

**Comment by StrikerRUS** [comment]
I can't find any item in our feature requests hub (#2302) related to this. Would you like to add it there? If so, please fill in the following short form and describe why binary format is needed and how it will improve LightGBM.
https://github.com/microsoft/LightGBM/blob/master/.github/ISSUE_TEMPLATE/FEATURE_REQUEST.md

**Comment by bholekiran** [comment]
@StrikerRUS Thanks for pointing me to this repository.
I raised the below feature request:-
https://github.com/microsoft/LightGBM/compare/master...bholekiran:patch-1

**Comment by jameslamb** [comment]
Thanks @bholekiran !

But @StrikerRUS meant to paste that in here, not to create a patch on your fork. I've done that for you below.

<hr>

## Summary

Saving and loading LightGBM model to binary stream or file like text.

## Motivation

Some analytical or predictive models are stored in binary format so that user cannot see the way model is implemented. It can be usefult also when user is layman. Other benefit can be model cannot be easily tampered. In that case two unnecessary steps of saving to text and then create blob out of it while saving and read blob and convert it to text for loading to library. This can lower the performance so can this be considered as new feature to implement?

## Description
Thanks,
Kiran

## Description

This was already implemented at below link so would be easy to implement it in master as an additional API to provide better flexxibility:
https://github.com/wxchan/LightGBM/blob/1e6091c01f75cbbc86b55b104ae3231d302a0a9f/src/proto/gbdt_model_proto.cpp

## References

As an reference this machine learning model is save and loaded from Binary format.
https://machinelearningmastery.com/save-load-machine-learning-models-python-scikit-learn/

**Comment by bholekiran** [comment]
Thanks @StrikerRUS and @jameslamb for quick actions.

**Comment by StrikerRUS** [comment]
@bholekiran Thanks for providing details for your feature request!
I think we can add this as a feature request but I believe it requires further discussion.

> Other benefit can be model cannot be easily tampered.

Sorry, but I don't believe that only binary format in open source project can prevent tampering in any way... Encryption is needed here.

BTW, the article you've referring in  your rationale is describing pickling. I want to note that LightGBM models can be easily pickled as well.
https://github.com/microsoft/LightGBM/blob/d5c2c55682cdf52b9371dbead9bd551e2acbffdc/examples/python-guide/advanced_example.py#L86-L92

Does it fit your needs?

**Comment by bholekiran** [comment]
@StrikerRUS Yes you are right that encryption is needed there.
Yes it seems that this will solve my requirement. Thanks.
You may close this issue.
