### ISSUE TITLE
[Question] Is gamma loss actually an exponential loss?

### ISSUE THREAD

**Issue by hlee13** [microsoft/LightGBM#4218]
Is gamma loss actually an exponential loss?

**Comment by hlee13** [comment]
in gamma metric code segments, psi = 1.0

also get_gradients function

**Comment by shiyu1994** [comment]
@hlee13 Thanks for using LightGBM. Since `psi = 1`, the form of this gamma loss is exactly the exponential loss. However, in the gamma objective loss, we use `log-link`, which means `\hat{y} = ln (\theta)`. Plug this into the expression of gamma loss with `psi=1`, it is different with the exponential loss, which should be `exp (-y \hat{y})`.
By the way, it seems that the gamma metric uses the canonical link function, instead of the log-link. It seems inconsistent with the gamma objective function. I'll investigate more into this, and if necessary, I'll fix it.

**Comment by hlee13** [comment]
@shiyu1994 gamma metric use log-link function in RegressionPoissonLoss::ConvertOutput
Moreover, when psi=1, gamma loss actually exponential loss. In RegressionGammaLoss::GetGradients, actually exponential loss gradients

**Comment by guolinke** [comment]
hi @shiyu1994, is this question solved?
