### ISSUE TITLE
When to use split vs gain for plot_importance?

### ISSUE THREAD

**Issue by annaymj** [microsoft/LightGBM#4255]
## Description
The default plot_importance function uses split, the number of times a feature is used in a model.  Gain is an alternative choice.
I am wondering whether there is any guidance or recommendation when to use split and when to use gain for feature importance understanding. Thanks!

**Comment by shiyu1994** [comment]
@annaymj Thanks for using LightGBM! In decision tree literature, the gain-based feature importance is the standard metric, because it measures directly how much a feature contributes to the loss reduction. However, I think since the split features are selected through split gain, number of times being used should result in similar feature importance ordering.
I'm not sure whether you observed a significant difference between the two in your use cases. Please feel free to post further questions here and I'll try my best to help.
