### ISSUE TITLE
Support forced splits with data and voting parallel versions of LightGBM

### ISSUE THREAD

**Issue by imatiach-msft** [microsoft/LightGBM#4260]
## Summary

I'm unable to add forced splits to the data and voting parallel versions of lightgbm in mmlspark, I see the error:

https://github.com/microsoft/LightGBM/blob/master/src/io/config.cpp#L318

```
Don't support forcedsplits in data tree learne
```

## Motivation

I would like to add this feature but I'm not sure why I can't just remove that line in the config and enable it.  What is special about the data and voting parallel learners that wouldn't allow this config to be specified on each node?

## Description

The fix would be to remove that thrown exception.  Also, it would be great if we could specify the forced splits as a string directly instead of a file.

https://github.com/microsoft/LightGBM/blob/master/src/boosting/gbdt.cpp#L769

**Comment by imatiach-msft** [comment]
it looks like the ForceSplits function is also only implemented in the serial tree learner:
 
https://github.com/microsoft/LightGBM/blob/master/src/treelearner/serial_tree_learner.cpp#L450
 
seems I would need to do something similar in the  data parallel tree learner:
 
https://github.com/microsoft/LightGBM/blob/master/src/treelearner/data_parallel_tree_learner.cpp

**Comment by shiyu1994** [comment]
For data and voting distributed training, we need to synchronize the histogram before `GatherInfoForThreshold` is called. Otherwise each machine would get a different leaf value and leaf gain, given the incomplete features histograms which sums over only partial data.
https://github.com/microsoft/LightGBM/blob/f83180883a51729af9562ccac7b450c6da79a04a/src/treelearner/serial_tree_learner.cpp#L483-L489

So the logic for implementing `ForceSplits` in data and voting distributed training is not quite straightforward as in feature distributed training.

**Comment by StrikerRUS** [comment]
Closed in favor of being in #2302. We decided to keep all feature requests in one place.

Welcome to contribute this feature! Please re-open this issue (or post a comment if you are not a topic starter) if you are actively working on implementing this feature.
