### ISSUE TITLE
'deterministic' parameter not recognised

### ISSUE THREAD

**Issue by davidmosca** [microsoft/LightGBM#4335]
## Description
The code below triggers the following error:
`[LightGBM] [Warning] Unknown parameter: deterministic`
According to the documentation (https://lightgbm.readthedocs.io/en/latest/Parameters.html), 'deterministic' is a valid parameter.

## Reproducible example
```import lightgbm as lgb
import numpy as np
model = lgb.LGBMRanker(importance_type='gain', deterministic=True, min_child_samples=1, force_col_wise=True)
N = 20
y = np.arange(N)
X = np.random.normal(size=(N, 2))
X[:, 1] = y[0:]+1
model.fit(X, y, group=[N])
```

## Environment info

LightGBM version or commit hash: 3.0.0

Command(s) you used to install LightGBM

`conda install -c conda-forge lightgbm`

Windows 10 Pro, Python 3.8

**Comment by jameslamb** [comment]
Thanks for using LightGBM, and for the excellent detailed report! We really appreciate it.

`deterministic` was introduced in LightGBM 3.1.0

*  https://github.com/microsoft/LightGBM/pull/3494
* https://github.com/microsoft/LightGBM/releases/tag/v3.1.0

We do not maintain the `conda-forge` package, but I just checked https://github.com/conda-forge/lightgbm-feedstock and it looks like that package is up to 3.2.1. So I expect that this would be fixed by `conda install -c conda-forge -y 'lightgbm>=3.1.0'`

**Comment by jameslamb** [comment]
> According to the documentation (https://lightgbm.readthedocs.io/en/latest/Parameters.html), 'deterministic' is a valid parameter.

Apologies for the confusion on this, we only very recently adopted the practice of publishing versioned docs (#4236), so the documentation at that site refers to the state of LightGBM as of the most recent development version.

**Comment by davidmosca** [comment]
Updating LightGBM solves the issue. Thanks.
