### ISSUE TITLE
Custom subsample method

### ISSUE THREAD

**Issue by mangleddata** [microsoft/LightGBM#4379]
I don't know if it's possible, but is there a way to apply a custom subsampler while building trees. While there's a parameter to control the ratio of instances being chosen, I am trying to see if there's a way to have more fine grained control. I am working with timeseries data where the neighboring training rows leak information, so the intent is to make sure the population being chosen has enough variety (simplest would be to space them apart to prevent data leakage)
```
subsample (float, optional (default=1.)) – Subsample ratio of the training instance.
```
Appreciate any pointers if it could be done (even if it meant tweaking my own build)

**Comment by shiyu1994** [comment]
@mangleddata Thanks for using LightGBM. To do this, you can modify the `Bagging` method in `src/boosting/gbdt.cpp` (more specifically line 231 to line 248). You can do anything you want as long as `bag_data_indices_` (which is the data indices you want to choose in this iteration) and `bag_data_cnt_`, the number of selected data, are well-defined. You may implement `Bagging` so that the indices in `bag_data_indices_` have enough variety.
https://github.com/microsoft/LightGBM/blob/ec1debcee84e6b02f749282d9a501021370e74a9/src/boosting/gbdt.cpp#L228-L262

**Comment by shiyu1994** [comment]
If you have any further question about how to implement, please feel free to post here.
