### ISSUE TITLE
Creation of a Booster object with a subset of features

### ISSUE THREAD

**Issue by youyoux7** [microsoft/LightGBM#4384]
With feature_importance, one can easily get the subset of the features effectively used by the fitter (used for splitting in at least one tree) from a model that has been fitted.
Is there a convenient way to create a new model file/Booster object that only uses that subset of features without the unused ones? This would be easier for using a fitted model without having to compute the unused features.

**Comment by shiyu1994** [comment]
@youyoux7 Thanks for using LightGBM.
1. If your goal is to ignore these unused features when training a new model. Specifying `ignore_column` should meet your demand. See
https://lightgbm.readthedocs.io/en/latest/Parameters.html#ignore_column.
2. If your goal is to ignore these unused features when prediction, the model itself should require no computation of the unused features, since they are not used in the model. So you may replace the unused features with any values, for example, fill them with 0's.

If you have any further question, please feel free to post here.
