### ISSUE TITLE
[dask] what learning parameters can be used?

### ISSUE THREAD

**Issue by darshanbint** [microsoft/LightGBM#4398]
## Summary

Parameters like min_data_per_group, cat_l2, cat_smooth, max_cat_threshold missing from DaskLGBMClassifier, will passing them as kwargs work? Or this is still not implemented yet? Please help

**Comment by jameslamb** [comment]
Thanks for using LightGBM! I've reformatted this issue so that most of the question is in the description, not the title. That makes it easier to understand when looking at the list of issues.

All of the parameters mentioned, and many more, can be passed directly to `lightgbm.dask.DaskLGBMClassifier`'s constructor. You can try this yourself by modifying the examples at https://github.com/microsoft/LightGBM/tree/master/examples/python-guide/dask and inspecting the resulting model.

If you try to use one of these parameters with `lightgbm.dask` and find that it does not work, please provide a reproducible example, a bit of code that you expected to work but which does not, and a clear explanation of the difference between how you expected LightGBM to behave and how it actually behaved. That reproducible example should also include information about the version of LightGBM you are using and how you installed it.
