### ISSUE TITLE
[R-package] session crashes when serializing and deserializing model

### ISSUE THREAD

**Issue by verajosemanuel** [microsoft/LightGBM#4415]
I trained a model in R using LightGBM (treesnip) and saved using common saveRDS command.

To my surprise, when trying to predict some data after reading the saved model, readRDS seems to work but script&predict is crashing.

Read this issue https://github.com/microsoft/LightGBM/issues/4208  regarding some similar issue but I am not sure that is the cause.

is there any safe procedure to save my model fot later use in R?

regards

**Comment by jameslamb** [comment]
It is hard to say for sure since you haven't provided a reproducible example showing exactly what you tried, but based on the information you've provided, #4208 probably describe problems you're facing using `saveRDS()` / `readRDS()`. I recommend subscribing to #4208 to be sure you're notified once that issue is resolved.

Until then, you can use the functions `lightgbm::saveRDS.lgb.Booster()` and `lightgbm::readRDS.lgb.Booster()` to save a `{lightgbm}` model object.

You can try these by using the following code:

```r
library(lightgbm)

data(agaricus.train, package = "lightgbm")

dtrain <- lightgbm::lgb.Dataset(
    agaricus.train$data
    , label = agaricus.train$label
)
bst <- lightgbm::lgb.train(
    params = list(
        "learning_rate" = 0.05
    )
    , data = dtrain
    , nrounds = 10L
    , obj = "binary"
)

model_file <- "test-model.rds"
saveRDS.lgb.Booster(
    object = bst
    , file = model_file
)

rm(list = ls())
```

After running that code, restart your R session and re-load the model. You should see that you're able to successfully predict on new data.

```r
library(lightgbm)

model_file <- "test-model.rds"

data(agaricus.test, package = "lightgbm")
bst <- lightgbm::readRDS.lgb.Booster(
    file = model_file
)

preds <- predict(bst, data = agaricus.test$data)
print(preds)
```

For more, see:

* `?lightgbm::readRDS.lgb.Booster`
* unit tests on model serialization and deserialization: https://github.com/microsoft/LightGBM/blob/53ffba7c5c4a4d64853ad6c5409735b986283d2d/R-package/tests/testthat/test_lgb.Booster.R#L831

NOTE: I'm not familiar with how `{treesnip}` works. If it returns its own object which wraps a `{lightgbm}` Booster, then until #4208 is resolved you will have to extract the Booster from that `{treesnip}`-specific object to use the example code above.

**Comment by verajosemanuel** [comment]
that's correct! just the issue I was having. Thanks for the workaround!!!

**Comment by jameslamb** [comment]
> Sadly, the code you provided crashed my R environment

How did you install `{lightgbm}` and what version of it are you using? As I mentioned in https://github.com/microsoft/LightGBM/issues/4007#issuecomment-869080432, there have been several stability fixes to the R package that have not yet been released.

If you need further help, please provide a reproducible example.
