### ISSUE TITLE
Question: why setting num_threads = cpu cores is better

### ISSUE THREAD

**Issue by LittleLittleCloud** [microsoft/LightGBM#4425]
I'm running a few experiments using lgbm in docker container, and I find a SIGNIFICANT speed improvement when setting `num_threads` equals to cpu number instead of thread number (which is cpu number * 2). Just wonder if it is expected?

FYI, the cpu limit is set to 1 for that docker container. So the old `num_threads` is 2 while the new `num_threads` is 1. And the new `num_thread` improves training speed by 20X approximately.

**Comment by shiyu1994** [comment]
The physical core numbers of CPU is the actual number of cores. But the thread number, which is twice of the CPU core numbers in some intel CPUs, is due to the hyperthreading design. Hyperthreading means that a CPU core can be allocated 2 threads so that when one thread waits for data being fetched from memory, another thread can be scheduled to the core. In this way, we can hide memory latency.

Using hyperthreading maybe helpful in some cases. But it can also hurt the performance in other cases. For example, when each thread use a lot of cache, two threads in the same core may compete for the cache space, so there can be more cache misses with hyperthreading.

It is hard to determine from the algorithm itself whether hyperthreading is useful or not. But I observed that in GBDT applications, using hyperthreading is often a bad choice.

**Comment by StrikerRUS** [comment]
> Just wonder if it is expected?

Yeah, it's expected and have been already documented:

> for the best speed, set this to the number of **real CPU cores**, not the number of threads (most CPUs use hyper-threading to generate 2 threads per CPU core)
   https://lightgbm.readthedocs.io/en/latest/Parameters.html#num_threads

**Comment by jameslamb** [comment]
Agree with everything said above. Linking this related issue that provides a little bit more context: https://github.com/microsoft/LightGBM/issues/4192#issuecomment-822023560
