### ISSUE TITLE
Categorical features are not passed to _Booster

### ISSUE THREAD

**Issue by lingyi-ms** [microsoft/LightGBM#4451]
https://github.com/microsoft/LightGBM/blob/e36cc9c1717665963a7fed09a5413a2bf5f0f50a/python-package/lightgbm/sklearn.py#L712

Shouldn't it be this instead? 
```python
self._Booster = train(params, train_set,
                              self.n_estimators, valid_sets=valid_sets, valid_names=eval_names,
                              early_stopping_rounds=early_stopping_rounds,
                              evals_result=evals_result, fobj=self._fobj, feval=eval_metrics_callable,
                              verbose_eval=verbose, feature_name=feature_name,
                              categorical_feature=categorical_feature,
                              callbacks=callbacks, init_model=init_model)
```

**Comment by StrikerRUS** [comment]
Hey @lingyi-ms ! Thanks for your question. Categorical features is a parameter of the Dataset object in LightGBM. That's why `categorical_feature` param is located in the `Dataset Parameters` section
https://lightgbm.readthedocs.io/en/latest/Parameters.html#categorical_feature.
And that parameter is passed here
https://github.com/microsoft/LightGBM/blob/e36cc9c1717665963a7fed09a5413a2bf5f0f50a/python-package/lightgbm/sklearn.py#L664-L671
