### ISSUE TITLE
[Question] How to merge boosters to make a multiclass (OVA) classifier booster?

### ISSUE THREAD

**Issue by wsonv** [microsoft/LightGBM#4456]
Hello, 
I'm trying to individually train boosters and merge it. (Trying to make One versus all classifiers and merge it)
I need to use monotonicity constraints etc, so using multiclass objective is not fit for my purpose.

But I don't see specific merging functions etc. But since you have multi_class_ova objectives, I guess there is a function for this. Could you guide me on how to do this?

I'm trying to merge it and make it as one booster since it is convenient in saving/loading (Also there is a function that I want to use but this function is only good for one booster instance.)

**Comment by shiyu1994** [comment]
@wsonv Thanks for using LightGBM. Do you want to train your own OVA classifiers because you want to specify different monotone constraints for the scores of different classes?

So far we don't have an interface to merge boosters into one. We may merge the boosters by merging the tree items in the text model files. But I'm not sure whether that will meet your need.

Please feel free to post any further question here.
