### ISSUE TITLE
Unable to update existing booster

### ISSUE THREAD

**Issue by George3d6** [microsoft/LightGBM#4466]
I seem to be unable to update an existing booster. In the documentation I was able to find two methods:
1. `refit` , which seems to completely refit, thus it's not very useful for my needs.
2. `update`, which seems to do what I require but:
   * The booster has to have the `train_set` set, it's unclear to me if this means I actually need to store the previous training set used for the booster, or if it's enough to set this to `None` in order to use `update` as "add extra tree to handle new data"
   * `update` seems to get stuck, whereas a "normal" itteration takes ~0.1second for my usecase, I've been waiting for `update` to finish (with a much smaller dataset) for over 100 seconds with no results

What's the recommended strategy for updating a model to handle new observations? Ideally without having to store all previous observations. Is the experience I'm having with `update` a potential bug or expected under certain usage scenarios. It happens both when I set the model's `train_set` to `None` and when I set it to the `Dataset` I used to actually train, it seems to happen both for optuna generated models and for those generated via lgbm directly.

**Comment by George3d6** [comment]
Update: It *seems* that one way to do this might be `model = lightgbm.train(params, dataset, init_model=model)`

And just set the nr of itterations in the params to be == however many estimators ought to be added, but I'm not entirely sure this is correct. If so it *might* make sense to make this more explicit in the documentation.

**Comment by shiyu1994** [comment]
@George3d6 Thanks for using LightGBM.
Yes, the `init_model` in the `train` function is for continual training. You can use that.

For update, it is only boost for one more iteration. The behavior you reported about the update method is strange, though. `update` is called during the training process in each iteration. To make it work, you need to set `keep_training_booster=True` in the `train` method, so that the information during training is kept in the `Booster` object. Otherwise an error should be reported when calling `update`, as shown below.
```
AttributeError: 'Booster' object has no attribute 'train_set'
```
