### ISSUE TITLE
doc: missing score method on LGBMRegressor methods doc

### ISSUE THREAD

**Issue by raybellwaves** [microsoft/LightGBM#4479]
AFAICT in the docs under https://lightgbm.readthedocs.io/en/latest/pythonapi/lightgbm.LGBMRegressor.html and scrolling down to methods I don't see the score method being mentioned

![Screen Shot 2021-07-16 at 4 51 16 PM](https://user-images.githubusercontent.com/17162724/126007171-4b08f446-267b-44e9-8b1c-e2abebe4e384.png)

but it exists

![Screen Shot 2021-07-16 at 4 51 58 PM](https://user-images.githubusercontent.com/17162724/126007234-099e163a-d984-4a46-8aef-68a0debeb653.png)

I feel it would be worth adding to the docs.

**Comment by StrikerRUS** [comment]
@raybellwaves Thanks for writing this issue!

Just a clarification why it is happening. During docs generation process we mock third-party libraries including scikit-learn
https://github.com/microsoft/LightGBM/blob/5b7a6f3e7150aeb704d1dd2b852d246af3e913a3/docs/conf.py#L41-L45
That's why Sphinx's `autodoc` extension with turned on `inherited-members` option
https://github.com/microsoft/LightGBM/blob/5b7a6f3e7150aeb704d1dd2b852d246af3e913a3/docs/conf.py#L94-L99
cannot know anything about `score` method from [`RegressorMixin`](https://scikit-learn.org/stable/modules/generated/sklearn.base.RegressorMixin.html)/[`ClassifierMixin`](https://scikit-learn.org/stable/modules/generated/sklearn.base.ClassifierMixin.html) parent class which is actually a dummy stub during docs generation process
https://github.com/microsoft/LightGBM/blob/5b7a6f3e7150aeb704d1dd2b852d246af3e913a3/python-package/lightgbm/compat.py#L103-L111
