### ISSUE TITLE
plot_tree returns empty chart

### ISSUE THREAD

**Issue by chinnawat1** [microsoft/LightGBM#4482]
Working on azure databricks, I would like to plot a tree classifier diagram by using plot_tree. Here is what I did and got:

![image](https://user-images.githubusercontent.com/53522784/126429676-cfad81c3-b06f-43a6-8302-6c8f80052667.png)

I also tried using "create_tree_digraph". Sadly, I can't install graphviz library since after installing by following this https://docs.microsoft.com/en-us/azure/databricks/libraries/cluster-libraries#install-workspace-libraries all the commands cannot be run. So I've decided to use plot_tree rather than create_tree_digraph.

**Comment by StrikerRUS** [comment]
Hey @chinnawat1 !

> Sadly, I can't install graphviz library since after installing by following this ...

`plot_tree()` function internally calls `create_tree_digraph()` function and then converts a result to `png` format. That's why you get empty axes.
https://github.com/microsoft/LightGBM/blob/5b7a6f3e7150aeb704d1dd2b852d246af3e913a3/python-package/lightgbm/plotting.py#L667-L678
Unfortunately, without installing `graphviz` library you cannot plot trees in LightGBM.
