### ISSUE TITLE
[doc] [R-package] Add {lightgbm} to ModelDeployment CRAN view?

### ISSUE THREAD

**Issue by jameslamb** [microsoft/LightGBM#4566]
## Summary

CRAN supports a feature called "task views", which can be used to discover packages related to a specific topic.

@terrytangyuan, could `{lightgbm}` be added to the ModelDeployment view at https://cran.r-project.org/web/views/ModelDeployment.html, since `{xgboost}` is there? I know I could have DM'd you, but thought it would be better to have the conversation here so other LightGBM maintainers and users of the R package could see.

Thanks for considering it!

**Comment by terrytangyuan** [comment]
Thanks for asking and yes it would be great to include lightgbm there! 

Feel free to submit a PR to the repo for this specific task view [here](https://github.com/terrytangyuan/ctv-model-deployment). Note that once the PR is merged, it may still take quite a while for the change to be updated on CRAN since I will need to check with CRAN team to see if there's any update on the maintenance process over the last year.

**Comment by jameslamb** [comment]
Oh thanks! Didn't realize there was a repo dedicated to that task view, I should have scrolled all the way to the bottom of the page 😂

**Comment by jameslamb** [comment]
I've open https://github.com/terrytangyuan/ctv-model-deployment/pull/6 with a suggestion, so I think this issue here can be closed. Thanks again!

**Comment by mayer79** [comment]
Sweet! LightGBM is on https://cran.r-project.org/web/views/MachineLearning.html as well.
