### ISSUE TITLE
The Recommendation for Training Big Image Data that Cannot Fit into Memory

### ISSUE THREAD

**Issue by xuzikun2003** [microsoft/LightGBM#4672]
## Summary
Right now if we try to train a folder of image data that cannot fit into memory of a single machine, lightgbm is not an available option. We can see some distributed solutions for lightgbm but each of them requires one partition of the data to fit into memory in a single node.

Do we have a solution to train the data that cannot fit into memory on a single node with lightgbm?

## Motivation
Train large dataset on a single node.

**Comment by jameslamb** [comment]
Thanks for using LightGBM!

I have a few suggestions below for "train a model on a larger-than-memory dataset on a single node". This question is also making me realize we should have a dedicated section in the documentation for this.

**1. Use `lightgbm`'s new Sequence API**

In #4089, `lightgbm` took on a new API in the Python package that allows the creation of a LightGBM `Dataset` object from multiple files.

You might find that this interface allows you to accomplish training on a single node when the raw data is larger than memory on that node, since it constructs a Dataset incrementally from multiple files.

* examples: https://github.com/microsoft/LightGBM/blob/master/examples/python-guide/dataset_from_multi_hdf5.py
* API docs: https://lightgbm.readthedocs.io/en/latest/pythonapi/lightgbm.Sequence.html?highlight=Sequence
* tests (for more examples):
    - https://github.com/microsoft/LightGBM/blob/29857c8adb3c879268cddc23037e0651c2ec4df6/tests/python_package_test/test_basic.py#L94
    - https://github.com/microsoft/LightGBM/blob/29857c8adb3c879268cddc23037e0651c2ec4df6/tests/python_package_test/test_basic.py#L135

When this could work: If you are able to upgrade to `lightgbm` 3.3.0, and can partition your data into multiple files that will work with the `Sequence` access pattern.

**2. Try using `lightgbm.dask`**

Depending on where in the process you're running out of memory, you might be able to avoid such problems by using `lightgbm.dask`. You can see the docs at https://lightgbm.readthedocs.io/en/latest/Parallel-Learning-Guide.html#dask-examples.

At high levels of memory usage, Dask workers will start spilling to disk. This can make processing much slower, but allows you to work on larger-than-memory data. http://distributed.dask.org/en/latest/worker.html#memory-management. Dask will work on a single machine if you use a `LocalCluster`, as all of the examples at https://github.com/microsoft/LightGBM/tree/5c8a331bf5966f1df546f154f64ed9b8856a90ee/examples/python-guide/dask do.

If you do this, it's important to partition your data in a way that allows Dask to not need to hold all of it in memory at the same time. For example, you might create a partitioned directory of Parquet files and use `dask.DataFrame.read_parquet()` (https://docs.dask.org/en/latest/generated/dask.dataframe.read_parquet.html).

When this could work: If your training data all fits in memory on one node *after feature engineering / feature selection / sampling*.

**3. Train a smaller model**

If you have sufficient memory to load the data and create a `lgb.Dataset`, but then hit memory issues during training (as the model object grows), most of the strategies at https://lightgbm.readthedocs.io/en/latest/Parameters-Tuning.html#for-faster-speed can also be used to reduce the memory footprint of the model. For example, decreasing `num_leaves` / `max_depth` or increasing `min_gain_to_split`, `min_data_in_leaf`, or `min_sum_hessian_in_leaf` will lead to smaller models.

When this could work: If your training data all fits in memory on one node but you see out of memory errors once training begins, due to the memory footprint of the model. And if you are able to confirm that the statistical performance of the smaller model is good enough for your use case.

**4. Use Training Continuation**

LightGBM offers the ability to start the boosting process from an existing trained model. See https://github.com/microsoft/LightGBM/blob/c6199311dece08e6ac08778f60d7fc9c3d796b11/examples/python-guide/advanced_example.py#L102-L112.

So I think you could partition your data into multiple files, then do something like the **pseudocode** below.

```python
import lightgbm as lgb

first_file = "some_file.csv"
data, label = get_raw_data_from_csv(first_file)
first_dataset = lgb.Dataset(first_file, params={"label_column": "y"}, free_raw_data=True)
first_dataset.construct()

# train a model on this first chunk of data, for a few rounds
booster = lgb.train(
    train_set=first_dataset,
    num_boost_round=10,
)
booster.save_model("model.txt")
del booster

# for each additional file, create a Dataset and train a few more rounds
for next_file in rest_of_the_files:
    dataset = lgb.Dataset(
        next_file,
        params={"label_column": "y"},
        free_raw_data=True,
        reference=first_dataset
    )
    dataset.construct()
    booster = lgb.train(
        train_set=dataset,
        num_boost_round=10,
        init_model="model.txt"
    )
    # overwrite model file
    booster.save_model("model.txt")
    # free memory before next file
    del dataset, booster
```

This will be much slower than training with all of the data in memory at once, and you'll have to be very careful about how the data is partitioned. The distribution of features and the target should be roughly similar across the partitions. See https://github.com/microsoft/LightGBM/issues/4555#issuecomment-924533600 for a bit more information.

When this could work: If you can tolerate much slower training and are comfortable carefully managing the partitioning of the input data.
