### ISSUE TITLE
Loading saved LightGBM model to predict 1 instance of new data.

### ISSUE THREAD

**Issue by Ana3112** [microsoft/LightGBM#4703]
## Description
Hi, apologies if there is anything unclear please let me know.
I am working on a Windows 10 machine.
I have trained the LightGBM model and saved it as a text file using clf.save_model().
Now, I am trying to load this saved model and use the .predict() function to be able to predict a classification of a new instance. 

For example my variable includes the following:
```val1 = [['75', '201', '149',	'14', '1', '1',	'0', '12', '0',	'925', '849', '11', '411', '36800',	'568',	'320', '568', '320', '568', '320']]```
I load the saved model using ```bst = lgb.Booster(model_file="LGBM_model.txt") ```
Then I use ```ypred = bst.predict(val1)``` to predict if the val1 instance is of type class 1 or class 2.

However, I am getting the same percentage each time 0.06420237 for any time of input.
If I try to load the model and use it to predict a dataset, it works fine so I am guessing the issue is with the way I am inputting the data?
I would appreciate if anyone could explain what I am doing wrong please.

## Environment info

LightGBM version or commit hash: LightGBM 3.2.1

Command(s) you used to install LightGBM

```shell
pip install lightgbm
```

**Comment by shiyu1994** [comment]
@Ana3112 Thanks for using LightGBM. Is your model file `LGBM_model.txt` and your test cases with single instances private? If not, could you please share it here so that we can help to identify the problem more easily.
Does the same problem happens if you did not save and load the model, but use the booster for prediction right after the training?
