### ISSUE TITLE
`macOS-10.14` Azure Pipelines environment is deprecated

### ISSUE THREAD

**Issue by StrikerRUS** [microsoft/LightGBM#4797]
> The macOS-10.14 environment is deprecated and will be removed on December 10, 2021. For more details see https://devblogs.microsoft.com/devops/hosted-pipelines-image-deprecation/

We use this environment here
https://github.com/microsoft/LightGBM/blob/6e6fb14cdfdeb4dd0580bfe48f99da1251766bd2/.vsts-ci.yml#L220

The main problem is that that environment is used right now to create release artifacts: LightGBM dylib, SWIG jar and `macosx` Python wheel file.
https://github.com/microsoft/LightGBM/blob/6e6fb14cdfdeb4dd0580bfe48f99da1251766bd2/.vsts-ci.yml#L250-L251

So we should consider this upcoming migration as a possible breaking change: https://github.com/microsoft/LightGBM/pull/4732#issuecomment-955306714.

**Comment by jameslamb** [comment]
@StrikerRUS thanks for getting ahead of this. I think we should switch to the new VM image in CI soon, since we know this removal is coming in a month. To avoid CI being blocked once that image is removed.

Since the next release is 4.0.0, I think it's ok to make this breaking change. The impact is just that users on macOS 10.14.x will end up building from source instead of getting a wheel, right?

**Comment by StrikerRUS** [comment]
> I think we should switch to the new VM image in CI soon,

Agree!

> Since the next release is 4.0.0, I think it's ok to make this breaking change.

Yeah, good timing for us for the first time 😄 

> The impact is just that users on macOS 10.14.x will end up building from source instead of getting a wheel, right?

I think yes. TBH, I don't know what version of Xcode is default for `10.15` and whether it's common or not among macOS users to upgrade/downgrade it. Hope that default is not less than `10.3` by which we'll build all artifacts.
