### ISSUE TITLE
Suppress warnings of LightGBM tuning using Optuna

### ISSUE THREAD

**Issue by akshat3492** [microsoft/LightGBM#4825]
## Description
 I am getting these warnings which I would like to suppress could anyone tell how to suppress it?

[LightGBM] [Warning] feature_fraction is set=0.8, colsample_bytree=1.0 will be ignored. Current value: feature_fraction=0.8
[LightGBM] [Warning] min_data_in_leaf is set=2900, min_child_samples=20 will be ignored. Current value: min_data_in_leaf=2900
[LightGBM] [Warning] min_gain_to_split is set=3.2710454850444934, min_split_gain=0.0 will be ignored. Current value: min_gain_to_split=3.2710454850444934

## Environment info

LightGBM version or commit hash:

Command(s) you used to install LightGBM

```shell

```

**Comment by StrikerRUS** [comment]
Hey @akshat3492 !
Unfortunately, you can't silence these warnings with the `verbose` parameter right now. See #4518.
But you can use an appropriate argument of a function instead of the param alias to make these warnings disappear: https://github.com/microsoft/LightGBM/issues/3641#issuecomment-898438044.
