### ISSUE TITLE
Understanding feature_parallel distributed learning algorithm in LightGBMClassifier

### ISSUE THREAD

**Issue by Nitinsiwach** [microsoft/LightGBM#4945]
I want to understand ```feature_parallel``` algorithm in [LightGBMClassifier][1]. 
It describes how it is done traditionally and how ```LightGBM``` improves it

The two ways are as follows (verbatim from linked site):

**Traditional Feature_parallel:**

Feature parallel aims to parallelize the “Find Best Split” in the decision tree. The procedure of traditional feature parallel is:

1. Partition data vertically (different machines have different feature set).
2. Workers find local best split point {feature, threshold} on local feature set.
3. Communicate local best splits with each other and get the best one.
4. Worker with best split to perform split, then send the split result of data to other workers.

**Feature_parallel in LightGBM:** (Problem text **bold** and *italicized*)

Since feature parallel cannot speed up well when #data is large, we make a little change: instead of partitioning data vertically, every worker holds the full data. ***Thus, LightGBM doesn’t need to communicate for the split result of data since every worker knows how to split data***

**The procedure of feature parallel in LightGBM:** (Problem text **bold** and *italicized*)

1. Workers find ***local best split*** point {feature, threshold} on the local feature set. (Why call it local? Since it is being found on the entire data this is the global best split)

2. Communicate local best splits with each other and get the best one. (But, earlier it was mentioned that ***Thus, LightGBM doesn’t need to communicate for the split result of data since every worker knows how to split data***)

3. Perform best split. (Did we not already have the best split?)

Moreover, If each worker is retaining the entire dataset then it is capable of creating the entire estimator itself. What is distributed learning here?

  [1]: https://lightgbm.readthedocs.io/en/latest/Features.html#optimization-in-distributed-learning

**Comment by jmoralez** [comment]
Hi @Nitinsiwach, thanks for your interest in LightGBM.

First I'd like to point out that the feature parallel tree learner isn't available in the C API:
https://github.com/microsoft/LightGBM/blob/4aaeb22932b72aaff632b40ba596ca2533071ca2/src/c_api.cpp#L129 which means that right now you can only use it through the CLI.

I'll try to answer your questions based on what I think, I hope some other maintainer can correct me if I'm wrong:
1) Each worker finds the best split for the subset of features assigned to it, it is local in the sense that the global best split is the best split across all features.
2) This refers to saying: hey fellas, I found a split with this gain, and then deciding which one has the greatest gain. The difference with respect to the traditional approach is that using only the split info (i.e. X1 <= 16) each worker knows which indices of the data go left and which go right (because every worker holds the full data so they can make that split locally) whereas in the traditional approach the worker that has that feature locally (X1) has to communicate the indices to the other workers.
3) This refers to actually splitting the data based on the best split found in the previous step.

Hope this helps.

**Comment by jameslamb** [comment]
I'd also like to add... @Nitinsiwach please do not double-post here and on Stack Overflow at the same time: https://stackoverflow.com/questions/70678523/understanding-feature-parallel-distributed-learning-algorithm-in-lightgbmclassif.

Doing that means that it's possible that, for example, I could have been answering this question on Stack Overflow at the same time as @jmoralez was answering it here. That would be a bad outcome for the LightGBM project and its users, not just us personally, since we have limited time to spend on maintenance work here.

I'm also requesting that you not do this because, in my experience, we regularly see double-posting where the poster moves on after getting their answer in one place and does not go back to update the other place. That can lead to dead-ends for people facing the same issue in the future who find the unresolved post from search engines.

**Comment by Nitinsiwach** [comment]
@jmoralez - That clears things up for me. Thank you so much for your time, effort and attention :)

@jameslamb - Thank you for helping me understand the proper and efficient code of conduct. I posted it on multiple forums for better reach. I did not think about the downsides of it which I clearly do now
