### ISSUE TITLE
[R-package] Cannot pass CSR single-row for prediction

### ISSUE THREAD

**Issue by david-cortes** [microsoft/LightGBM#4966]
When making predictions on a single row with sparse data, the Python interface for lightgbm allows passing the input as a sparse CSR matrix, and making predictions this way is faster/more efficient than with CSC format when the input is large. The R interface does not allow passing prediction-time inputs in CSR formats (package `Matrix` has classes `dsparseVector` and `dgRMatrix` for that).

**Comment by jameslamb** [comment]
Thanks for the report! Are you able to provide a minimal, reproducible example demonstrating this behavior?

And can you elaborate on what "does not allow" means specifically? e.g., is there an error raised, does LightGBM just produce incorrect results, etc.

We're grateful for your reports and happy to try to help resolve these things, but would really appreciate more details so that maintainers don't spend time guessing things that I suspect you already know.

**Comment by david-cortes** [comment]
Reproducible example:
```r
library(lightgbm)
data("mtcars")
ds <- lgb.Dataset(as.matrix(mtcars[, -1]), label=mtcars[,1])
m <- lgb.train(data=ds, obj="regression")

library(Matrix)
m_pred <- as.matrix(mtcars[, -1])
m_pred <- m_pred[1, , drop=FALSE]
x_csc <- as(m_pred, "CsparseMatrix")
x_csr <- as(x_csc, "RsparseMatrix")
x_spv <- as(x_csc, "sparseVector")

predict(m, x_csc) ### fine, but slow
predict(m, x_csr) ### error
predict(m, x_spv) ### error
```

By "not allows" I mean that it throws errors, because there is no code route to take the input data in those formats.

**Comment by jameslamb** [comment]
Excellent, thanks very much for that!

**Comment by jameslamb** [comment]
I've added this to #2302, where we document feature requests for this project.

Per this project's policies, I'll close this issue for now. Anyone reading this who is interested in contributing this feature, leave a comment and it can be re-opened.
