### ISSUE TITLE
Strange values for single trees

### ISSUE THREAD

**Issue by mlindsk** [microsoft/LightGBM#5017]
I am trying to fit a single decision tree, however I find the output a little strange. I have `15` explanatory variables and the numerical response variable has the following characteristic:

```
count    653.000000
mean      31.503813
std       11.838267
min       13.750000
25%       22.580000
50%       28.420000
75%       38.250000
max       76.750000
Name: X2, dtype: float64
```

I do the following to fit the tree; I first construct the `Dataset` object

```
df_train = lightgbm.Dataset(
    df, # The data 
    label = df[response], # The response series
    feature_name = features, # A list with names of all explanatory variables
    categorical_feature = categorical_vars # A list with names of the categorical ones
)
```

Next, I define the parameters and fit the model:

```
param = {
    # make it a single tree:
    'objective': 'regression',
    'bagging_freq':0,  # Disable bagging
    'feature_fraction':1, # don't randomly select features. consider all.
    'num_trees': 1,
    
    # tuning parameters
    'max_leaves': 10,
    'max_depth': 7,
    'min_data_in_leaf': 1
}

model = lightgbm.train(param, df_train)
```

From the model I extract the leaves of the tree as:

```
tree = model.trees_to_dataframe()[[
'right_child',
    'node_depth',
    'value',
    'count']]

leaves = tree[tree.right_child.isnull()]

print(leaves)

   right_child  node_depth      value  count
3         None           4  30.229624    120
4         None           4  30.698575    154
6         None           4  31.186881     98
7         None           4  31.685297     89
11        None           5  32.134824     51
12        None           5  32.505571     43
13        None           4  33.072456     42
16        None           5  33.596800     19
17        None           5  34.124388     23
18        None           4  35.120717     14
```

Now, if you look at the values, they range from (approximately) `30` to `35`. This is far from capturing the distribution (shown above with `min = 13.75` and `max = 76.75`) of the response variable.  Can anyone explain to me what is going on here? Ultimately, I would like to get as close to decision trees as in the `R` library `rpart`.

**Comment by mlindsk** [comment]
Hi,

Thanks for the details. I've just tried setting the two parameters `'learning_rate':1` and `'min_data_in_bin':1` as you suggested.  You have literally saved my day. It works like a charm.

Regarding `sklearn.tree`, this is not an option. I want a decision tree to honor true splittings of categorical variables. In `sklearn.tree` you have to one-hot encode the categorical ones first or something similar. I'm just transitioning from `R` to `Python` and I was completely baffled that there is no such implementation in `Python`. Several posts discuss this issue (see for example [this kaggle post](https://www.kaggle.com/gabrielaltay/categorical-variables-in-decision-trees) in which they state that only `CatBoost`, `H2o` and `lightgbm` honor the way of splitting categorical values. They also show, that it can have dramatic consequences if one chooses to one-hot encode categorical variables.

With that said, I'm happy with the answer, and you are free to close the question.

**Comment by jameslamb** [comment]
@jmoralez do you use Stack Overflow? This question was double-posted here and to Stack Overflow ([https://stackoverflow.com/questions/71158779/python-decision-tree-in-lightgbm-with-odd-values](https://stackoverflow.com/questions/71158779/python-decision-tree-in-lightgbm-with-odd-values)). If you copy your answer over to there, I'd be happy to mark it as the answer.

------------

@mlindsk we appreciate your interest in `lightgbm` and clear write-up, but please do not post the same LightGBM question to multiple forums. It can lead to duplicate effort. For example, I monitor the `lightgbm` tag on Stack Overflow, and it's possible that I could have seen your Stack Overflow post first and started working on an answer at the same time that @jmoralez  saw your post here and started working on an answer. That would be a bad outcome for the LightGBM project, not just us personally, since we have limited time to spend on maintenance work here.

I'm also requesting that you not do this because, in my experience, we regularly see double-posting where the poster moves on after getting their answer in one place and does not go back to update the other place. That can lead to dead-ends for people facing the same issue in the future who find the unresolved post from search engines.

**Comment by mlindsk** [comment]
@jameslamb Point taken - that was careless of me. I definitely think, that the answer could serve others on Stack Overflow. I would also be happy to mark it as the answer.

**Comment by jameslamb** [comment]
thanks @jmoralez ! No problem, I monitor the `lightgbm` tag there and try to answer when I can.

@mlindsk thanks very much ❤️
