### ISSUE TITLE
to enable bagging, bagging_fraction should be set to value smaller than 1.0

### ISSUE THREAD

**Issue by FatemehTahavori** [microsoft/LightGBM#5072]
If I use the following params and Random forest I am getting:
 LoadError: call to LightGBM's LGBM_BoosterCreate failed: Check failed: config->bagging_freq > 0 && config->bagging_fraction < 1.0f && config->bagging_fraction > 0.0f at /__w/1/s/src/boosting/rf.hpp
  **boosting = "rf"
  bagging_freq = 1
  bagging_fraction = 1
  objective = "binary"
  metric = "average_precision"
  num_class = 1**
  However if I use GBDT boosting, it works fine.
    **boosting = "gbdt"
  bagging_freq = 1
  bagging_fraction = 1
  objective = "binary"
  metric = "average_precision"
  num_class = 1**
  Is this intended? why it works for gbdt?

**Comment by jameslamb** [comment]
👋 thanks for using LightGBM!

Setting `bagging_fraction < 1.0` is required in random forest mode because without it, you wouldn't really be training a random forest. When `boosting_type = rf`, LightGBM does not update gradients between iterations (https://github.com/microsoft/LightGBM/issues/4206#issuecomment-824547988). That means that with `bagging_fraction = 1.0` and `feature_fraction = 1.0` (the defaults), I believe every tree in a LightGBM model trained with `boosting_type = rf` would be identical.

The general random forest algorithm is described at https://www.stat.berkeley.edu/~breiman/RandomForests/cc_home.htm. You can see there that that algorithm prescribes:

* for each tree, train on a random sample (with replacement) of the rows in the training data
* for each tree, train on a randomly-chosen subset of features

LightGBM's random forest mode accomplishes that via `bagging_fraction` and `feature_fraction`.

You may want to see the discussion in #2922 as well for a bit more information.
