### ISSUE TITLE
lightgbm not using all the CPU

### ISSUE THREAD

**Issue by slfan2013** [Microsoft/LightGBM#512]
When using xgboost, I can see my CPU is almost 100% percent, using the default settings of `nthread`.
However, when using lightgbm, my CPU is only ~30%. I tried using the default of `num_threads` and using `num_threads` equals to the 2*#CPU (I have 8 logical processors and 4 Cores thus `num_threads=8`).

Is there anything wrong?

Since my local PC is slow, I tried the google computing engine with 24 CPU and 100G RAM, but still only ~20% of CPU is being used (`num_threads` = 48 this time).

I am working on a typical 200k sample * 200 variables classification problem.

Thanks.

**Comment by guolinke** [comment]
@slfan2013 Did you compile with openmp ?

**Comment by slfan2013** [comment]
@guolinke I guess not.. what is it?

**Comment by guolinke** [comment]
It is the basic multi-threading support in LightGBM. 
How did you compile it?

**Comment by slfan2013** [comment]
I use Windows mostly and sometime use CentOS.
I just ran
`devtools::install_github("Microsoft/LightGBM", subdir = "R-package")` in R.

I thought openmp is only for OSX?

**Comment by guolinke** [comment]
BTW, can you try use a bigger data? and set ```num_leaves``` to a bigger values ?

**Comment by slfan2013** [comment]
I am afraid I don't have a bigger data at hand. I thought 2 million samples is not small. I set `num_leaves=2^5`. Correspondingly, when I use xgboost, I used the same data and `max_depth=5` and xgboost makes my CPU 100% occupied with a 4.2GHz.

**Comment by guolinke** [comment]
@Laurae2 
I found I have the same issue. When I run with R in windows, it only runs by one thread. 
My test data is Bosch, 1M * 1K .

**Comment by Laurae2** [comment]
@guolinke let me check with my server, I'll come back here in about 10 mins to see what is happening

@slfan2013 LightGBM doesn't scale with many threads, you can check this link for Higgs example: https://public.tableau.com/views/gbt_benchmarks/Master-Data?:showVizHome=no

Click on image to see it better:

![image](https://cloud.githubusercontent.com/assets/9083669/26031995/a3348b1c-3887-11e7-9ea4-1f02e90afa61.png)

**Comment by guolinke** [comment]
@Laurae2 The scale in Higgs is because the number of feature in this data is too small (about 28?) .
The multi-threading in LightGBM is based on feature.

**Comment by Laurae2** [comment]
@guolinke Ah, great to know it scales by features and not by rows then.

On Bosch, I am getting 14% CPU usage wth 40 threads, which is expected.

![image](https://cloud.githubusercontent.com/assets/9083669/26032064/2a83ae2a-388a-11e7-91e9-956bee26a654.png)

Tried with both gcc 7.1 (most recent) and gcc 4.9 (default Rtools).

@slfan2013 it is possible for xgboost only if you are using exact method which scales by cores and not by GHz. Fast histogram xgboost scales by GHz and not by cores. See the examples here: https://medium.com/data-design/benchmarking-xgboost-fast-histogram-frequency-versus-cores-many-cores-server-is-bad-8d333e9b0b27

**Comment by guolinke** [comment]
@Laurae2 It takes me full cpu (20 Cores) when running by CLI version, using the same dataset.

**Comment by Laurae2** [comment]
@guolinke Do you have a .conf file so I can try on CLI?

**Comment by guolinke** [comment]
@Laurae2 just set ```num_leaves=255 app=binary data=bosch.train``` .

BTW, I find another strange thing when running by R:

1. one thread will be almost 100 %, when set num_thread=1
2. when set num_thread=2, it will take 2 threads, but each use about 40%.
3. when set num_thread=4, it will take 4 threads, but each use about 20%.
....

**Comment by Laurae2** [comment]
@guolinke 

With `../LightGBM/lightgbm num_leaves=255 app=binary data=bosch.data`, on 40 CPUs (20 cores 40 threads):

* 40 threads: 20% CPU
* 20 threads: 13% CPU
* 10 threads: 9% CPU
* 4 threads: 6% CPU (2 cores busy 80%+, 2 other cores 20%+ only according to htop)
* 2 threads: 4% CPU (cores busy 80%+ according to htop)
* 1 thread: 2% CPU (core busy 100% according to htop)

With my workload (`../LightGBM/lightgbm num_leaves=255 app=binary data=bosch.data learning_rate=0.05 max_depth=12 max_bin=255 min_gain_to_split=1 min_sum_hessian_in_leaf=1 min_data_in_leaf=1 bin_construct_sample_cnt=1183747`), I get 18% CPU usage which is a bit faster than R.

![image](https://cloud.githubusercontent.com/assets/9083669/26032190/6b444f48-388d-11e7-8f3d-2fd75a2351a8.png)

**Comment by guolinke** [comment]
My version:
![image](https://cloud.githubusercontent.com/assets/16040950/26032207/4e2b6bc0-38c0-11e7-9754-4fadb27a3b57.png)

BTW I compile it by vs 2013. Your CLI is compiled by mingw ?

**Comment by Laurae2** [comment]
CLI compiled using MinGW with gcc 7.1.

Can you run LightGBM CLI (yours compiled with with VS 2013) with these params and return me the time taken on your computer for each run?

* `num_leaves=255 app=binary data=bosch.train num_threads=32 num_iterations=200 learning_rate=0.05`
* `num_leaves=255 app=binary data=bosch.train num_threads=16 num_iterations=200 learning_rate=0.05`

**Comment by guolinke** [comment]
@Laurae2 

32 thread:
```
[LightGBM] [Info] Trained a tree with leaves=255 and max_depth=28
[LightGBM] [Info] 178.635229 seconds elapsed, finished iteration 200
[LightGBM] [Info] Finished training
```
16 thread:
```
[LightGBM] [Info] Trained a tree with leaves=255 and max_depth=28
[LightGBM] [Info] 290.485177 seconds elapsed, finished iteration 200
[LightGBM] [Info] Finished training
```

**Comment by Laurae2** [comment]
@guolinke I think it doesn't matter if it uses 100% CPU or 20% CPU, we have approximately the same speed when using all cores.

---

As your CPU runs at 3.3GHz in turbo boost when all cores are used, and mines runs at 2.7GHz (only one generation difference, does not matter much here), if we disregard multithreading overhead:

* You have 52.8GHz raw power (3.3 x 16)
* I have 54GHz raw power (2.7 x 20)

Comparing raw performance on physical cores:

* If I do 287.07s with all 20 physical cores, then you should do 293.59s on all your 16 physical cores
* You do 290.48s, which is expected

Hyperthreading is supposed to add about from 15% to 50% performance with a zero overhead:

* Your hyperthreading is really good (+62% performance)
* My hyperthreading is poor (+20% performance)

---

I locked my machine with 16 physical cores and 32 threads. I get this:

* 16 threads: 308.27s
* 32 threads: 204.62s

I have poor hyperthreading when there is a medium overhead, this is because I use virtualization. I saw the same behavior with xgboost (comparing with baremetal servers). Only small overhead (like Cinebench R15) is not tearing down hyperthreading performance when virtualized.

**Comment by guolinke** [comment]
@slfan2013 did you have the speed-up when num_thread is set to large number ?

@Laurae2 if the speed is comparable, what is problem ? The measure error of GPU ?  But the xgboost with R in slfan2013 can take 100% CPU. (BTW, xgboost also can take 100% in your machine ?)

**Comment by Laurae2** [comment]
@guolinke xgboost exact can easily take 100% CPU if data is large enough (does not need that big, but with many cores it needs bigger datasets), the fast histogram xgboost will not take 100% (even if data is 1 billion rows, will not reach 100%). I saturate nearly all my 40 threads with xgboost exact on Bosch:

![image](https://cloud.githubusercontent.com/assets/9083669/26032576/07323b96-3897-11e7-9dc1-3c94ca1c87c2.png)

I get 100% very easily with exact xgboost if using less threads. Fast histogram xgboost cannot.

I do not know the reason why Visual Studio is showing 100% and MinGW / gcc is not showing 100%. However, at full load, the load (Watts) at the wall does not change (I tried on a 8 core i7-5960X last week) between LightGBM with VS or MinGW/gcc.

When comparing with exact xgboost, I am using 50% more watts at the wall. Potentially, one of these hypotheses is wrong:
* VS compilation leads to instructions unintentionally overstating CPU usage (100% CPU usage in my scenario) <= I expect the CPU usage to be wrong in this one, this should be the right hypothesis
* MinGW compilation leads to instructions unintentionally understating CPU usage (30% CPU usage in my scenario) <= I expect this is the wrong hypothesis

Because with htop on the host machine, the reported CPU usage is nearly identical to the virtual machine, and energy usage is identical at the wall.

**Comment by slfan2013** [comment]
Hi @Laurae2 
I have two machines. One is Windows 10, 4 Cores 32G RAM and one is CentOS 24Cores 100G RAM.
For windows, the lightgbm speed is much faster than xgboost, even CPU is only ~30% being used for lightgbm, while xgboost using 100%.
For centOS, the lightgbm speed is equal with xgboost. Lightgbm also only take ~ 20% of CPU while xgbost takes 80%.

What I worry the most is that the lightgbm in CentOS (24Cores) is **NOT** faster (some cross validation folds were even slower) than my local PC (4Cores).

**Comment by Laurae2** [comment]
@slfan2013 24 cores (48 threads) is way too much for 200 observations x 200 features (you should have negative scaling). As you have 100GB RAM, use less threads and parallelize cross-validation. For instance, if you do 6 fold CV, it is better to do:

* Parallelized cross-validation over folds
* 8 threads per fold for training

This would mean the 6 folds are trained at the same time, while each only using each 8 threads. This would make use of the CPU better than using a sequential training of 48 threads.

Check this for the explanation (it uses fast histogram xgboost, which is similar to LightGBM): https://medium.com/data-design/benchmarking-new-xgboost-fast-histogram-xgboost-and-the-compiler-story-86f0c5a4bcd3

> Clearly, going over 1 thread is already providing a poor ROI (return on investment, but applied to CPU threads). For instance, on i7–7700K, you better do a 4-fold cross-validation using a parallelized cross-validation:
> Parallelized cross-validation: less than 5 minutes for doing 4 parallel trainings using 1 thread each.
Sequential cross-validation: about 12 minutes for doing a training one by one using 3 threads each (assuming you found out the sweet spot).

because adding more threads is not linearly scaling.

**Comment by slfan2013** [comment]
Gotcha. Helpful!

**Comment by Laurae2** [comment]
@guolinke should we add a warning on the docs about CPU usage when not using VS?

**Comment by Laurae2** [comment]
@slfan2013 is the problem solved in your case? (you can close if yes)

**Comment by slfan2013** [comment]
Yes. Thanks!

I think I should carefully select instance configuration in the google compute engine (or other computing cloud) when using `lightgbm`, because it does not use all of the CPU and won't speedup for more CPUs.
