### ISSUE TITLE
Save model on every iteration

### ISSUE THREAD

**Issue by Qashqay** [microsoft/LightGBM#5178]
Hello,

Is it possible to save intermediate model on every boosting iteration with the standard `train` function?
For example:
```
params  = {'num_leaves': 10, 'objective': 'rmse', 'save_freq': 1, 'save_path': '/tmp/'}
model = train(params, data)
```
and in `/tmp/` we will have 10 files with identical to `model.save_model('/tmp/model.txt')` format.

Thank you

**Comment by jmoralez** [comment]
Hello @Qashqay, thank you for your interest in LightGBM. This isn't implemented in the library but since there are callbacks this is very easy to achieve if you implement your own callback. Every callback takes a [`CallbackEnv`](https://github.com/microsoft/LightGBM/blob/56ccea4243aba4c538ebca9de8c67ee0c9bc60eb/python-package/lightgbm/callback.py#L34-L41) as argument, so you can use something like the following:
```python
import lightgbm as lgb
import numpy as np

def save_model_callback(env):
    env.model.save_model(f'booster_{env.iteration}.txt')

ds = lgb.Dataset(np.random.rand(100, 2), np.random.rand(100))
model = lgb.train({'num_leaves': 10}, ds, num_boost_round=5, callbacks=[save_model_callback])
```
After running this you should see 5 files in your current directory (one for each iteration). You can modify the logic of that function to only save every *x* iterations or saving to a different path.

Please let us know if this helps.

**Comment by jmoralez** [comment]
Great. I'm closing this issue but feel free to reopen if you run into some problem using this.

**Comment by gaebw** [comment]
running on windows 10: 
Name: lightgbm
Version: 3.1.1
Summary: LightGBM Python Package
Home-page: https://github.com/microsoft/LightGBM
Author: None
Author-email: None
License: The MIT License (Microsoft)
Location: c:\users\info\anaconda3\lib\site-packages
Requires: scipy, scikit-learn, wheel, numpy

tried above code:
import lightgbm as lgb
import numpy as np

def save_model_callback(env):
    env.model.save_model(f'booster_{env.iteration}.txt')

ds = lgb.Dataset(np.random.rand(100, 2), np.random.rand(100))
model = lgb.train({'num_leaves': 10}, ds, num_boost_round=5, callbacks=[save_model_callback])

Error:
AttributeError: function 'LGBM_DumpParamAliases' not found

**Comment by gaebw** [comment]
On ubuntu it works!

**Comment by jameslamb** [comment]
@gaebw `LGBM_DumpParamAliases` was introduced December 2, 2021 (#4829), so it's very surprising to see an error message about it given that you said you are using v3.1.1 ([October 27, 2021](https://github.com/microsoft/LightGBM/releases/tag/v3.3.1)).

I suspect that maybe you've built a newer version of the Python code (using `python setup.py install --precompile`) but linking to an older version of `lib_lightgbm.so`.

Please try building `lightgbm`'s development version from the source code on GitHub, following the steps at https://github.com/microsoft/LightGBM/releases/tag/v3.3.1.
