### ISSUE TITLE
'-1' in category feature

### ISSUE THREAD

**Issue by jodyfatty** [microsoft/LightGBM#5206]
Hi, I am a beginner in machine learning and trying use LightGBM. I know lightgbm can handle category feature and try the code showed below
```
x_train_lgb = x_train.copy()
x_test_lgb = x_test.copy()
y_train_lgb = y_train.copy()

cate = list((x_train_lgb.select_dtypes('object').columns))
for name in cate:
    encoder = LabelEncoder()
    encoder.fit(list(x_train_lgb[name].values))
    x_train_lgb[name] = encoder.transform(list(x_train_lgb[name].values))

lgb_model = lgb.LGBMClassifier(seed = 42).fit(x_train_lgb, y_train_lgb, categorical_feature = cate)
lgb_model.booster_.dump_model()
```

I use `sklearn.preprocessing.LabelEncoder()` to convert `str` into `int` with value start from 0. I use sklearnAPI of lightlgb and set `categorical_feature = cate` in fit method. After bulid the model,  I use `lgb_model.booster_.dump_model()` to check the structure.
I see for every category feature there is one more category '-1' (like   'swimming': {'min_value': -1, 'max_value': 1, 'values': [-1, 0, 1]})

![1t](https://user-images.githubusercontent.com/49807732/167562933-59f5d384-6226-410e-86b1-19c62a835a1e.jpg)

Could anyone teach me the meaning of this '-1'?

**Comment by jmoralez** [comment]
Hi @jodyfatty, thank you for your interest in LightGBM. As you may know when using categorical features LightGBM uses integer codes starting from zero to represent them and makes splits like `school_assessment == 1||4`. The `-1` there is used to represent missing values (since the minimum feature value is zero). If you take your trained model and use either `-1` or `np.nan` as the value for a categorical feature you should see the exact same prediction.

Please let us know if this helps.

**Comment by jodyfatty** [comment]
@jmoralez  thank you!
