### ISSUE TITLE
Fit support for categorical features

### ISSUE THREAD

**Issue by lcrmorin** [microsoft/LightGBM#5218]
There already seems to be some discussion about the topic but it is unclear what the approach should be for categorical features. I am trying to use the python .fit approach with dataframe instead of lgbm datasets. 

Feeding objet will give an error: "DataFrame.dtypes for data must be int, float or bool.
Did not expect the data types in the following fields: workclass, education, marital-status, occupation, relationship, race, gender, native-country" (Adult Data Set).

So I just converted the object columns to integers:

```
features_object = data.dtypes[data.dtypes == object].index
data.loc[:,features_object] = data[features_object].apply(lambda col:pd.Categorical(col).codes)
```

Now the lgbm seems to learn well without needing to specify the categorical_feature option of the fit function.

1) Can you calrify if there is a need to specify the categorical_features if I already converted them to integers ?

Convertly, if I only input categorical features name without having them converted to integers, it throws the same error about data types. I honestly expected to be handled internally if I give the name of the categorical features.

2) Wouldn't it be better for categorical variables to be handled when specifying the categorical_features option in the fit function ?

**Comment by jmoralez** [comment]
Hi @lcrmorin. Quoting the [docs](https://lightgbm.readthedocs.io/en/latest/Parameters.html#categorical_feature):

> Note: all values will be cast to int32 (integer codes will be extracted from pandas categoricals in the Python-package)

So if you are training with a pandas dataframe the easiest way to tell LightGBM that you want to use some features as categorical is to set them to categorical data type, i.e. `df['cat_col'] = df['cat_col'].astype('category')`. This way when you call `fit` LightGBM will automatically extract the codes from that column and treat it as categorical.

If you don't set them to that datatype but want to use them as categorical you can do so by setting the `categorical_feature` argument either to the index or the name of the feature. This however requires that the columns can be cast to integers, i.e. they can have a floating point data type but must be integers `([1.0, 2.0, 5.0])`.

> Can you calrify if there is a need to specify the categorical_features if I already converted them to integers ?

This is indeed necessary because on the C++ side LightGBM gets a single array that is either `float32` or `float64` so it doesn't know which columns were integers, thus the need for the `categorical_feature` argument. If you don't specify it what will happen is that LightGBM will treat that column as continuous instead of categorical.

Please let us know if you have further doubts.

**Comment by lcrmorin** [comment]
Ok, thanks @jmoralez. If I understand correctly the general solution is something like:

```
cat_cols = data.dtypes[data.dtypes == object].index
data.loc[:,cat_cols] = data[cat_cols].astype('category')
```

Then fit will handle this automatically (or use lgb datasets).

**Comment by jmoralez** [comment]
Yes, that's the easiest way. Keep in mind that this works for `lgb.Dataset` as well:
```python
import lightgbm as lgb
import numpy as np
import pandas as pd

df = pd.DataFrame({'x': np.random.choice(['a', 'b'], 100)}, dtype='category')
ds = lgb.Dataset(df).construct()
ds.pandas_categorical
# [['a', 'b']]
```
