### ISSUE TITLE
[Bug] Null bin mapper error in dataset_loader.cpp

### ISSUE THREAD

**Issue by vollis** [microsoft/LightGBM#5221]
See line in bold and italic. The bin mapper could be nullptr.
if (bin_mappers.size() < 1024) {
    for (size_t i = 0; i < bin_mappers.size(); ++i) {
      const int max_bin_for_this_feature = max_bin_by_feature.empty() ? max_bin : max_bin_by_feature[i];
      _**if (bin_mappers[i]->bin_type() == BinType::CategoricalBin && bin_mappers[i]->num_bin() > max_bin_for_this_feature) {**_
        need_warning = true;
        break;
      }
    }
  }

**Comment by vollis** [comment]
It would be null for example, when the 0 column is query id

**Comment by jameslamb** [comment]
Thanks for your interest in LightGBM!

In the future, links to code instead of copied snippets would be greatly appreciated. In case you are new to GitHub, you might find this documentation useful: https://docs.github.com/en/repositories/working-with-files/using-files/getting-permanent-links-to-files.

I believe I found the code you're talking about.

https://github.com/microsoft/LightGBM/blob/c000b8cc689a9b3ee8bf4f294749d2f848f7176f/src/io/dataset_loader.cpp#L1472-L1479

Looks like that code was added in #4448.

We need some more information from you to help with this.

What is the specific issue you've observed? For example...an error, a segmentation fault, silently-incorrect behavior, etc.?

Are you able to provide a [minimal, reproducible example](https://stackoverflow.com/help/minimal-reproducible-example) hitting this condition?

**Comment by vollis** [comment]
Sorry, I can't provide an example. But I think the bug is pretty straightforward for someone who is familiar with dataset_loader.
@shiyu1994 I think shiyu did a similar fix in #5146

**Comment by jameslamb** [comment]
> I can't provide an example

How did you discover the issue you're reporting, which you believe to be a bug?

Without an example and more details, it's very difficult for maintainers here to:

1. the impact of this behavior and how likely it is that users will encounter it
2. write a test that will prevent such a bug from being reintroduced in the future

Are you at least able to answer the other question I asked, about what the result of this behavior is?

> ..an error, a segmentation fault, silently-incorrect behavior, etc.?
