### ISSUE TITLE
'LGBMRegressor' object has no attribute 'n_estimators_'

### ISSUE THREAD

**Issue by phantng** [microsoft/LightGBM#5337]
## Description

The 'LGBMRegressor' object has no attribute 'n_estimators_' but it does have 'n_estimators', which is inconsistent with the documentation in [https://lightgbm.readthedocs.io/en/latest/pythonapi/lightgbm.LGBMRegressor.html](url).

## Reproducible example
```
model = lgb.LGBMRegressor(**model_config)
model = model.fit(x_train, y_train)
...
print(model.n_estimators_)
```
## Environment info
lightgbm=3.3.2
python=3.9.7

**Comment by nguyenlnc1** [comment]
Got it, thanks for the reply!

**Comment by jmoralez** [comment]
@jameslamb @StrikerRUS can we make the default page be the latest release (3.3.2 in this case) instead of the current master on readthedocs? It can be very confusing finding things that aren't there yet and getting errors, and we've had a couple of issues because of it (#5113 comes to mind but I think we've had some more).

**Comment by jameslamb** [comment]
Thanks for bringing it up @jmoralez . I have been meaning to open an issue about that since #5185, your `@` reminded me to do it. Created #5342 . Let's move the discussion about what to do with the docs site over there.

Based on the 👍 from @phantng on https://github.com/microsoft/LightGBM/issues/5337#issuecomment-1170092678, I'm going to close this issue.
