### ISSUE TITLE
LightGBMError: Cannot change bin_construct_sample_cnt after constructed Dataset handle.

### ISSUE THREAD

**Issue by MRzcs10** [microsoft/LightGBM#5411]
[question.zip](https://github.com/microsoft/LightGBM/files/9292440/question.zip)

**Comment by jameslamb** [comment]
Thanks for using LightGBM!

But please replace `question.zip` with a description, in plain text, of the issue you're facing.

I won't download and open ZIP archives attached to issues here, since it's possible to use such a file for malicious purposes (e.g. https://en.wikipedia.org/wiki/Zip_bomb).

Putting your question into plain text will also allow search engines to find it, so that other people facing the issue you're facing can find this discussion and benefit from it.

**Comment by jmoralez** [comment]
Also this comment explains the possible problem and has a solution: https://github.com/microsoft/LightGBM/issues/4019#issuecomment-785124299
