### ISSUE TITLE
face verification

### ISSUE THREAD

**Issue by kingvision** [Microsoft/LightGBM#55]
Hi:
    After extracting face region high dimensional LBP feature, can  I use LightGBM further select features, used for face verification? Can you give some advice or examples?
    thanks

**Comment by chivee** [comment]
hi @kingvision , it is hard to understand your task since we don't have much experience on face verification. but I think that can be done as following:

1. Making LBP feature readable for LightGBM
2. Define objective function for face verification( classification to my understanding).
3. Training & read the model file to select features.

**Comment by chivee** [comment]
feel free to reopen if issues still there
