### ISSUE TITLE
Is it possible to train estimator for 1500 classes?

### ISSUE THREAD

**Issue by FiksII** [microsoft/LightGBM#5583]
Hi. I have tabular sparse ~~(but it does not matter, because LightGBM does not use it natively)~~ dataset 7M * 340 and 1500 classes. In the preparation stage (before training iterations) LightGBM consumes all my memory 128 Gb and fails. Is it possible to do it without increasing memory?

LightGBM version '3.3.3'
Python 3.9

Code to reproduce:
```
import lightgbm
from sklearn import datasets
from sklearn.model_selection import train_test_split

X, y = datasets.make_classification(n_samples=int(7e6), n_features=30, n_informative=30, n_redundant=0, 
                                                n_classes=1500)
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.1, random_state=42)                                                

classifier = lightgbm.LGBMClassifier(n_estimators=5000, num_leaves=128, learning_rate=0.1)
classifier.fit(X_train, y_train, eval_set=[(X_test, y_test)], 
                   eval_metric='logloss', callbacks=[lightgbm.log_evaluation(), lightgbm.early_stopping(50)]) # This consumes all memory
```

Training log:
```
[LightGBM] [Debug] Dataset::GetMultiBinFromAllFeatures: sparse rate 0.000000
[LightGBM] [Debug] init for col-wise cost 0.000838 seconds, init for row-wise cost 0.328462 seconds
[LightGBM] [Warning] Auto-choosing col-wise multi-threading, the overhead of testing was 0.398092 seconds.
You can set `force_col_wise=true` to remove the overhead.
[LightGBM] [Info] Total Bins 7650
[LightGBM] [Info] Number of data points in the train set: 6300000, number of used features: 30
```

**Comment by jameslamb** [comment]
> In the preparation stage (before training iterations) LightGBM consumes all my memory 128 Gb and fails

Are you able to provide ? You haven't provided some important information that we ask for in the issue template, including:

* version of LightGBM you're using
* how you installed LightGBM
* how you're using LigthGBM (Python package? R package? CLI?)
* a [minimal, reproducible example](https://stackoverflow.com/help/minimal-reproducible-example), code that demonstrates this issue

Providing those details would allow us to provide a higher-quality answer. Otherwise, you are asking maintainers here to guess at what might be leading to the situation you've described.

-------

> I have tabular sparse (but it does not matter, because LightGBM does not use it natively)

What does this comment mean? Could you please rephrase it? What specifically are you saying LightGBM "does not use" and what do you mean by "natively"?

-------

> is it possible to train ... [with] 1500 classes?

Yes, it is. But please keep in mind... in multiclass classification, LightGBM will train  `{number of classes}` trees on every iteration. So, for example, for `num_iterations = 10` and 1500 classes LightGBM might produce a model with 15,000 trees. That can lead to high memory usage pretty quickly.

I understand that you said you're running into memory issue "before training" so maybe that is not relevant to the issue you're currently facing, but just noting it in case I've misunderstood your brief description.

**Comment by FiksII** [comment]
@jameslamb 
Sorry for the incorrect post. I edited the post and added the necessary information.

> What does this comment mean? Could you please rephrase it? What specifically are you saying LightGBM "does not use" and what do you mean by "natively"?

Sorry, if I am wrong. But, I thought LightGBM converts the sparse matrix to dense.

**Comment by jameslamb** [comment]
> Sorry for the incorrect post.

Thanks for adding those details! They're very helpful in seeing what's going on.

Can you provide some logs to help us understand what you mean by "In the preparation stage (before training iterations) LightGBM ... fails"? That would help us to narrow down where in the code for `LGBMClassifier.fit()` you are running out of memory.

--------

> I thought LightGBM converts the sparse matrix to dense. I was wrong

No problem, just wanted to be sure I understood! Yes, LightGBM directly supports several types of sparse inputs, and can directly create a LightGBM `Dataset` from such inputs without ever creating a corresponding dense representation.

**Comment by FiksII** [comment]
@jameslamb 

It crashes here https://github.com/microsoft/LightGBM/blob/master/python-package/lightgbm/basic.py#L2780

```
            _safe_call(_LIB.LGBM_BoosterCreate(
                train_set.handle,
                c_str(params_str),
                ctypes.byref(self.handle)))
```

**Comment by jameslamb** [comment]
@FiksII can you please provide the logs as requested in https://github.com/microsoft/LightGBM/issues/5583#issuecomment-1313095448? I appreciate you those links to the Python code, but that is calling underlying C/C++ code. Seeing the exact logs would be helpful.

**Comment by FiksII** [comment]
@jameslamb Added log at 1st post. But, there is nothing special there

**Comment by jameslamb** [comment]
The last line in that log you've added in the original post is an INFO-level log from Dataset construction. When you said "it fails", I expected to see some error message. Does that not happen for you? Does "it fails" just mean the training process dies without producing any additional output?

**Comment by jameslamb** [comment]
Alright thanks. The fact that you're working in a Jupyter notebook is new and useful information as well, as that can change how to interpret some failure modes in Python code.

Given what you've provided, I think that you simply don't have enough available memory for LightGBM to accomplish the task you're asking it to.

<hr>

## Memory requirements for this type of model

As I mentioned in https://github.com/microsoft/LightGBM/issues/5583#issuecomment-1313056893, LightGBM multiclass classification generates one tree per class per iteration.

So with the following parameters:

```text
n_estimators = 5000
n_classes = 1500
num_leaves = 128
```

If early stopping isn't triggered, you're asking LightGBM to train 7.5 million trees, each of which could have up to 128 leaf nodes.

<hr>

## Things you can do to try to try to train a LightGBM model with this dataset on your current machine

**Kill any other non-critical processes running on the machine**

Try to give LightGBM as much of your machine's RAM as possible. For example, close web browsers, messaging clients, and anything else not necessary for LightGBM.

**Train a smaller model**

* reduce `num_leaves`
* reduce `n_estimators`
* increase `min_data_in_leaf` or `min_gain_to_split`
* combine classes so that there are fewer total `n_classes`
* reduce the number of early stopping rounds

**Don't use the scikit-learn interface**

LightGBM has its own data representation, `lgb.Dataset`, that requires much less memory than the corresponding dense matrices in e.g. `numpy` or `pandas` format.

You might find that you can reduce the peak memory usage of LightGBM training by constructing those, removing the 2 copies of the data in `numpy` format from memory, and using the non-`scikit-learn` interface. Like this:

```python
import lightgbm as lgb
from sklearn import datasets
from sklearn.model_selection import train_test_split

X, y = datasets.make_classification(
    n_samples=int(7e6),
    n_features=30,
    n_informative=30,
    n_redundant=0, 
    n_classes=1500
)
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.1, random_state=42)

# construct lightgbm Datasets
dtrain = lgb.Dataset(data=X_train, label=y_train, free_raw_data=True)
dtrain.construct()

dvalid = lgb.Dataset(data=X_test, label=y_test, free_raw_data=True)
dtrain.construct()

# remove the raw data
del X, y, X_train, y_train, X_test, y_test

# train
classifier = lgb.train(
    train_set=dtrain,
    params={
        "n_estimators": 1,
        "num_leaves": 128,
        "learning_rate": 0.1,
        "objective": "multiclass",
        "num_classes": 1500
    },
    valid_sets = [dvalid],
    valid_names = ["validation_set"],
    callbacks = [
        lgb.log_evaluation(),
        lgb.early_stopping(50)
    ]
)
```

**Comment by jameslamb** [comment]
Also linking the related discussion #4239.

@guolinke @shiyu1994 tagging you in case I've said anything incorrect or you have anything else you'd like to add.

**Comment by FiksII** [comment]
Thank you. Will try

**Comment by FiksII** [comment]
@jameslamb Yes... the same thing with your code:

```
UserWarning: Found `n_estimators` in params. Will use it instead of argument
  _log_warning(f"Found `{alias}` in params. Will use it instead of argument")
[LightGBM] [Warning] Auto-choosing col-wise multi-threading, the overhead of testing was 0.399564 seconds.
You can set `force_col_wise=true` to remove the overhead.
[LightGBM] [Info] Total Bins 7650
[LightGBM] [Info] Number of data points in the train set: 6300000, number of used features: 30
[1]    904837 killed     ipython
```

**Comment by jameslamb** [comment]
I cannot say with confidence "you definitely should be able to train a 1500-class, 5000-iteration multiclass classification model with 128GB RAM". It's possible that LightGBM simply can't do what you're asking with the physical resources available in your environment.

One other thing you could try... install the development version of `lightgbm` (the Python library for LightGBM). It's been more than a year since the last substantative release, it's possible that some combination of efficiency improvements and bugfixes in that year of development could allow you to successfully train this model.

Instructions: https://github.com/microsoft/LightGBM/tree/master/python-package#install-from-github

<hr>

Just want to set the right expectation...if you or anyone else reading this thread investigates this further and are able to identify a specific point in the code where there is an opportunity to reduce LightGBM's memory usage for this type of machine learning task please do share it! But at this point I personally am not planning to spend more time investigating this.
