### ISSUE TITLE
OSError: dlopen: cannot load any more object with static TLS

### ISSUE THREAD

**Issue by 18811449050** [microsoft/LightGBM#5584]
## Description

`import lightgbm` then Error : `OSError: dlopen: cannot load any more object with static TLS` occured.
## Reproducible example

`import lightgbm`
## Environment info

LightGBM version or commit hash:
- lightgbm 3.3.3
- lightgbm 3.3.2
- lightgbm 3.2.1
Command(s) you used to install LightGBM

```shell
`pip install lightgbm` or `conda install lightgbm`
```

![image](https://user-images.githubusercontent.com/64057896/201524265-e8e2746e-f13d-4d66-a063-323059b3d3cd.png)

**Comment by jameslamb** [comment]
Thanks for using LightGBM and for reporting this!

Unfortunately, this issue is not unique to LightGBM, and should not occur on Linux systems with `GLIBC >= 2.21`. You can read more about it at the links here:

* https://github.com/microsoft/LightGBM/pull/4893#issuecomment-1039204806
* https://github.com/microsoft/LightGBM/issues/5390#issuecomment-1203495465

Here are some things you can try to work around this

* if possible, switch to a newer Linux distribution with `GLIBC >= 2.23`
    - you can figure out the version by running `ldd --version`, see the description of #5514 for an example
* try changing versions of `scipy`, `numpy`, or `scikit-learn`
* if you have `dask` and `distributed` in that `conda` environment but don't need them, `conda uninstall` them (so they won't be loaded when importing `lightgbm`)
* try installing `lightgbm` without OpenMP support
    - see https://github.com/microsoft/LightGBM/tree/master/python-package#build-threadless-version
    - ⚠️ this version of LightGBM will be **much** slower in most settings ⚠️
