### ISSUE TITLE
Order of the features affects predictions?

### ISSUE THREAD

**Issue by chrysa-r** [microsoft/LightGBM#5664]
I am using LighGBM Classifier and Regressor and it seems that the order of the features I am adding, affect the predictions of the model. Everytime I change the order, another result comes up and with a big difference from the previous one. Is there a way to handle this issue? Thank you!

**Comment by jameslamb** [comment]
Thanks for using LightGBM!

I'm not exactly sure what you mean by "...the order of features affects the predictions".

With LightGBM's default settings, across all of it's official interfaces...

* **training**: shuffling the feature order should not have any impact on the predicted scores
* **scoring**: the order of the features must match the order from training

LightGBM stores information about the features by positional index, and you need to present data at scoring time with all the same features from training, in the same order.

There are some exceptions to this, for example the optional `validate_features` configuration if using `pandas` DataFrames in the Python package (see https://github.com/microsoft/LightGBM/issues/5627#issuecomment-1357892604 for example).

If you want more specific help, please provide the things that we asked for in the issue template when you clicked `New Issue`, including:

* version of LightGBM you're using
* how you're using LightGBM (R package? Python package? CLI?)
* a [minimal, reproducible example](https://stackoverflow.com/help/minimal-reproducible-example) showing what you ran, and describing the difference between what happened and what you expected to happen

-------

Also...I see that you double-posted this here and on Stack Overflow ([link](https://stackoverflow.com/questions/75025304/why-the-order-of-the-features-affects-lightgbm-predictions)). Please do not do that. Maintainers here also monitor the `[lightgbm]` tag on Stack Overflow. I could have been spending time preparing an answer here while another maintainer was spending time answering your Stack Overflow post, which would have been a waste of maintainers' limited attention that could otherwise have been spent improving this project. Double-posting also makes it less likely that others with a similar question will find the relevant discussion and answer.

**Comment by squangelo** [comment]
> you need to present data at scoring time with all the same features from training, in the same order.

Just commenting because i ran in the same issue and can probably clarify the problem the user was having. While LightGBM explicitly checks for number of features (raising a `ValueError: Number of features of the model must match the input`), if the user was not careful about the features order the model prediction will be wrong.

This happened to me because I had sorted my features by importance and mistakenly used `predict` on the dataframe passing the sorted list instead of the original features. Appreciate the new `validate_features` arg to protect against this!
