### ISSUE TITLE
plot tree with high cardinality feature

### ISSUE THREAD

**Issue by moziada** [microsoft/LightGBM#5687]
When I try to plot a tree that splits on a feature with high cardinality the overall diagram gets missed up no matter how I tried to adjust the width and height
![out](https://user-images.githubusercontent.com/60968402/215163488-bb4da6a8-ef6b-452c-bd36-0e883af60992.png)
There must be a way to ignore writing all the values that are used on the split within the nodes

**Comment by jmoralez** [comment]
Hi @moziada, thanks for using LightGBM. I think a possible solution would be to check the number of categories in the split and if there are too many we should collapse them and show them in the [tooltip](https://graphviz.org/docs/attrs/tooltip/) instead, which would look like this:
![Screenshot from 2023-02-12 16-30-37](https://user-images.githubusercontent.com/8473587/218341359-f61b53cf-dc77-4817-931a-cafe73a918f1.png)
The problem is that at least for me (firefox + jupyterlab) the graph isn't automatically shown as SVG, so I had to save it first and then load it and show as HTML which is cumbersome. We should find a way to display it as SVG by default, I can look into that later, or if you're interested you can investigate and contribute the change yourself. The logic for showing it in the tooltip is very simple, here's a sample diff:
```diff
diff --git a/python-package/lightgbm/plotting.py b/python-package/lightgbm/plotting.py
index d2a57209..87c287c0 100644
--- a/python-package/lightgbm/plotting.py
+++ b/python-package/lightgbm/plotting.py
@@ -493,7 +493,13 @@ def _to_graphviz(
                     direction = _determine_direction_for_numeric_split(
                         example_case[split_feature], root['threshold'], root['missing_type'], root['default_left']
                     )
-            label += f"<B>{_float2str(root['threshold'], precision)}</B>"
+            if is_categorical_split and len(root['threshold'].split('||')) > 5:
+                threshold = '...'
+                tooltip = root['threshold']
+            else:
+                threshold = root['threshold']
+                tooltip = None
+            label += f"<B>{_float2str(threshold, precision)}</B>"
             for info in ['split_gain', 'internal_value', 'internal_weight', "internal_count", "data_percentage"]:
                 if info in show_info:
                     output = info.split('_')[-1]
@@ -525,7 +531,8 @@ def _to_graphviz(
             if "data_percentage" in show_info:
                 label += f"<br/>{_float2str(root['leaf_count'] / total_count * 100, 2)}% of data"
             label = f"<{label}>"
-        graph.node(name, label=label, shape=shape, style=style, fillcolor=fillcolor, color=color, penwidth=penwidth)
+            tooltip = None
+        graph.node(name, label=label, shape=shape, style=style, fillcolor=fillcolor, color=color, penwidth=penwidth, tooltip=tooltip)
         if parent is not None:
             graph.edge(parent, name, decision, color=color, penwidth=penwidth)
```

**Comment by moziada** [comment]
Hey @jameslamb sorry I did not receive your response earlier, I will look into it and try to make a contribution.
I will keep you with any updates

**Comment by moziada** [comment]
After searching I have found that this is a common issue with JupyterLab and people have opened issues on it (like this [issuse](https://github.com/jupyterlab/jupyterlab/issues/7497)).
The workaround to display svg images on JupyterLab is to wrap the svg image content with ```IPython.display.HTML``` then the tooltip works properly
![JupyterLab](https://user-images.githubusercontent.com/60968402/227783393-52210b7d-82fa-4bcc-ab48-02488a4a2728.png)

Also I have tested the tooltip on Jupyter Notebook it works fine no workarounds are needed
![Jupyter Notebook](https://user-images.githubusercontent.com/60968402/227783726-89e50be1-237a-4f41-babe-3fb8a2446a43.png)
Both screenshots are taken on Firefox browser

**Comment by moziada** [comment]
@jmoralez sorry I forgot to mention you with my results

**Comment by moziada** [comment]
Sure I am working on a PR

**Comment by moziada** [comment]
I am having difficulties on testing the changes I have made, is there any systematic way to make changes and install the new version to the current python environment?

**Comment by jameslamb** [comment]
Since you're only touching Python code, compile the library just one time by running the following from the root of the repo.

```shell
rm -r ./build
mkdir ./build
cd ./build
cmake ..
make -j2
```

Then every time you change the Python package, run this from the root of the repo.

```shell
cd ./python-package
python setup.py install --precompile
```

Then every time you want to run the tests, point `pytest` at any of the ddirectories and files in the `tests` directory. For example, by runming the following from the root of the repo.

```shell
pytest tests/python_package_test/test_plotting.py
```

**Comment by moziada** [comment]
I have made the changes but I noticed that all ```.rst``` doc pages under [Plotting](https://lightgbm.readthedocs.io/en/latest/Python-API.html#plotting) section are not available on github

**Comment by jameslamb** [comment]
That page is automatically generared from the docstrings in `python-package/lightgbm/plotting.py`.

**Comment by jmoralez** [comment]
You can also render the docs locally following [this](https://lightgbm.readthedocs.io/en/v3.3.2/README.html#build).
