### ISSUE TITLE
c_api does not support continued train or incremental training?

### ISSUE THREAD

**Issue by MrRace** [microsoft/LightGBM#5717]
From

https://github.com/microsoft/LightGBM/blob/7fd708df780582dcd016c696a97803dac7aefd88/src/c_api.cpp#L119-L122

it seems does not support incremental training? Why？

Intuitively the continued train  in c_api is required, for  example deploy lightgbm on device and do incremental training.

**Comment by guolinke** [comment]
That is because you can implement it by predicting the init_score by  init_model first, then using the init_score.
The python-package also calls the c_api by this way, refer to https://github.com/microsoft/LightGBM/blob/ad487fee57945f45041ff21038dfeaaee4e10e52/python-package/lightgbm/basic.py#L1880-L1887
