### ISSUE TITLE
Conan installation support

### ISSUE THREAD

**Issue by barynton** [microsoft/LightGBM#5770]
## Summary

It would be nice to have supported conan installation option

## Motivation

Package management is convenient

## Description

0) Add conan package to installation options
1) There's a conan package available on https://conan.io/center/lightgbm. But it contains only basic functionality. There's no support of GPU or CUDA f.e. The options can be added to the conan recipe.
2) The conan recipe contains git patches. It would be nice to apply it permanently:

- https://github.com/conan-io/conan-center-index/blob/master/recipes/lightgbm/all/patches/0001-fix-includes.patch
- https://github.com/conan-io/conan-center-index/blob/master/recipes/lightgbm/all/patches/0002-fix-openmp-clang.patch

## References
https://docs.conan.io/2/
https://conan.io/center/

**Comment by jameslamb** [comment]
Thanks for using LightGBM.

I'm not very familiar with Conan, but it seems to me that LightGBM is already supported there (e.g. based on what I see in https://github.com/conan-io/conan-center-index/pull/16412).

I've added this to #2302 (where we group all future requests) and will close this as I personally am not planning to work on it and don't expect any other maintainers in the project to work on it in the near future. Our policy in this project it to track feature requests in #2302 and only open the corresponding GitHub issues when someone is actively working on that feature.

I've also changed the title of this issue to more accurately reflect what's being asked for (as I understand it).

Since you're familiar with that package manager, the fastest way to accomplish changes to its repackaging of LightGBM is probably for you to make those changes yourself. You're welcome to use comments here to ask questions about how LightGBM builds work, if you need help.
