### ISSUE TITLE
[RFC] Drop support for CUDA 10

### ISSUE THREAD

**Issue by shiyu1994** [microsoft/LightGBM#5789]
## Summary

CUDA 10 is very old. And with CUDA 10 we found some compilation problems that do not occur in CUDA 11. See (https://github.com/microsoft/LightGBM/pull/5605#issuecomment-1471250105) for example. Dropping support for CUDA 10 may reduce maintenance and CI test cost. Just want to hear your ideas about this @guolinke @jameslamb @StrikerRUS @jmoralez.

**Comment by jameslamb** [comment]
I'm +1 on moving LightGBM's minimum supported CUDA version to CUDA 11.x.

We have such a small team of maintainers here, and so few non-maintainer contributors around the project right now, I think the reduction in maintenance burden is necessary to ensure that at least the CDUA 11.x support is high-quality.

<hr>

Some references to help with this decision...

The last **CUDA 10.x** release, `v10.2`, was in November 2019.

The first **CUDA 11.x** release, `v11.0.1`, was in June 2020. ([release history](https://developer.nvidia.com/cuda-toolkit-archive)).

And it seems to me that many other machine learning projects supporting GPU acceleration have already done that.

**XGBoost** has been requiring CUDA 11.x since at least June 2022: https://github.com/dmlc/xgboost/issues/8006#issuecomment-1159079213 (cc @trivialfis @hcho3 could tell us if it's even further back than that)

**RAPIDS** announced that they considered CUDA 10.2 "deprecated" as of February 2021 (https://docs.rapids.ai/notices/rsn0005/)... not sure if / when they formally removed support for it.

**Pytorch** seems to only be supporting be publishing precompiled binaries CUDA 11.x as far as I can tell (not sure if they support building from source against older CUDA)

* https://pytorch.org/get-started/previous-versions/
* https://anaconda.org/pytorch/pytorch-cuda/files

<img width="988" alt="image" src="https://user-images.githubusercontent.com/7608904/226151457-4a760310-ef96-4151-ada7-e91c20f1684a.png">

**Tensorflow** dropped support for CUDA 10 as of v2.4.0, December 2020 ([support table](https://www.tensorflow.org/install/source#gpu), [release history](https://github.com/tensorflow/tensorflow/releases/tag/v2.4.0))

<img width="849" alt="Screen Shot 2023-03-18 at 10 08 00 PM" src="https://user-images.githubusercontent.com/7608904/226151478-ba4c509c-24df-416a-b287-7532bac107b9.png">

**Comment by hcho3** [comment]
@jameslamb We dropped CUDA 10.x support in February 2022: https://github.com/dmlc/xgboost/issues/7366

**Comment by jameslamb** [comment]
Perfect, thanks for that @hcho3 !

**Comment by jameslamb** [comment]
To add more evidence here... the default CUDA on Google Colab is v12.0.

Ran `!nvidia-smi` in a notebook with a T4 GPU attached tonight:

```text
+-----------------------------------------------------------------------------+
| NVIDIA-SMI 525.105.17   Driver Version: 525.105.17   CUDA Version: 12.0     |
|-------------------------------+----------------------+----------------------+
| GPU  Name        Persistence-M| Bus-Id        Disp.A | Volatile Uncorr. ECC |
| Fan  Temp  Perf  Pwr:Usage/Cap|         Memory-Usage | GPU-Util  Compute M. |
|                               |                      |               MIG M. |
|===============================+======================+======================|
|   0  Tesla T4            Off  | 00000000:00:04.0 Off |                    0 |
| N/A   39C    P8     9W /  70W |      0MiB / 15360MiB |      0%      Default |
|                               |                      |                  N/A |
+-------------------------------+----------------------+----------------------+
                                                                               
+-----------------------------------------------------------------------------+
| Processes:                                                                  |
|  GPU   GI   CI        PID   Type   Process name                  GPU Memory |
|        ID   ID                                                   Usage      |
|=============================================================================|
|  No running processes found                                                 |
+-----------------------------------------------------------------------------+
```
