### ISSUE TITLE
Integers vs floats in categorical features in LGBMRegressor

### ISSUE THREAD

**Issue by JoaquinAmatRodrigo** [microsoft/LightGBM#5820]
## Description

Hi there,

I'm having an issue with the LGBMRegressor model and its native usage of categorical features. The documentation suggests that categorical features should be encoded as integers. However, once the model has been trained, it produces the same predictions regardless of whether I pass a pandas dataframe with integers or a numpy array with floats.

I'm unsure if the model is treating the categorical features correctly since, in a categorical context, category 1.0 is different from category 1. Shouldn't the model recognize 1.0 as a separate category and produce different predictions based on this?

Thanks a lot for your help

## Reproducible example

```python
from lightgbm import LGBMRegressor
import pandas as pd
import numpy as np

# Data
# ======================================================================================
y = pd.Series(np.random.normal(size=50))
X = pd.DataFrame({
    'col_1': pd.Series(np.random.normal(size=50), dtype=float),
    'col_2': pd.Series(np.random.choice([1, 2, 3, 4], size=50), dtype='category')
})
X.head(2)

# Model
# ======================================================================================
model = LGBMRegressor(categorical_features='auto')
_ = model.fit(y=y, X=X)

# Predict using a pandas dataframe with category 
# ======================================================================================
predictions_1 = model.predict(X=X)
print(predictions_1)


# Predict using a numpy array with float values 
# ======================================================================================
X_float = X.to_numpy()
print(X_float.dtype)
predictions_2 = model.predict(X=X_float)
print(predictions_2)

# Check predictions are equal
# ======================================================================================
np.testing.assert_array_equal(predictions_1, predictions_2)
```

## Environment info

lightgbm version: 3.3.5

Command(s) you used to install LightGBM

```shell
pip install lightgbm
```

**Comment by jmoralez** [comment]
Hey @JoaquinAmatRodrigo, thanks for using LightGBM.

> However, once the model has been trained, it produces the same predictions regardless of whether I pass a pandas dataframe with integers or a numpy array with floats.

If you trained the model with categorical features LightGBM stores which columns were categorical and tries to reapply their encodings https://github.com/microsoft/LightGBM/blob/1f1ed5b44fed607c45102188c804fd2b00eb8f0e/python-package/lightgbm/basic.py#L684

but the C API expects a single data type array to compute the predictions, so after the encodings have been applied everything is cast to either float32 or float64
https://github.com/microsoft/LightGBM/blob/1f1ed5b44fed607c45102188c804fd2b00eb8f0e/python-package/lightgbm/basic.py#L1064-L1067

So by passing it directly the array you're skipping that preprocessing. It's important to note that in order to get the exact same predictions the float array must be encoded correctly, e.g. if your possible values are [10, 20, 30] they'll be encoded as [0, 1, 2], and so if you pass [10.0, 20.0, 30.0] they'll be treated as missing categories (categories LightGBM didn't see during training) and will probably yield different predictions.

Please let us know if this helps.
