### ISSUE TITLE
How can I inference trained model using c++ with gpu?

### ISSUE THREAD

**Issue by YuqiangJia** [microsoft/LightGBM#5854]
I am loading a pre-trained lightgbm model and try to inference using GPU:  
```    LGBM_BoosterPredictForMat(_handle, _agg_features.data(), C_API_DTYPE_FLOAT32, 1, _input_channels * _agg_feature_dim, 1, C_API_PREDICT_NORMAL, 0, -1, "device_type=gpu", &out_len, out.data());```
However, I found it still using cpu to inference, is it the right way using GPU?

**Comment by YuqiangJia** [comment]
Can anyone help me?

**Comment by Kaiyang-Chen** [comment]
Anyone has any idea on this? Do we support GPU inference or not?

**Comment by jameslamb** [comment]
Thanks for using LightGBM.

I believe that LightGBM does not currently have GPU-accelerated prediction, and that only training-related workloads run on the GPU. @shiyu1994 could confirm.

If you're finding that LightGBM's existing prediction routines on CPU are not fast enough for your application and are looking to improve performance, you could also explore these projects that allow serving LightGBM models:

* `treelite` (https://github.com/dmlc/treelite/blob/mainline/docs/tutorials/import.rst)
* `fil` ("forest inference library") backend for Triton (https://github.com/triton-inference-server/fil_backend)

**Comment by unbelievable3513** [comment]
james, Thank you very much for your detailed response. I have gained valuable insights from your explanation:

1. I am now aware of two engineering solutions for accelerating LightGBM model inference: `treelite` and `fil`. I will delve deeper into these options to understand their capabilities and potential benefits.
2. I apologize for the vague description of "performance is lower," which may have caused confusion. This lack of clarity likely stems from my failure to clearly articulate the specific context of the reproducible example and the training times of `lgb_cuda (600ms) `and `lgb_cpu (50ms)` as depicted in the image. Both were tested on the same model, defined by the line `model = lgb.train(params, train_data, num_boost_round=100)`, with the only difference being the device specification: `device = "cuda`" for the former and `device = "cpu"` for the latter. The reason you provided for the observed performance difference—`that the scale might be too small`—makes sense, and I will seek opportunities to conduct further experiments. Since training performance is not my primary focus, there is no need for further assistance in this regard. However, the information in the `GPU-Performance.rst` document you shared is highly informative and will be of significant value.
3. On a related note, I am curious about the absence of an official inference acceleration version. Could this be due to specific considerations, such as the CPU time already being sufficient for most scenarios? Is the repository's focus primarily on training optimization?

Thank you once again for your time and expertise.
