### ISSUE TITLE
'LightGBM:inet_pton': ambiguous call to overloaded function (compiling source file ..\src\network\liners_socket.app)

### ISSUE THREAD

**Issue by erinengle76** [microsoft/LightGBM#5856]
Hi James,

I am still facing the same issue despite using the sln file from v 3.3.5 uploaded on January 23rd. (https://github.com/microsoft/LightGBM/releases). I have selected Windows SDK 10.0 (latest installed version) and Visual Studio 2022(v143) under general properties. See error log below.
          
![Screenshot 2023-04-25 121916](https://user-images.githubusercontent.com/86852846/234380621-e60f7756-f77b-47cc-9190-baf4016601cc.png)

"Thanks for your interest in LightGBM!

I put some of the text of those logs through Google Translate (I cannot read the language they're in, apologies), and saw that it looks like you are hitting this during compilation:

> error C2668: "LightGBM::inet_pton": ambiguous call to overloaded function (compile source file..\src\network \linkers_socket.cpp)

LightGBM has its own implementation of `inet_pton`, but some newer compilers on Windows ship with their own, conflicting implementation.

If you searched this project's issue tracker for that error message, you'd see that the same error was reported in #5019, and fixed about 5 months ago in #5159.

Please update to a newer version of LightGBM's source code, from at least after #5159.

If that doesn't resolve the issue you're facing, please click below to see the information we need to efficiently, effectively help you.

<details><summary>how to ask for help (click me)</summary>

It is very very very difficult for maintainers to help you when you only report a wall of logs without other context.

* are you installing the Python package / R package? just building the CLI? something else?
* how did you try to install LightGBM?
* what version are you using?
* it seems like you might be using Visual Studio to compile LightGBM... what version of Visual Studio? Did you customize anything about the installation?

Without answers like this, you are asking maintainers here to guess what you're doing, and that will take away our already-limited time from other work on this project.

Can you please provide the answers to the questions I've asked above?

</details>

_Originally posted by @jameslamb in https://github.com/microsoft/LightGBM/issues/5499#issuecomment-1271827484_"

**Comment by jameslamb** [comment]
Thanks for using LightGBM and for the report. I was able to reproduce this on latest `master` (https://github.com/microsoft/LightGBM/commit/a2c1dec0722c3cfe614d6cd7718b306216053693) today with the following steps:

1. setting Windows SDK version in `LightGBM.vcxproj` to `10.0`

https://github.com/microsoft/LightGBM/blob/a2c1dec0722c3cfe614d6cd7718b306216053693/windows/LightGBM.vcxproj#L37

2. running the following from the root of the repo

```pwsh
MSBuild.exe windows/LightGBM.sln /p:Configuration=DLL /p:Platform=x64 /p:PlatformToolset=v142
```

I have Visual Studio 2019, and am on Windows 10.

Adding `#define WIN_HAS_INET_PTON` right above this line, I'm able to compile LightGBM successfully with `MSBuild.exe`.

https://github.com/microsoft/LightGBM/blob/a2c1dec0722c3cfe614d6cd7718b306216053693/src/network/socket_wrapper.hpp#L59

I suspect that would work for you too.

-----

I guess that building directly from inside Visual Studio the way you are, `CMake` isn't being used, and therefore this check doesn't run?

https://github.com/microsoft/LightGBM/blob/a2c1dec0722c3cfe614d6cd7718b306216053693/CMakeLists.txt#L338-L348

I'll try to push a fix for that. Since that the was only added for compatibility with newer MinGW, it should be safe to assume that any build using Visual Studio compilers won't already have `inet_pton.
