### ISSUE TITLE
Feature importance with duplicated data

### ISSUE THREAD

**Issue by beantr96** [microsoft/LightGBM#5864]
## Description

I don't think this is a bug but I just want to understand better the mechanism of LightGBM. I want to assess how LightGBM works in case of duplicated data. My setup is to train LightGBM on dataset 1: 30 random samples and dataset 2: 60 samples (duplicate of dataset 1). When checking the feature importance, the importance of dataset 1 is all 0s and while for dataset 2 there are a few non-zero values. I want to know what factor influences the feature importance because I assume duplicating the data does not lead to any additional information.

## Reproducible example

```python
import numpy as np 
from lightgbm import LGBMClassifier

X = np.random.rand(30, 2)
y = np.random.randint(0, 2, 30)

model1 = LGBMClassifier()
model1.fit(X, y)

model2= LGBMClassifier()
model2.fit(np.concatenate([X, X]), np.concatenate([y, y]))

print("Feature importance on dataset 1", model1.feature_importances_)
print("Feature importance on dataset 2", model2.feature_importances_)
```
Output:
```
Feature importance on dataset 1 [0 0]
Feature importance on dataset 2 [63 74]
```
## Environment info

LightGBM version or commit hash: 3.3.5

Command(s) you used to install LightGBM

```shell
pip install lightgbm
```

## Additional Comments

The original problem that leads to this investigation is that I want to select the features using sklearn's SelectFromModel with lightgbm on a very small dataset of 17 sample points. The feature importance I got was all 0s. However, when I duplicated the data, the importance of some features is non-zero and can be used for feature selection. I want better understand if duplicating the data can significantly influences the importance and subsequently the selected features.

**Comment by adfea9c0** [comment]
The models are actually quite different:
```python
print(f"Model 1 has {model1.booster_.num_trees()} trees")
print(f"Model 2 has {model2.booster_.num_trees()} trees")
```
which gives
```
Model 1 has 1 trees
Model 2 has 100 trees
```
The [default parameters](https://lightgbm.readthedocs.io/en/v3.3.2/Parameters.html) result in an empty first model, probably setting `min_data_in_leaf` to something smaller should solve the issue.

**Comment by jameslamb** [comment]
@adfea9c0 is exactly right. LightGBM's default values for overfitting-control parameters like `min_data_in_leaf` are set based on the assumption that you'll have at least a few thousand rows.

For very very small datasets like the ones in your examples, if you want LightGBM to overfit as a way to test your understanding of how it works, set at least `min_data_in_leaf=1`, and consider also setting smaller-than-the-default values for `min_data_in_bin` and `min_gain_to_split`.

This answer describes it in more detail: https://stackoverflow.com/a/66728185/3986677

Since you asked about duplicate features, you might also find this informative: https://stackoverflow.com/a/73059939/3986677
