### ISSUE TITLE
DaskLGBMRegressor early_stopping_rounds error

### ISSUE THREAD

**Issue by kunshouout** [microsoft/LightGBM#5963]
It seems using early_stopping_rounds with DaskLGBMRegressor would result in
`lightgbm.basic.LightGBMError: Socket recv error, Connection reset by peer (code: 104)`

Is this expected behavior?

LightGBM version or commit hash:
3.3.5.99

**Comment by jameslamb** [comment]
Thanks for using LightGBM.

Early stopping is not yet supported in the Dask interface. You can follow #4189 to be notified if/when that support is added.

However... I wouldn't expect the error you mentioned could be caused by providing parameter `early_stopping_rounds`.

If you can provide us with enough information to reproduce the issue you're facing, we can help:

* operating system
* version of Python
* versions of `dask` and `distributed`
* minimal, self-contained code which reproduces the error
