### ISSUE TITLE
[python-package] Where has the "fobj" parameter gone in lightgbm.cv() in v4.0.0?

### ISSUE THREAD

**Issue by vladv14** [microsoft/LightGBM#6072]
In prior version (v3.3.5) lightgbm cv function accepts custom objective function via the fobj parameter as can be found here:
https://lightgbm.readthedocs.io/en/v3.3.5/pythonapi/lightgbm.cv.html

This parameter has disappeared in v4.0.0 and you would now get an error:
TypeError: cv() got an unexpected keyword argument 'fobj'

**Comment by jameslamb** [comment]
Thanks for using LightGBM.

`fobj` was removed from the interface of `train()` and `cv()` as of v4.0.0, in #5052.

Please instead pass a custom objective function through the `params` dictionary, like this:

```python
import lightgbm as lgb
import numpy as np
from sklearn.datasets import make_regression

X, y = make_regression(n_samples=10_000)
dtrain = lgb.Dataset(X, label=y)


def mse_obj(y_pred, dtrain):
    y_true = dtrain.get_label()
    grad = (y_pred - y_true)
    hess = np.ones(len(grad))
    return grad, hess


results_dict = lgb.cv(
    train_set=dtrain,
    params={
        "objective": mse_obj,
    },
    metrics=["rmse", "mae"],
    num_boost_round=4,
    nfold=3,
    stratified=False,
)
print(results_dict)
```

```text
{
  "valid rmse-mean": [
    176.36987026398734,
    167.6587549252454,
    159.89456470976708,
    152.87281010933657
  ],
  "valid rmse-stdv": [
    3.1024741893923964,
    2.8084421012176723,
    2.697431048972295,
    2.8063495452805944
  ],
  "valid l1-mean": [
    139.73999487039018,
    132.74335440132123,
    126.45147148699913,
    120.75546660303708
  ],
  "valid l1-stdv": [
    2.5603029246751587,
    2.351527407415942,
    2.317894957868989,
    2.376012741246122
  ]
}
```

Note that it's important to explicitly pass `metrics` when using a custom objective, since LightGBM won't be able to guess appropriate evaluation metrics when the objective function is arbitrary Python code.

In case you haven't seen, all of LightGBM's release notes are available at https://github.com/microsoft/LightGBM/releases. Searching for "fobj" at https://github.com/microsoft/LightGBM/releases/tag/v4.0.0 would have pointed you to #5052.

**Comment by vladv14** [comment]
Thank you very much for your answer and the example @jameslamb! This is very clear.
