### ISSUE TITLE
Unable to load shared library 'lib_lightgbm' or one of its dependencies with Docker

### ISSUE THREAD

**Issue by jonidaschl** [microsoft/LightGBM#6079]
I am using `ML.NET` to train and create models with different algorithms. When I test the method locally on windows it works fine.

But when I run it with Docker this error comes up:

> System.DllNotFoundException: Unable to load shared library 'lib_lightgbm' or one of its dependencies. In order to help diagnose loading problems, consider setting the LD_DEBUG environment variable: liblib_lightgbm: cannot open shared object file: No such file or directory.

This is my Dockerfile:

```dockerfile
FROM mcr.microsoft.com/dotnet/aspnet:6.0 AS base
WORKDIR /app
EXPOSE 80
EXPOSE 443

FROM mcr.microsoft.com/dotnet/sdk:6.0 AS build
WORKDIR /src

RUN apt-get update
RUN apt-get install git clang-3.9 cmake libunwind8 curl -y 
RUN apt-get install -y libomp-dev

RUN git clone --recursive https://github.com/microsoft/LightGBM /src/LightGBM

WORKDIR /src/LightGBM
RUN mkdir build && cd build && cmake .. && make -j install

COPY ["MAS/MAS.csproj", "RAS/"]
COPY ["DAL/DAL.csproj", "DAL/"]
COPY ["Domain/Domain.csproj", "Domain/"]
COPY ["DI/DI.csproj", "DI/"]

RUN dotnet restore "MAS/MAS.csproj"
COPY . .
WORKDIR "/src/MAS"
RUN dotnet build "MAS.csproj" -c Release -o /app/build

FROM build AS publish
RUN dotnet publish "MAS.csproj" -c Release -o /app/publish /p:UseAppHost=false

FROM base AS final
WORKDIR /app
COPY --from=publish /app/publish .

ENV LD_DEBUG=all

ENTRYPOINT ["dotnet", "MAS.dll"]
```

**Comment by jameslamb** [comment]
Thanks for using LightGBM.

I've reformatted this report so that the difference between code, output from code, and your own words is clearer. If you're unsure how I did that, please read https://docs.github.com/en/get-started/writing-on-github/getting-started-with-writing-and-formatting-on-github/basic-writing-and-formatting-syntax.

Also...I see that you double-posted this here and on Stack Overflow ([link](https://stackoverflow.com/questions/76995421/unable-to-load-shared-library-lib-lightgbm-or-one-of-its-dependencies-with-doc)). **Please do not do that.** Maintainers here also monitor the `[lightgbm]` tag on Stack Overflow. I could have been spending time preparing an answer here while another maintainer was spending time answering your Stack Overflow post, which would have been a waste of maintainers' limited attention that could otherwise have been spent improving this project. Double-posting also makes it less likely that others with a similar question will find the relevant discussion and answer.

This report would have been more appropriate in the `ML.Net` repo (https://github.com/dotnet/machinelearning/issues), but let's not further split the conversation across multiple websites.

I'll investigate this for a bit right now, and post on your Stack Overflow post. If I can't find anything, I'll tag some of the `ML.Net` maintainers and direct them there as well.

**Comment by jameslamb** [comment]
I've responded in comments on your Stack Overflow post, but to be honest I'm not sure what the exact root cause is. I suspect it lies somewhere in:

* mixing of Windows and Linux components (executing a `.dll` in a Debian image is unusual)
* definition of your project in files not shown in your reports

If you can reduce this issue to a [minimal, reproducible example](https://stackoverflow.com/help/minimal-reproducible-example) using only LightGBM and not `ML.Net`, we can investigate more. Otherwise, consult the `ML.Net` docs (https://github.com/dotnet/machinelearning/tree/main) and/or continue the investigation with the several people who've already commented on your Stack Overflow post.
