### ISSUE TITLE
[R-package] lightgbm 3.3.5 installation issue on Mac

### ISSUE THREAD

**Issue by pholiu** [microsoft/LightGBM#6088]
I am installing the latest version of lightgbm on my Mac using

```r
install.packages("lightgbm")
```

However, it can't be installed and it says

```text
checking whether MM_PREFETCH works... no
checking whether MM_MALLOC works... no
checking whether OpenMP will work in a package... no
***********************************************************************************************
 OpenMP is unavailable on this macOS system. LightGBM code will run single-threaded as a result.

 To use all CPU cores for training jobs, you should install OpenMP by running

     brew install libomp
***********************************************************************************************
configure: creating ./config.status
config.status: creating src/Makevars
** libs
xcrun: error: invalid active developer path (/Library/Developer/CommandLineTools), missing xcrun at: /Library/Developer/CommandLineTools/usr/bin/xcrun
ERROR: compilation failed for package ‘lightgbm’
* removing ‘/Library/Frameworks/R.framework/Versions/4.0/Resources/library/lightgbm’
```

I used to use 3.3.2 of lightgbm and it has no problem in installing it on my Mac. It looks like the latest version requires OpenMP to be available on Mac? What can I do to make it installed?

Thank you!

**Comment by jameslamb** [comment]
Thanks for using LightGBM.

I don't think this issue is specific to LightGBM... what happens if you run something like the following in R?

```r
install.packages(c("data.table", "xgboost"), repos = "https://cran.r-project.org")
```

I suspect that'll fail with similar errors. If you search for that XCode error using Google or a similar search engine, you'll see many posts including it that are unrelated to LightGBM or R:

* https://developer.apple.com/forums/thread/673827
* https://apple.stackexchange.com/questions/254380/why-am-i-getting-an-invalid-active-developer-path-when-attempting-to-use-git-a

Open the Terminal app or similar and run the commands listed in this answer: https://apple.stackexchange.com/a/254381/505218

```shell
xcode-select --install
```

Then try reinstalling `{lightgbm}`.

----

NOTE: I've edited your question to make the difference between code, output from code, and your own own words clearer. If you're unfamiliar with how to do that, please see https://docs.github.com/en/get-started/writing-on-github/getting-started-with-writing-and-formatting-on-github/basic-writing-and-formatting-syntax.

**Comment by jameslamb** [comment]
> I used to use 3.3.2 of lightgbm and it has no problem in installing it on my Mac.

I noticed that you're using R 4.0. I suspect that's why you didn't face this installation issue with `{lightgbm}` v3.3.2. I'm guessing CRAN prepared macOS binaries of `{lightgbm}` for R 4.0 as of when v3.3.2 was released. I suspect there are no such binaries for v3.3.5 + that version of R. Upgrading to R 4.1 or 4.2 might mean that `install.packages("lightgbm")` gives you a precompiled binary that doesn't require compilation from source, and therefore doesn't hit issues in the build toolchain like the XCode error you've reported.

> *It looks like the latest version requires OpenMP to be available on Mac? What can I do to make it installed?*

I want to clarify for you and for anyone finding this issue from search... this statement is not correct. For every release of `{lightgbm}` that has ever been on CRAN, LightGBM links to OpenMP if an installation is found *but does not strictly require it*.
