### ISSUE TITLE
my program crashed when call LightGBM::Boosting::Predict()

### ISSUE THREAD

**Issue by Jason0401** [microsoft/LightGBM#6225]
LightGBM::Boosting* boosting = LightGBM::Boosting::CreateBoosting("gbdt", "model.txt");
boosting->InitPredict(0, num, false);
boosting->Predict(data[0].data(), &predValue, nullptr); //coredump here

**Comment by jameslamb** [comment]
Thanks for using LightGBM.

This is not enough information for us to help. Can you please provide a minimal, reproducible example? That would mean a self-contained, minimal example code that we could run which reproduces what you're seeing.

As well as this information which you were asked for when you clicked "New issue":

* operating system
* version of LightGBM you are using
* how you installed LightGBM (exact commands)
* compiler you're using for your own program (since it appears you're using the C API directly)
