### ISSUE TITLE
Reasons of difference between multiclass versus multiclassova in multi-class classification

### ISSUE THREAD

**Issue by Cauchemare** [microsoft/LightGBM#6248]
## Summary
as regards the difference between multiclass and  multiclassova ,after have readed  the debate of this issue [multiclass versus multiclassova in multi-class classification problems](https://github.com/Microsoft/LightGBM/issues/1518)
I have some question as belows :
1. Why there exists those difference ,or what is the purpose ?;
2. If in multiclass situation,I find one class predict result is perfect,could I contruct one binary model to  reappper the prediction ?（even I know maybe impossible）

Hope you can explain a bit further.
Thank you. 
Any reports are also welcome

**Comment by khaymanii** [comment]
The differences between the "multiclass" (One-vs-All) and "multiclassova" (One-vs-One) strategies in multi-class classification stem from various considerations related to computational efficiency, handling imbalances, and the interpretability of predictions.

1. Computational Efficiency:
  Multiclass: It is computationally more efficient as it requires training only N classifiers, where N is the number of classes.
   Multiclassova: Involves training N * (N-1) / 2 classifiers, leading to higher computational complexity. This can be a concern, especially when dealing with large datasets or limited computational resources.

2. Handling Imbalances:
   Multiclass: Tends to handle class imbalances better because each classifier focuses on distinguishing one class from the rest.
   Multiclassova: May be sensitive to imbalances in class pairs, potentially leading to challenges when certain class pairs are more prevalent in the data.

3. Prediction Confidence:
   Multiclass: Provides confidence scores for each class, aiding in understanding the classifier's certainty about predictions.
   Multiclassova:Typically results in a "vote" without direct confidence measures. The winning class might not always have the highest individual classifier confidence.

4. Interpretability:
   Multiclass: Offers straightforward interpretability as each classifier distinguishes between one class and the rest.
   Multiclassova: Provides insights into pairwise class relationships, which can be beneficial when understanding the distinctions between specific classes is important.

The choice between these strategies depends on the specific characteristics of the problem at hand and the available resources.

**Comment by khaymanii** [comment]
Yes, it's possible to construct a binary model for a specific class in a multiclass situation, although it might not necessarily improve the overall performance of your model.

**Comment by Cauchemare** [comment]
thanks for  replying to my question, but in fact, ova version means "one-versus-all" ,not "one-vs-one" you have writed in your explanation;
