### ISSUE TITLE
[python-package] Can't import LightGBM into Jupyter notebook on M1 MacOS

### ISSUE THREAD

**Issue by erickrb83** [microsoft/LightGBM#6262]
## Description
I get an OSError when I try to import lightgbm as lgb

## Reproducible example
When I enter
`import lightgbm as lgb
`
I get the following error:
```
---------------------------------------------------------------------------
OSError                                   Traceback (most recent call last)
Input In [2], in <cell line: 1>()
----> 1 import lightgbm as lgb
      3 get_ipython().run_line_magic('matplotlib', 'inline')
      5 try:
      6     # To enable interactive mode you should install ipywidgets
      7     # https://github.com/jupyter-widgets/ipywidgets

File ~/opt/anaconda3/lib/python3.9/site-packages/lightgbm/__init__.py:8, in <module>
      2 """LightGBM, Light Gradient Boosting Machine.
      3 
      4 Contributors: https://github.com/microsoft/LightGBM/graphs/contributors.
      5 """
      6 from pathlib import Path
----> 8 from .basic import Booster, Dataset, Sequence, register_logger
      9 from .callback import EarlyStopException, early_stopping, log_evaluation, record_evaluation, reset_parameter
     10 from .engine import CVBooster, cv, train

File ~/opt/anaconda3/lib/python3.9/site-packages/lightgbm/basic.py:247, in <module>
    245     _LIB = Mock(ctypes.CDLL)  # type: ignore
    246 else:
--> 247     _LIB = _load_lib()
    250 _NUMERIC_TYPES = (int, float, bool)
    251 _ArrayLike = Union[List, np.ndarray, pd_Series]

File ~/opt/anaconda3/lib/python3.9/site-packages/lightgbm/basic.py:232, in _load_lib()
    230 """Load LightGBM library."""
    231 lib_path = find_lib_path()
--> 232 lib = ctypes.cdll.LoadLibrary(lib_path[0])
    233 lib.LGBM_GetLastError.restype = ctypes.c_char_p
    234 callback = ctypes.CFUNCTYPE(None, ctypes.c_char_p)

File ~/opt/anaconda3/lib/python3.9/ctypes/__init__.py:460, in LibraryLoader.LoadLibrary(self, name)
    459 def LoadLibrary(self, name):
--> 460     return self._dlltype(name)

File ~/opt/anaconda3/lib/python3.9/ctypes/__init__.py:382, in CDLL.__init__(self, name, mode, handle, use_errno, use_last_error, winmode)
    379 self._FuncPtr = _FuncPtr
    381 if handle is None:
--> 382     self._handle = _dlopen(self._name, mode)
    383 else:
    384     self._handle = handle

OSError: dlopen(/Users/MyUserName/opt/anaconda3/lib/python3.9/site-packages/lightgbm/lib/lib_lightgbm.so, 0x0006): Library not loaded: /usr/local/opt/libomp/lib/libomp.dylib
  Referenced from: <AF2B35E2-56EE-3669-88A6-BBD75577D81F> /Users/MyUserName/opt/anaconda3/lib/python3.9/site-packages/lightgbm/lib/lib_lightgbm.so
  Reason: tried: '/usr/local/opt/libomp/lib/libomp.dylib' (no such file), '/System/Volumes/Preboot/Cryptexes/OS/usr/local/opt/libomp/lib/libomp.dylib' (no such file), '/usr/local/opt/libomp/lib/libomp.dylib' (no such file), '/usr/local/lib/libomp.dylib' (no such file), '/usr/lib/libomp.dylib' (no such file, not in dyld cache)
```

## Environment info
python: 3.11.7.final.0
conda: 23.11.0
Anaconda Navigator 2.3
Lighgbm: 4.2.0
numpy: 1.26.3
scipy: 1.11.4
libomp: 17.0.6
cmake: 3.28.1

LightGBM version or commit hash:

Command(s) you used to install LightGBM
I've used home brew, pip, in anaconda notebook. 
```
brew install lightgbm
pip install lightgbm
!pip install lightgbm
%pip install lightgbm
```

## Additional Comments
Not sure what else to try. Any help is greatly appreciated. Thanks.

**Comment by jameslamb** [comment]
Thanks for using LightGBM, and for the excellent report!

## Short Answer

Install OpenMP with Homebrew.

```shell
brew install libomp
```

Restart your Jupyter kernel. Importing `lightgbm` should now work.

## Longer Answer

With its default settings, LightGBM requires OpenMP. It looks like you don't have a copy available. That's what this line in the logs is telling you:

>   Reason: tried: '/usr/local/opt/libomp/lib/libomp.dylib' (no such file), '/System/Volumes/Preboot/Cryptexes/OS/usr/local/opt/libomp/lib/libomp.dylib' (no such file), '/usr/local/opt/libomp/lib/libomp.dylib' (no such file), '/usr/local/lib/libomp.dylib' (no such file), '/usr/lib/libomp.dylib' (no such file, not in dyld cache)

Since it appears that you're on macOS + using `pip install`, using Homebrew to install OpenMP is probably the most reliable way to get it.

Alternatively, since I see you're using conda, you could alternatively install `lightgbm` from `conda-forge`. That has a prebuilt binary for M1 mac (so should install much faster than with `pip install` on your system), and will automatically pull in a `conda-forge` distribution of OpenMP.

```shell
pip uninstall --yes lightgbm
conda install \
    --yes \
    -c conda-forge \
        'lightgbm>=4.2.0'
```

## One more note

Homebrew's distribution of `lightgbm` is **only the LightGBM command-line interface (CLI)**. If your goal is to use the `lightgbm` Python package, `brew install lightgbm` won't help you.

In fact, it could even cause issues with your Python package, if you have a different version of the Homebrew package and the Python package.

If you're not using the LightGBM CLI, uninstall it.

```shell
brew uninstall lightgbm
```
