### ISSUE TITLE
[gpu] error installing GPU version: "CMakeLists.txt not present"

### ISSUE THREAD

**Issue by prasithats** [microsoft/LightGBM#6281]
## Description

While am trying to use GPU along with LightGBM am getting an error like "recompile with CMake `DUSE_GPU=1`", but again while am trying that am getting an error like CMakeLists.txt not present.

Please help me to solve this error immediately.

## Environment info

LightGBM version or commit hash:

Command(s) you used to install LightGBM

```shell

```

**Comment by jameslamb** [comment]
Thanks for your interest in LightGBM.

Please see the documentation on building a GPU-accelerated version of LightGBM:

* NVIDIA GPUs: https://lightgbm.readthedocs.io/en/latest/Installation-Guide.html#build-cuda-version
* all others: https://lightgbm.readthedocs.io/en/latest/Installation-Guide.html#build-gpu-version

If you're looking to use the Python package, see that documentation:

* NVIDIA GPUs: https://github.com/microsoft/LightGBM/blob/master/python-package/README.rst#build-cuda-version
* all others: https://github.com/microsoft/LightGBM/blob/master/python-package/README.rst#build-gpu-version

If those don't resolve your issue, please post a minimal, reproducible example with the information you were asked to provide when you clicked "new issue":

* operating system
* version of LightGBM (or commit hash)
* exact commands you ran to install LightGBM
* any logs printed by the build

**Comment by jameslamb** [comment]
I've reformatted your post so that your question is in the body and not all in the title. I suspect you might be new to GitHub. We're happy to have you here, but please review the following before posting again:

* https://docs.github.com/en/issues/tracking-your-work-with-issues/creating-an-issue
* https://docs.github.com/en/get-started/writing-on-github/getting-started-with-writing-and-formatting-on-github/basic-writing-and-formatting-syntax

**Comment by jameslamb** [comment]
Closing due to lack of response. We'd be happy to help in the future if you have other questions.
