### ISSUE TITLE
LGBM_BoosterCreateFromModelfile crash on Android device

### ISSUE THREAD

**Issue by BurjalHou** [microsoft/LightGBM#6343]
## Description
We are running LightGBM on Android devices, sometimes the following crash occurs in `LGBM_BoosterCreateFromModelfile` method:

```
backtrace:
      #00 pc 000000000003ee9c  ../com.android.runtime/lib64/bionic/libc.so (_Unwind_SetGR+76) (BuildId: )
      #01 pc 000000000000a604  /system/lib64/libxxx.so (__gxx_personality_v0+336) (BuildId: )
      #02 pc 000000000042b164  /system/lib64/lib_lightgbm.so
```

## Reproducible example

Occasional crashes.

```cpp
ALOGD("LGBM_BoosterCreateFromModelfile begin"); // 
result = LGBM_BoosterCreateFromModelfile(filename, &p, &handle);
ALOGD("LGBM_BoosterCreateFromModelfile end"); // when crashed, no this line
```

## Environment info

LightGBM version or commit hash: d78b6bc2fdf96c87e3cb61f2d497a962e3270c91

## Additional Comments
We guess that an exception occurred in `API_BEGIN()` and `API_END()`.

```
int LGBM_BoosterCreateFromModelfile(
  const char* filename,
  int* out_num_iterations,
  BoosterHandle* out) {
  API_BEGIN();
  auto ret = std::unique_ptr<Booster>(new Booster(filename));
  *out_num_iterations = ret->GetBoosting()->GetCurrentIteration();
  *out = ret.release();
  API_END();
}
```

If any additional information is required please contact me. Thanks.

**Comment by jameslamb** [comment]
Thanks for using LightGBM.

We don't test deployment to mobile operating systems but can try to help here. To do that, we need more information.

1. Could you provide the model file as a text file attachment here?
2. Is it possible to upgrade to a newer version of LightGBM? The version you're using is from September 1, 2022 ... there have been many fixes and improvements since then.
3. Can you please provide the exact commands you used to build LightGBM?
