### ISSUE TITLE
[python-package] json.decoder.JSONDecodeError when loading booster from save_model method

### ISSUE THREAD

**Issue by simpsus** [microsoft/LightGBM#6349]
## Description
Trying to load a booster from a model file that was created by calling booster.save_model before

## Reproducible example
[mmc_staking_bmc_trial_10_exact_train.txt](https://github.com/microsoft/LightGBM/files/14472329/mmc_staking_bmc_trial_10_exact_train.txt)

using the text file above the code to reproduce is
```shell
booster = lgb.Booster(model_file="mmc_staking_bmc_trial_10_exact_train.txt")
```

output is:
```
>>> lgb.Booster(model_file=fn)
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "C:\Users\grumb\miniconda3\envs\tool\Lib\site-packages\lightgbm\basic.py", line 3244, in __init__
    params = self._get_loaded_param()
             ^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\grumb\miniconda3\envs\tool\Lib\site-packages\lightgbm\basic.py", line 3312, in _get_loaded_param
    return json.loads(string_buffer.value.decode('utf-8'))
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\grumb\miniconda3\envs\tool\Lib\json\__init__.py", line 346, in loads
    return _default_decoder.decode(s)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\grumb\miniconda3\envs\tool\Lib\json\decoder.py", line 337, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\grumb\miniconda3\envs\tool\Lib\json\decoder.py", line 355, in raw_decode
    raise JSONDecodeError("Expecting value", s, err.value) from None
json.decoder.JSONDecodeError: Expecting value: line 1 column 1181 (char 1180)
```
## Environment info

LightGBM version or commit hash:
4.1.0
Command(s) you used to install LightGBM

```shell
pip install lightgbm
```

Windows, python 3.11, usage of lightgbm via python package

**Comment by jameslamb** [comment]
Thanks for using LightGBM and for the very clear report.

I'm able to reproduce this with `lightgbm` built from latest sources here (https://github.com/microsoft/LightGBM/commit/1a292f898ee08530583a15bcd99e05a499a289a4), using Python 3.11 on macOS.

It looks like the problem is this line in the model file:

```text
[interaction_constraints: False]
```

That is parsed into this text

```text
"interaction_constraints": [False]
```

Which isn't valid JSON. JSON booleans must be `false` or `true` (all lowercase).

If I manually change that line in the model file to `[false]`, I'm able to load the model.

```python
import lightgbm as lgb
import tempfile

with tempfile.NamedTemporaryFile() as patched_file:
    with open("/Users/jlamb/Downloads/mmc_staking_bmc_trial_10_exact_train.txt", "r") as original_file:
        original_content = original_file.read()
    patched_content = original_content.replace(
        "interaction_constraints: False",
        "interaction_constraints: false"
    )
    patched_file.write(patched_content.encode("UTF-8"))
    booster = lgb.Booster(model_file=patched_file.name)

# check that the parameters from the file were preserved
assert booster.params["objective_seed" == 29849]

# view all loaded parameters
print(booster.params)
```

So, I'd like to understand how that `: False` got in there.

* did you manually edit the model file?
* if not, can you please share exactly how it was created?
   - e.g. version of LightGBM used to create it, code you used to create it

**Comment by simpsus** [comment]
Hallo @jameslamb ,

Thank you for that comprehensive reply.
The version of lightgbm used to create that booster is 4.1.0

The exact code is a bigger hyperparameter optimization study (I use optuna for that). Basically I get a trial object which I can use to sample parameters. I use it like 

```
    trial.suggest_categorical("interaction_constraints", [True, False])
    # cleanup the params dict
    params.update(trial.params)
    if params["interaction_constraints"]:
        params["interaction_constraints"] = INTERACTION_CONSTRAINTS
```

The params dict then gets passed to lightgbm the usual way

```
booster = lgb.train(
                params=params,
                train_set=self.train_datasets[split],
                callbacks=[
                    DeadManSwitchCallback(frequency=100),
                ],
            )
```

If the trial samples a True, the parameter in the dict gets replaced by the actual interaction contrstaints (the uppercase constant), but if not, the False stays.

So it seems we have two issues:

1) I should not be setting that to False. I see in the docs that None is the default value. I guess I should set it to None then?
2) The False is accepted by the booster and then also written into the json which only tanks on import, would be nice to know earlier that an unusable json is produced.

May I asked how you found out which line was causing the problem? I would have loved to find that out myself but had no clue on where to start.

**Comment by jameslamb** [comment]
> May I asked how you found out which line was causing the problem?

Looking at the stacktrace you provided, I saw the error was coming form a `json.loads()` in function `_get_loaded_param()` in `lightgbm`'s `basic.py`.

I put a break point like this:

```python
import pdb; pdb.set_trace()
```

Right before that `json.loads()`, here:

https://github.com/microsoft/LightGBM/blob/28536a0a5d0c46598fbc930a63cec72399a969e4/python-package/lightgbm/basic.py#L3762

Then rebuilt the library, following the docs at https://github.com/microsoft/LightGBM/blob/master/python-package/README.rst.

```shell
cmake -B build -S .
cmake --build build --target _lightgbm -j4
sh ./build-python.sh install --precompile
```

Then I ran the code you provided with the model file you provided (filling in the omitted parts like imports... please include those next time to make the example fully reproducible).

```python
import lightgbm as lgb

lgb.Booster(model_file="mmc_staking_bmc_trial_10_exact_train.txt")
```

That dropped me into an interactive debugger (the result of that `pdb.set_trace()`).

From there, I printed out the value JSON string. Put that into a JSON validator in my local development environment (in this case, Sublime Text), and that helped me find the line which was not valid JSON.

**Comment by jameslamb** [comment]
> I see in the docs that None is the default value.

Could you please share where you see that?

In the parameter docs ([docs link](https://lightgbm.readthedocs.io/en/latest/Parameters.html#interaction_constraints)), I see `""` as the default.

As well as this note: *"for Python-package, list of lists, e.g. `[[0, 1, 2], [2, 3]]`"*

And that parameter isn't exposed as a keyword argument in any parts of the Python package or otherwise included in Python-specific docs.

```shell
git grep interaction python-package/
```

>  I guess I should set it to None then?

If it's more convenient in your setup to provide some value in the `params` dictionary than to completely omit it, then yes, use `None`.

You can use this minimal, reproducible example to test different values. It works for me with Python 3.11 and `lightgbm==4.3.0.99` (built from latest `master`).

```python
import lightgbm as lgb
from sklearn.datasets import make_regression

X, y = make_regression(n_samples=1_000, n_features=2)

bst = lgb.train(
    params={
        "objective": "regression",
        "num_iterations": 1,
        "interaction_constraints": None
    },
    train_set=lgb.Dataset(X, label=y)
)
bst.save_model("delete_me.txt")

new_booster = lgb.Booster(model_file="delete_me.txt")
assert new_booster.num_trees() == 1
```

Any parameter set to `None` in `params` in the Python package will not be passed along to the C/C++ side.

If you're curious, here's where that happens:

https://github.com/microsoft/LightGBM/blob/28536a0a5d0c46598fbc930a63cec72399a969e4/python-package/lightgbm/basic.py#L523-L535

> The False is accepted by the booster and then also written into the json which only tanks on import, would be nice to know earlier that an unusable json is produced.

Totally understandable! Sorry that you hit this.

I'm not sure where the right place is to put validation like that. LightGBM has many parameters, and supports a free-form dictionary for setting them (a pattern introduced before `dataclasses` existed in Python) to prevent breaking the significant amount of `lightgbm` code out in the world.

Will think about it.

**Comment by simpsus** [comment]
Thank you for that follow up.

Re docs you are right it says "", not None. I searched the github repo because I could swear I saw it with None but nope.

I guess the problem here is with python treating None, False and "" kind of similar. They all lead to the else branch of an if statement.  But they are not the same, so

`None == False` or `"" == None` both evaluate to false.

So if lightgbm wanted to catch that error it could.  You are right about the possible implications. I would assume before this issue has not surfaced. So ... why not put it at the generation of the json? As you say, it produces invalid json and so ... it should not do that. 

As for the question what it _should_ do, I would hope that a conversion to "" works for every parameter. If it does not, at lease None would not work either.

I close this issue because it is resolved for me, please feel free to reopen it you want more input from my side

**Comment by jameslamb** [comment]
> why not put it at the generation of the json? As you say, it produces invalid json and so ... it should not do that.

I agree with this statement.

If you're interested in trying to propose a fix like that, we'd be happy to consider it. Here's the code where that JSON is generated:

https://github.com/microsoft/LightGBM/blob/28536a0a5d0c46598fbc930a63cec72399a969e4/src/boosting/gbdt.h#L169
