### ISSUE TITLE
[R-package] how do I build a GPU-enabled version of the R package?

### ISSUE THREAD

**Issue by nipnipj** [microsoft/LightGBM#6378]
I followed these steps:
```
git clone --recursive https://github.com/microsoft/LightGBM
cd LightGBM
mkdir build
cd build
cmake -DUSE_GPU=1 ..
make -j4
```
At this point everything compiled/built. My question is. How do I make R recognize it as a package?

**Comment by jameslamb** [comment]
Thanks for using LightGBM.

Those steps product the LightGBM CLI (`./lightgbm`) and shared library (`./lib_lightgbm.so`) but not the R package. They're not necessary to build the R package.

To build the R package from sources here on GitHub, follow the instructions at https://github.com/microsoft/LightGBM/tree/master/R-package#installation.

Since it looks like you'd like to build a GPU-accelerated version of the package, pay particular attention to https://github.com/microsoft/LightGBM/tree/master/R-package#installing-a-gpu-enabled-build.

```shell
Rscript build_r.R --use-gpu
```

The CRAN-style distribution of the package does not support GPU acceleration at this time. That feature is tracked in these:

* #3206
* #3465
* #5378

**Comment by nipnipj** [comment]
Whe I use `Rscript build_r.R --use-gpu`, I get another error, it asks me to recomplile with cmake -DUSE_CUDA=1.
Basically I just want to test the GPU capabilities.

**Comment by jameslamb** [comment]
> it asks me to recompile with cmake -DUSE_CUDA=1

Running the command `Rscript build_r.R --use-gpu` generates an error telling you to pass `-DUSE_CUDA=1`? That doesn't sound right to me.

Can you please share the exact text of that error message?

**Comment by nipnipj** [comment]
Ok I opened terminal from LightGBM folder and used `Rscript build_r.R --use-gpu`. Then I tried to fit a model and the following message appears:
```
[LightGBM] [Fatal] CUDA Tree Learner was not enabled in this build.
Please recompile with CMake option -DUSE_CUDA=1
Error in initialize(...) : 
  CUDA Tree Learner was not enabled in this build.
Please recompile with CMake option -DUSE_CUDA=1
```

**Comment by jameslamb** [comment]
> Then I tried to fit a model

Ah! Ok, so it wasn't coming from the build command.

I strongly suspect you passed `device = "cuda"` in `params` to `lgb.train()`. If you've built the library with `Rscript build_r.R --use-gpu`, pass `device = "gpu"` instead.

The R package currently only supports LightGBM's `GPU` build, which uses OpenCL to generate GPU kernels that work across GPUs from several manufacturers.

The R package doesn't support LightGBM's newer and faster `CUDA` build, a direct reimplementation of key operations in LightGBM as CUDA kernels. That is tracked in #3465 and #5378.

**Comment by nipnipj** [comment]
> Ok I opened terminal from LightGBM folder and used `Rscript build_r.R --use-gpu`. Then I tried to fit a model and the following message appears:
> 
> ```
> [LightGBM] [Fatal] CUDA Tree Learner was not enabled in this build.
> Please recompile with CMake option -DUSE_CUDA=1
> Error in initialize(...) : 
>   CUDA Tree Learner was not enabled in this build.
> Please recompile with CMake option -DUSE_CUDA=1
> ```
No error when using "gpu" instead of "cuda".

**Comment by jameslamb** [comment]
> No error when using "gpu" instead of "cuda".

hmmmm that sounds like a bug. Because that error is only raised in one place...the constructor of `CUDASingleGPUTreeLearner` if you compiled the library without passing `-DUSE_CUDA=ON`.

https://github.com/microsoft/LightGBM/blob/4332b9d5152c90b211e6667093c6c2bdda3ea15c/src/treelearner/cuda/cuda_single_gpu_tree_learner.hpp#L153-L160

And the library will only try to instantiate one of those if you passed `device = "cuda"` in `params`.

https://github.com/microsoft/LightGBM/blob/4332b9d5152c90b211e6667093c6c2bdda3ea15c/src/treelearner/tree_learner.cpp#L41-L44

Can you please provide a minimal, reproducible example?

That's a small, self-contained snippet of R code that exactly produces this error. Something I could copy and run without modification.

And answers to these questions please:

* version of LightGBM
* version of R
* exact command(s) you ran to install the R package

**Comment by jameslamb** [comment]
Ah I see you closed this. @nipnipj did passing `device = "gpu"` fix this for you?

It'd be helpful if you could share the resolution you found, so we could learn if there is some bug that needs to be fixed and so other people finding this from search engines will be able to learn from your experience.
