### ISSUE TITLE
LGBM_BoosterUpdateOneIterCustom requires objective_func_ not null

### ISSUE THREAD

**Issue by parsiad** [microsoft/LightGBM#6393]
## Description
When I call `LGBM_BoosterUpdateOneIterCustom` and provide the gradient and Hessian diagonal manually, I get
```
Check failed: objective_function_ == nullptr at /build/source/src/boosting/gbdt.cpp
```

The check is here: https://github.com/microsoft/LightGBM/blob/28536a0a5d0c46598fbc930a63cec72399a969e4/src/boosting/gbdt.cpp#L347

All I did to create the booster was `LGBM_BoosterCreate`.

Any suggestions for how to circumvent this issue without manually removing the check?

**Comment by jameslamb** [comment]
Thanks for using LightGBM.

> *All I did to create the booster was `LGBM_BoosterCreate`.*

Ensure that you have `objective=custom` in the `parameters`.

https://github.com/microsoft/LightGBM/blob/28536a0a5d0c46598fbc930a63cec72399a969e4/src/c_api.cpp#L1945

That will tell LightGBM to set `objective_function_` on the `Booster` to a `nullptr`.

https://github.com/microsoft/LightGBM/blob/28536a0a5d0c46598fbc930a63cec72399a969e4/src/objective/objective_function.cpp#L100-L102

I believe that `CHECK()` is there because `objective_function_ == nullptr` is used by other code in `Booster::TrainOneIter()` to mean "gradients are being computed outside of LightGBM and provided directly", like in these places:

https://github.com/microsoft/LightGBM/blob/28536a0a5d0c46598fbc930a63cec72399a969e4/src/boosting/gbdt.cpp#L369-L371

https://github.com/microsoft/LightGBM/blob/28536a0a5d0c46598fbc930a63cec72399a969e4/src/boosting/gbdt.cpp#L407-L409

---

If this works, we should add a code comment on that `CHECK()` you hit and document `"custom"` in https://lightgbm.readthedocs.io/en/latest/Parameters.html#objective. Are you interested in contributing that?

**Comment by parsiad** [comment]
That works. Let's move the discussion to the PR: https://github.com/microsoft/LightGBM/pull/6396
