### ISSUE TITLE
Inquiry about Release Date for GPU Training Bug "bin size 257" FIX

### ISSUE THREAD

**Issue by RunxingZhong** [microsoft/LightGBM#6480]
I encountered an issue when using LightGBM for training with GPU, which leads to an error. 

I noticed that this issue has been resolved here: https://github.com/microsoft/LightGBM/pull/6019. 

It has been almost six months since the last version was released. 
Could you please let me know when the next version, including this fix, will be released?

Thank you very much

**Comment by jameslamb** [comment]
You can subscribe to #6439 (or "watch" the repo, per https://docs.github.com/en/account-and-profile/managing-subscriptions-and-notifications-on-github/setting-up-notifications/configuring-notifications#about-participating-and-watching-notifications) to be notified when the next release goes out.

That release will include the fix for #6019.
