### ISSUE TITLE
How to use gpu when lightgbm installed through pip?

### ISSUE THREAD

**Issue by louispotok** [Microsoft/LightGBM#650]
I installed lightgbm through pip (It was so easy! Thanks for doing that.)

Now I'm trying to train using a GPU, as per [this tutorial](https://github.com/Microsoft/LightGBM/blob/master/docs/GPU-Tutorial.md) and I think it's missing a section on how to do this after a pip installation.

I tried just setting 'device=gpu' and got the following error: 'GPU Tree Learner was not enabled in this build. Recompile with CMake option -DUSE_GPU=1'. This makes sense if I had compiled it myself, but I'm stuck here -- is it possible to recompile a package installed through pip, if so how to do it, and whether it's the right solution here.

There's a [related issue](https://github.com/Microsoft/LightGBM/issues/627) for someone using R, but I can't find anything about this specifically.

**Comment by guolinke** [comment]
as mentioned in our document, the gpu version only can be installed from github now: https://github.com/Microsoft/LightGBM/tree/master/python-package .

@wxchan , can we pass the parameter ```--use_gpu``` to ```setup.py``` when installing from pip ?

**Comment by wxchan** [comment]
@guolinke there is an option `--install-option` https://pip.pypa.io/en/stable/reference/pip_install/#cmdoption-install-option, no sure if it works

**Comment by wxchan** [comment]
I made a test, the `--install-option='--gpu'` option only can be used for `python setup.py --gpu install` instead of `python setup.py install --gpu`, so we need another way to register new argument. This thread might help: https://stackoverflow.com/questions/18725137/how-to-obtain-arguments-passed-to-setup-py-from-pip-with-install-option.

Another option is we release another package like `lightgbm-gpu`.

**Comment by guolinke** [comment]
refer to the new document: https://github.com/Microsoft/LightGBM/tree/master/python-package
