### ISSUE TITLE
It seems that larger_leaf_histogram_array_ points to the smaller?

### ISSUE THREAD

**Issue by pengxiao-song** [microsoft/LightGBM#6747]
## Description

Thanks for nice work!! Recently I read the source code. I don’t quite understand how the code of "Reproducible example" works. It seems that larger_leaf_histogram_array_ points to the node with a smaller number of samples. Is that correct? Why not write it like this instead?

```cpp
} else if (num_data_in_left_child < num_data_in_right_child) {
    if (histogram_pool_.Get(right_leaf, &larger_leaf_histogram_array_)) { parent_leaf_histogram_array_ = larger_leaf_histogram_array_; }
    histogram_pool_.Get(left_leaf, &smaller_leaf_histogram_array_);
```

## Reproducible example

```cpp
} else if (num_data_in_left_child < num_data_in_right_child) {
  // put parent(left) leaf's histograms into larger leaf's histograms
  if (histogram_pool_.Get(left_leaf, &larger_leaf_histogram_array_)) { parent_leaf_histogram_array_ = larger_leaf_histogram_array_; }
  histogram_pool_.Move(left_leaf, right_leaf);
  histogram_pool_.Get(left_leaf, &smaller_leaf_histogram_array_);
```

I am a little confused. Thanks for your response.

**Comment by jameslamb** [comment]
Thanks for using LightGBM.

> how the code of "Reproducible example" works

What is this a reference to? Where did this code come from? Can you please provide some links?

**Comment by pengxiao-song** [comment]
I apologize for the lack of clarity in my previous issue. Let me provide more context.

The piece of code in question comes from:
https://github.com/microsoft/LightGBM/blob/186c7cd47a72c080ccfccdf799b0fbe8da2ff53a/src/treelearner/serial_tree_learner.cpp#L369


I believe the related code is performing operations to update `larger_leaf_histogram_array_` and `smaller_leaf_histogram_array_`.

Specifically, can the code be written this way?

```
} else if (num_data_in_left_child < num_data_in_right_child) {
    if (histogram_pool_.Get(right_leaf, &larger_leaf_histogram_array_)) { parent_leaf_histogram_array_ = larger_leaf_histogram_array_; }
    histogram_pool_.Get(left_leaf, &smaller_leaf_histogram_array_);
```

like

https://github.com/microsoft/LightGBM/blob/186c7cd47a72c080ccfccdf799b0fbe8da2ff53a/src/treelearner/serial_tree_learner.cpp#L376

Could you please help clarify the reasoning behind the current structure? Thank you very much!

**Comment by shiyu1994** [comment]
Hi @pengxiao-song, thanks for using LightGBM.

We should first clarify why we need `larger_leaf_histogram_array_`. It is used in the subtraction operation here to get the histogram of the larger leaf.
https://github.com/microsoft/LightGBM/blob/480600b3afaf2a0a6f32cf417edf9567f625b2c3/src/treelearner/serial_tree_learner.cpp#L573-L576

And we should notify that the index of `left_leaf` inherits the index of `parent_leaf`, after the `parent_leaf` is split. Thus,
https://github.com/microsoft/LightGBM/blob/480600b3afaf2a0a6f32cf417edf9567f625b2c3/src/treelearner/serial_tree_learner.cpp#L371
is doing this:

Get the larger leaf histogram, which is always from `histogram_pool_.Get(left_leaf, &larger_leaf_histogram_array_)`. The larger histogram will always be **the histogram of the parent leaf** (if with enough memory space to store these parent histograms) since it is obtained by **subtracted the small histogram from the parent histogram**. So, we just make the larger histogram points to the parent histogram, and after the subtraction the content in the parent histogram **becomes** the larger histogram.

**Comment by pengxiao-song** [comment]
Thank you so much for your detailed response. I truly appreciate it and will take the time to carefully learn the source code logic.
