### ISSUE TITLE
data_size_t only supports 32 bit integers (too small?)

### ISSUE THREAD

**Issue by hatooku** [Microsoft/LightGBM#830]
https://github.com/Microsoft/LightGBM/blob/19eececfb889f03640e8c90bb09a00f9bb4a9f2f/include/LightGBM/meta.h#L14

Is it possible to change data_size_t to support 64 bit integers? I'm trying to run lambdarank, but my query_id's are 54 bit integers, so they do not work as the vector queries_ has type vector<data_size_t>. Also, with the change it can support larger datasets.

**Comment by guolinke** [comment]
using 64-bit integer will be much slower, and 32-bit is enough for most case. So we use 32-bit integer by default. 
I think it isn't small for single machine (due to memory limitation in single machine). And for the big data case, I think using parallel learning is a better choice. 


the solution for your query_id problem:
1.  If the number of unique value of your query_id is smaller than 32-bit, you can just map it to 32-bit integer.
2.  Use query file instead.
3. change `data_size_t` to `int64_t` in LightGBM/include/LightGBM/meta.h and recompile.
