### ISSUE TITLE
Does the order of the feature matters when training?

### ISSUE THREAD

**Issue by ZLake** [Microsoft/LightGBM#930]
Hi, there:
I am working on feature selection using the feature importance obtained from the trained lgb model on all features. 

However, I found strange results. When I use the feature index array (named selected_feature, values are the indexes of the features to keep) of the selected feature index to select the features, which can be written as train[:,selected_feature]. Then I feed this to the algorithm. Interesting things happened, with the same feature index array, but different order, the trained lgb models are different. 

Then I tested this by let the input train data to be train[:, permuation_idx] and test data to be test[:, permuation_idx],where permuation_idx = np.random.permutation(train.shape[1]). Every time the result differs. 

So with the same feature but different column order in the train data set, the result model differs. I want to know is this normal or is there some way I can make the trained model stable with the same feature?

Thanks in advance.

**Comment by guolinke** [comment]
@ZLake 
If you are using the sub_col (feature_fraction, subcol_per_tree), the result will be different, since the features are chosen according to their index. 

if you are using the full features.  it is possible if there are some similar features. 
And i think this problem cannot be avoided if you want the different column orders.
tree learning algorithm is a greedy process of finding the most useful (max split gain) feature.  when 2 features are similar, they may have the same split gain. in such a condition, LightGBM will choose the feature with smaller index.
