### ISSUE TITLE
Use feature name in prediction

### ISSUE THREAD

**Issue by guolinke** [Microsoft/LightGBM#980]
The model file has stored the feature names. However, the prediction is still based on feature indices. 
As a result the prediction will fail when test dataset changes column order of features.

**Comment by bbennett36** [comment]
Does this solve your problem?  (Coming from the FAQ page)

Solution 2: Because LightGBM constructs bin mappers to build trees, and train and valid Datasets within one Booster share the same bin mappers, categorical features and feature names etc., the Dataset objects are constructed when construct a Booster. And if you set free_raw_data=True (default), the raw data (with Python data struct) will be freed. So, if you want to:

get label(or weight/init_score/group) before construct dataset, it's same as get self.label
set label(or weight/init_score/group) before construct dataset, it's same as self.label=some_label_array
get num_data(or num_feature) before construct dataset, you can get data with self.data, then if your data is numpy.ndarray, use some code like self.data.shape
set predictor(or reference/categorical feature) after construct dataset, you should set free_raw_data=False or init a Dataset object with the same raw data

**Comment by guolinke** [comment]
@bbennett36 
I think we are talking about different topics. I know change the feature order in python/R is easy, so that will be a big problem. 

But in CLI version, this is a problem, especially when using weight_column/ignore_column.

**Comment by desperadox** [comment]
@guolinke 
I met the same problem.
Can we write more information in the mode file? I think it could be not enough to record only the index. Such as label name, weight name, ignored column and a hashmap( the key is the used feature name and values is the index in the train data).
